SET DEFINE OFF;
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (10, 'SALES', '10000000', 0, '销售管理',
    '#', 0, 1, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (11, 'DATA', '11000000', 0, '数据维护',
    '#', 0, 1, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (12, 'INVENTORY', '12000000', 0, '库存管理',
    '#', 0, 1, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (13, 'PAYOUT', '13000000', 0, '兑奖',
    '#', 0, 1, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (14, 'CAPITAL', '14000000', 0, '资金管理',
    '#', 0, 1, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (15, 'MARKET MANAGER', '15000000', 0, '市场管理员账户',
    '#', 0, 1, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (16, 'REPORT', '16000000', 0, '报表',
    '#', 0, 1, 21);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (17, 'OUTLET SERVICE', '17000000', 0, '站点服务',
    '#', 0, 1, 24);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (18, 'SYSTEM', '18000000', 0, '系统管理',
    '#', 0, 1, 27);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (19, 'MONITOR', '19000000', 0, '监控',
    '#', 0, 1, 26);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (44, 'VALIDATE', '44000000', 0, '验票管理',
    '#', 0, 1, 44);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1001, 'Purchase Order Apply', '10010000', 0, '订单申请',
    '/order.do?method=listOrderByApplyUser', 10, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1002, 'Purchase Order Inquery', '10020000', 0, '订单查询',
    '/order.do?method=listOrderForInquery', 10, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1003, 'Stock Transfer Apply', '10030000', 0, '调拨单申请',
    '/transfer.do?method=listTransferByApplyUser', 10, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1004, 'Stock Transfer Approval', '10040000', 0, '调拨单审批',
    '/transfer.do?method=listTransferForInquery', 10, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1005, 'Delivery Order Apply', '10050000', 0, '出货单申请',
    '/delivery.do?method=listDeliveryByApplyUser', 10, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1006, 'Delivery Order Inquery', '10060000', 0, '出货单查询',
    '/delivery.do?method=listDeliveryForInquery', 10, 2, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1101, 'Administrative Areas', '11010000', 0, '行政区域管理',
    '/areas.do?method=listAreas', 11, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1102, 'Institutions', '11020000', 0, '代理商管理',
    '/institutions.do?method=listInstitutions', 11, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1103, 'Outlets', '11030000', 0, '站点管理',
    '/outlets.do?method=listOutlets', 11, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1201, 'Plans', '12010000', 0, '方案管理',
    '/plans.do?method=listPlans', 12, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1202, 'Warehouses', '12020000', 0, '仓库管理',
    '/warehouses.do?method=listWarehouses', 12, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1203, 'Goods Receipts', '12030000', 0, '入库管理',
    '#', 12, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1204, 'Goods Issues', '12040000', 0, '出库管理',
    '#', 12, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1205, 'Inventory', '12050000', 0, '库存管理',
    '#', 12, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1206, 'Damaged Goods', '12060000', 0, '损毁管理',
    '/damagedGoods.do?method=listDamagedGoods', 12, 2, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1207, 'Logistics Information', '12070000', 0, '物流查询',
    '/logistics.do?method=initLogistics', 12, 2, 21);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1208, 'Batch Termination', '12080000', 0, '批次终结',
    '/termination.do?method=initBathTermination', 12, 2, 24);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1209, 'Item Maintenance', '12090000', 0, '物品管理',
    '#', 12, 2, 27);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1301, 'Process Payout', '13010000', 0, '中心兑奖',
    '/payout.do?method=initProcessPayout', 13, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1303, 'Payout Records', '13030000', 0, '兑奖查询',
    '/payout.do?method=listPayout', 13, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1401, 'Institution Capital', '14010000', 0, '部门资金管理',
    '#', 14, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1402, 'Account Maintenance', '14020000', 0, '资金账户管理',
    '#', 14, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1403, 'Cash Withdrawn Approval', '14030000', 0, '提现管理',
    '/cashWithdrawn.do?method=listCashWithdrawn', 14, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1404, 'Return Deliveries', '14040000', 0, '还货管理',
    '/return.do?method=listReturnDeliveries', 14, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1405, 'Repayment', '14050000', 0, '还款管理',
    '/repayment.do?method=listRepayment', 14, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1406, 'Outlet Adjustment', '14060000', 0, '站点调账',
    '/account.do?method=getOutletInfo', 14, 2, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1501, 'Return Delivery', '15010000', 0, '还货申请',
    '/returnDelivery.do?method=listReturnDeliveries', 15, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1502, 'Inventory Information', '15020000', 0, '库存查询',
    '/repaymentRecord.do?method=listInventory', 15, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1503, 'Register Damaged Goods', '15030000', 0, '损毁登记',
    '/damegeGood.do?method=initDamageGood', 15, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1504, 'Account Balance', '15040000', 0, '账户余额查询',
    '/marketManagerBalance.do?method=queryAccountBalance', 15, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1505, 'Repayment Records', '15050000', 0, '还款记录',
    '/repaymentRecord.do?method=listRepaymentRecords', 15, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1506, 'MM Transaction Records', '15060000', 0, '市场管理员交易记录查询',
    '/transferRecord.do?method=listMMTransferRecords', 15, 2, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1601, 'Fund Report', '16010000', 0, '资金报表',
    '#', 16, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1602, 'Sales Report', '16020000', 0, '销售报表',
    '#', 16, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1603, 'Inventory Report', '16030000', 0, '库存报表',
    '#', 16, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1604, 'Charts', '16040000', 0, '统计图表',
    '#', 16, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1605, 'Analysis', '160450000', 0, '数据分析报表',
    '#', 16, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1701, 'Outlet Information', '17010000', 0, '站点信息查询',
    '/outletInfo.do?method=listOutletInfo', 17, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1702, 'Transaction Records', '17020000', 0, '交易流水查询',
    '/outlets.do?method=agencyDealRecord', 17, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1703, 'Return Delivery Records', '17030000', 0, '退货查询',
    '/returnedGoods.do?method=returnGoodsList', 17, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1704, 'Fund Daliy Record', '17040000', 0, '资金日结',
    '/outlets.do?method=fundDailyRecord', 17, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1705, 'Sales Records', '17050000', 0, '入库销售记录',
    '/outletGoods.do?method=outletGoodsList', 17, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1706, 'Cash Withdrawn Records', '17060000', 0, '提现记录',
    '/withdrawnRecords.do?method=listWithdrawnRecords', 17, 2, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1801, 'Users', '18010000', 0, '用户管理',
    '/user.do?method=listUsers', 18, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1802, 'Roles', '18020000', 0, '角色管理',
    '/role.do?method=listRoles', 18, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1803, 'Change Password', '18030000', 0, '修改密码',
    '/user.do?method=initChangePwd', 18, 2, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1804, 'Change Trans Password', '18040000', 0, '修改交易密码',
    '/marketManagerPwd.do?method=changeMarketManagerPwd', 18, 2, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1805, 'System Parameter', '18050000', 0, '系统参数配置',
    '/sysParameter.do?method=sysParameterList', 18, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1901, 'Summary Statistics', '19010000', 0, '监控统计图汇总',
    '/monitor.do?method=summaryStatistics', 19, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1902, 'Real-Time Sales', '19020000', 0, '游戏销量监控',
    '/monitor.do?method=salesRealTime', 19, 2, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1905, 'Outlet Rankings', '19050000', 0, '站点销售排行',
    '/monitor.do?method=outletRankings', 19, 2, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (4401, 'Scan Tickets', '44010000', 0, '扫票验票',
    '/checktickets.do?method=scanTickets', 44, 2, 1);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (4403, 'Inquiry', '44030000', 0, '验票查询',
    '/checktickets.do?method=inquiryCheckedTickets', 44, 2, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (4405, 'Statistical Reports', '44050000', 0, '统计报表',
    '/checktickets.do?method=statisticalReports', 44, 2, 5);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (4407, 'Refused Records', '44070000', 0, '拒绝兑奖统计',
    '/checktickets.do?method=refusedRecords', 44, 2, 7);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120301, 'Goods Receipts Information', '12030100', 0, '入库查询',
    '/goodsReceipts.do?method=listGoodsReceipts', 1203, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120302, 'Goods Receipt by Batch', '12030200', 0, '批次入库',
    '/goodsReceipts.do?method=receiptByBatch', 1203, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120303, 'Goods Receipt by Stock Transfer', '12030300', 0, '调拨单入库',
    '/goodsReceipts.do?method=receiptByStockTransfer', 1203, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120304, 'Goods Receipt by Return Delivery', '12030400', 0, '还货入库',
    '/goodsReceipts.do?method=receiptByRetrunDelevery', 1203, 3, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120401, 'Goods Issue Information', '12040100', 0, '出库查询',
    '/goodsIssues.do?method=listGoodsIssues', 1204, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120402, 'Goods Issue by Stock Transfer', '12040200', 0, '调拨单出库',
    '/goodsIssues.do?method=issueByStockTransfer', 1204, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120403, 'Goods Issue by Delivery Order', '12040300', 0, '出货单出库',
    '/goodsIssues.do?method=issueByDeliveryOrder', 1204, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120501, 'Inventory Information', '12050100', 0, '库存查询',
    '/inventory.do?method=listInventoryInfo', 1205, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120502, 'Process Inventory Check', '12050200', 0, '库存盘点',
    '/inventory.do?method=listInventoryCheck', 1205, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120901, 'Item Types', '12090100', 0, '类别管理',
    '/item.do?method=listItemTypes', 1209, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120902, 'Item Receipts', '12090200', 0, '入库管理',
    '/item.do?method=listGoodsReceipts', 1209, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120903, 'Item Issues', '12090300', 0, '出库管理',
    '/item.do?method=listGoodsIssues', 1209, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120904, 'Inventory Information', '12090400', 0, '库存查询',
    '/item.do?method=listInventoryInfo', 1209, 3, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120905, 'Process Inventory Check', '12090500', 0, '库存盘点',
    '/item.do?method=listInventoryCheck', 1209, 3, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120906, 'Damaged Items', '12090600', 0, '物品损毁',
    '/item.do?method=listDamagedItems', 1209, 3, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140101, 'Top Ups', '14010100', 0, '充值',
    '/topUps.do?method=listTopUps', 1401, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140102, 'Cash Withdrawn', '14010200', 0, '提现申请',
    '/orgsWithdrawnRecords.do?method=listRecords', 1401, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140103, 'Account Balance', '14010300', 0, '账户余额',
    '/accountBalance.do?method=listAccountBalance', 1401, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140104, 'Capital Record', '14010400', 0, '部门资金流水',
    '/capitalRecord.do?method=listCapitalRecords', 1401, 3, 1);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140201, 'Outlet Accounts', '14020100', 0, '站点账户管理',
    '/account.do?method=listOutletAccounts', 1402, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140202, 'Institution Accounts', '14020200', 0, '部门账户管理',
    '/account.do?method=listInstitutionAccounts', 1402, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (140203, 'Market Managers Accounts', '14020300', 0, '市场管理员账户管理',
    '/account.do?method=listMarketManagersAccounts', 1402, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160101, 'Inst Outlets Statistics', '16010100', 0, '部门站点统计',
    '/saleReport.do?method=institutionFundReport', 1601, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160102, 'Outlet Fund Report', '16010200', 0, '站点资金报表',
    '/saleReport.do?method=outletFundReport', 1601, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160103, 'Inst Outlets Statistics(USD)', '16010300', 0, '部门站点统计(美金)',
    '/saleReport.do?method=institutionFundReportUSD', 1601, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160104, 'Outlet Fund Report(USD)', '16010400', 0, '站点资金报表(美元)',
    '/saleReport.do?method=outletFundReportUSD', 1601, 3, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160105, 'MM Capital Daliy Report', '16010500', 0, '市场管理员资金日结报表',
    '/saleReport.do?method=mmCapitalDaliyReport', 1601, 3, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160106, 'Inst Payable Report', '16010600', 0, '部门应缴款报表',
    '/saleReport.do?method=institutionPayableReport', 1601, 3, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160107, 'Inst Payable Report(USD)', '16010700', 0, '部门应缴款报表(美元)',
    '/saleReport.do?method=institutionPayableReportUSD', 1601, 3, 21);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160108, 'Agent Fund Report', '16010800', 0, '代理商资金报表',
    '/saleReport.do?method=agentFundReport', 1601, 3, 24);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160109, 'Agent Fund Report(USD)', '16010900', 0, '代理商资金报表(美金)',
    '/saleReport.do?method=agentFundReportUSD', 1601, 3, 27);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160201, 'Sales Reports', '16020100', 0, '游戏销售报表',
    '/saleReport.do?method=initGameSalesReport', 1602, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160202, 'Institution Sales Reports', '16020200', 0, '部门销售报表',
    '/saleReport.do?method=initInstitutionSalesReport', 1602, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160203, 'Payout Reports', '16020300', 0, '兑奖报表',
    '/report.do?method=initPayoutReports', 1602, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160204, 'Validate Winning Report', '16020400', 0, '验奖统计报表',
    '/checktickets.do?method=statisticalReports', 1602, 3, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160301, 'Inventory Reports', '16030100', 0, '库存报表',
    '/saleReport.do?method=initInventoryReports', 1603, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160302, 'MM Inventory Daliy Report', '16030200', 0, '市场管理员库存日结报表',
    '/saleReport.do?method=mmInventoryDaliyReport', 1603, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160303, 'Institution Daliy Report', '16030300', 0, '部门库存日结报表',
    '/saleReport.do?method=institutionInventoryDaliyReport', 1603, 3, 9);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160304, 'Outlet Daliy Report', '16030400', 0, '站点库存日结报表',
    '/saleReport.do?method=outletInventoryDaliyReport', 1603, 3, 12);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160305, 'HQ Item Issue Report', '16030500', 0, '总部物品出库报表',
    '/hqItemIssueReport.do?method=initHQItemIssueReport', 1603, 3, 15);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160306, 'HQ Issue Statistics', '16030600', 0, '总部方案出库报表',
    '/goodsReceiptsReport.do?method=initGoodsOutReport', 1603, 3, 18);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160307, 'HQ Receipt Statistics', '16030700', 0, '总部方案入库汇总',
    '/goodsReceiptsReport.do?method=initGoodsReceiptsReport', 1603, 3, 21);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160401, 'Institution Sales', '16040100', 0, '部门监控统计',
    '/monitor.do?method=institutionSales', 1604, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160402, 'Sales Statistics', '16040200', 0, '游戏销售监控',
    '/monitor.do?method=salesStatistics', 1604, 3, 6);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160501, 'Outlets Info Statistics', '16050100', 0, '站点信息统计',
    '/analysis.do?method=outletStatistics', 1605, 3, 3);
Insert into KWS.ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (120503, 'Inventory Check Inquiry', '12050300', 0, '库存盘点查询',
    '/inventory.do?method=listInventoryCheckInquiry', 1205, 3, 9);

COMMIT;
