prompt 正在导入初始化数据 [INIT DATA -> 10-init_menu.sql ]......
SET DEFINE OFF;

Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (30, 'GAME', '0102000000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '游戏管理', '/gameManagement.do?method=param',
    0, 1, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (31, 'ISSUE', '0103000000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '期次管理', '/issueManagement.do?method=issueManagementTabs',
    0, 1, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (32, 'MANAGEMENT', '0105000000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '业务管理', '#',
    0, 1, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (34, 'TICKET', '0107000000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '彩票管理', '#',
    0, 1, 15);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (36, 'REPORT', '00360000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '报表', '#',
    0, 1, 21);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (37, 'MONIOTR', '00370000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '监控', '#',
    0, 1, 24);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (1104, 'Teller', '11040000', 0, '销售员管理',
    '/teller.do?method=listTeller', 11, 2, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3001, 'Game Parameter', '0102010000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '游戏参数', '/gameManagement.do?method=param',
    30, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3002, 'Game Control', '0102030000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '游戏控制', '/gameManagement.do?method=control',
    30, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3003, 'Prize Pool', '0102040000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '奖池管理', '#',
    30, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3004, 'Adjustment Fund', '0102050000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '调节基金管理', '#',
    30, 2, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3005, 'Issuance Fee', '0102050000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '发行费管理', '/fundManagement.do?method=govCommision',
    30, 2, 15);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3101, 'Issue Inquiry', '0103010000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '期次查询', '/issueManagement.do?method=issueManagementTabs',
    31, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3102, 'Game Drawing', '0103020000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '游戏开奖', '/gameDraw.do?method=manualDraw',
    31, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3103, 'NewIssue-manual', '0103030000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '手工排期', '/issueManagement.do?method=preArrangementTabs',
    31, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3104, 'Newissue-templet', '0103040000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '模版排期', '/issueManagement.do?method=pre_qlx_tty',
    31, 2, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER, 
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL, 
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3201, 'Institution', '0105010000', 1, 1, 
    '1111111', '00:00:00', '23:59:00', '机构管理', '/omsarea.do?method=listOMSArea', 
    32, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3202, 'Outlet', '0105020000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '销售站管理', '/agency.do?method=listAgency',
    32, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3203, 'Terminal', '0105030000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '终端机管理', '/terminal.do?method=listTerminal',
    32, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3205, 'Notice', '0105050000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '通知管理', '#',
    32, 2, 15);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3206, 'Version', '0105060000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '版本管理', '#',
    32, 2, 18);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3401, 'Ticket Inquiry', '0107010000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '彩票查询', '/centerSelect.do?method=centerSelect',
    34, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3402, 'Ticket Payout', '0107020000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '彩票兑奖', '/centerSelect.do?method=expirydateint',
    34, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3403, 'Payout Records', '0107030000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '兑奖记录查询', '/expirydate.do?method=list',
    34, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3404, 'Ticket Refund', '0107040000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '彩票退票', '/refundquery.do?method=refundInit',
    34, 2, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3405, 'Refund Records', '0107050000', 1, 0,
    '1111111', '00:00:00', '23:59:00', '退票记录查询', '/refundquery.do?method=list',
    34, 2, 15);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3406, 'Abandoned Award Inquiry', '00003406', 1, 1,
    '1111111', '00:00:00', '23:59:00', '弃奖查询', '/abandon.do?method=abandonAward',
    34, 2, 18);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER, 
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL, 
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3407, 'Broken Ticket Inquiry', '34070000', 1, 1, 
    '1111111', '00:00:00', '23:59:00', '残票查询', '/badticketquery.do?method=badticketlist', 
    34, 2, 21);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3601, 'Lottery Winning Statistics', '36010000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '中奖统计表', '/misReport.do?method=misReport3132',
    36, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3602, 'Prize Payout Statistics (By Issue and Prize Level)', '36020000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '兑奖统计表(按奖等统计)', '/misReport.do?method=misReport3133',
    36, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3603, 'Prize Payout Statistics (By Issue and Prize)', '36030000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '兑奖统计表(按奖金统计)', '/misReport.do?method=misReport3134',
    36, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3604, 'Abandoned Award Statistics', '36040000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '弃奖统计表', '/misReport.do?method=misReport3135',
    36, 2, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3605, 'Dynamic Prize Table', '36050000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '奖金动态表', '/misReport.do?method=misReport3136',
    36, 2, 15);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3701, 'ISSUES', '37010000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '期次监控', '/gameIssue.do?method=listGameIssue',
    37, 2, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3702, 'ONLINE TERMINALS', '37020000', 1, 1,
    '1111111', '00:00:00', '23:59:00', '上线终端机', '#',
    37, 2, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (3703, 'Event Management', '00370100', 1, 1,
    '1111111', '00:00:00', '23:59:00', '事件控制台', '#',
    37, 2, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160503, 'Inst Outlets Statistcs(By Lottery Type)', '16050300', 0, '部门站点统计(按彩票类型)',
    '/analysis.do?method=instFundReportByLotType', 1605, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_REMARK,
    PRIVILEGE_URL, PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (160504, 'Agent Fund Report(By Lottery Type)', '16050400', 0, '代理商资金报表(按彩票类型)',
    '/analysis.do?method=agentFundReportByLotType', 1605, 3, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300301, 'Pool by Item', '0102040100', 1, 1,
    '1111111', '00:00:00', '23:59:00', '奖池流水', '/gameManagement.do?method=poolAdj',
    3003, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300302, 'Pool by Issue', '0102040200', 1, 1,
    '1111111', '00:00:00', '23:59:00', '期次奖池', '/gameManagement.do?method=poolManagement',
    3003, 3, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300303, 'Pool Adjustment', '0102040300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '奖池调整', '/gameManagement.do?method=createPoolAdj',
    3003, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300401, 'Adjustment Fund by Item', '0102050100', 1, 1,
    '1111111', '00:00:00', '23:59:00', '调节基金流水', '/fundManagement.do?method=fundList',
    3004, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300402, 'Adjustment Fund by Issue', '0102050200', 1, 1,
    '1111111', '00:00:00', '23:59:00', '期次调节基金', '/fundManagement.do?method=issueFundInfo',
    3004, 3, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (300403, 'Change Adjustment Fund', '0102050300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '调节基金调整', '/fundManagement.do?method=createFundAdj',
    3004, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320501, 'Outlet Notice', '0105050100', 1, 0,
    '1111111', '00:00:00', '23:59:00', '销售站公告', '/tmnotice.do?method=notifyList',
    3205, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320503, 'Ticket Slogan', '0105050300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '票面宣传语', '/tmnotice.do?method=sendTicketInfo',
    3205, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320504, 'Scrolling Notice', '00320504', 1, 1,
    '1111111', '00:00:00', '23:59:00', '滚动字幕', '/tmnotice.do?method=getScrollingNotice',
    3205, 3, 12);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320601, 'Software Package', '0105060200', 1, 1,
    '1111111', '00:00:00', '23:59:00', '软件包管理', '/tmversionPackage.do?method=listSoftPackage',
    3206, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320602, 'Upgrade Plan', '0105060300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '升级计划', '/updatePlan.do?method=updatePlanList',
    3206, 3, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (320603, 'Software Inquiry', '0105060400', 1, 1,
    '1111111', '00:00:00', '23:59:00', '软件查询', '/terminalSoftWare.do?method=terminalSoftWareList',
    3206, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370201, 'Online Distribution', '37020100', 1, 1,
    '1111111', '00:00:00', '23:59:00', '上线数量监控', '/areaTerminal.do?method=areaTerminalCulumn',
    3702, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370202, 'Online Percentage', '37020200', 1, 1,
    '1111111', '00:00:00', '23:59:00', '上线占比图', '/areaTerminal.do?method=areaTerminalPie',
    3702, 3, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370203, 'Online Ratio', '37020300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '上线率曲线图', '/areaTerminal.do?method=areaTerminalLine',
    3702, 3, 9);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370301, 'Event List Inquiry', '00370100', 1, 1,
    '1111111', '00:00:00', '23:59:00', '事件列表查询', '/event.do?method=listEvents',
    3703, 3, 3);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370302, 'Settlement Logs', '37030200', 1, 1,
    '1111111', '00:00:00', '23:59:00', '结算日志', '/taishanLog.do?method=listLog',
    3703, 3, 6);
Insert into ADM_PRIVILEGE
   (PRIVILEGE_ID, PRIVILEGE_NAME, PRIVILEGE_CODE, PRIVILEGE_SYSTEM, PRIVILEGE_IS_CENTER,
    PRIVILEGE_AGREEDAY, PRIVILEGE_LOGINBEGIN, PRIVILEGE_LOGINEND, PRIVILEGE_REMARK, PRIVILEGE_URL,
    PRIVILEGE_PARENT, PRIVILEGE_LEVEL, PRIVILEGE_ORDER)
 Values
   (370303, 'Data Collection', '37030300', 1, 1,
    '1111111', '00:00:00', '23:59:00', '上传日志', '/trace.do?method=listTrace',
    3703, 3, 9);
COMMIT;


prompt 正在导入初始化数据 [INIT DATA -> 12-init_privlege.sql ]......
/****************************************************/
/****************  修改说明  ************************/
-- created by 陈震 @ 2015/9/8
--       新增超级用户
/***************************************************/


insert into adm_role_admin(admin_id, role_id)values(1, 1);

--超级管理员
insert into adm_role_privilege select 0 as role_id,p.privilege_id from adm_privilege p  where (0,p.privilege_id) not in (select * from adm_role_privilege b);
--系统管理员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1805);
--仓库管理员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120305);
--部门经理
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1903);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1904);
--总部管理人员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1903);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1904);
--站点账户
commit;

prompt 正在导入初始化数据 [INIT DATA -> 13-init_other.sql ]......
/****************************************************/
/****************  修改说明  ************************/
-- created by 陈震 @ 2015/9/8
--       新增银行、销售站类型和印制厂商基本信息
/***************************************************/


-- 销售站类型
insert into INF_STORETYPES values (25,'Other/其他',1);
commit;

-- 泰山系统参数
update SYS_PARAMETER set SYS_DEFAULT_DESC='管理员兑奖，代销费属于（1-销售站点，2-不计算）' where SYS_DEFAULT_SEQ=2;
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1005, '销售站默认兑奖佣金比例(千分位)', '0');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1006, '销售站默认销售佣金比例(千分位)', '70');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1007, '销售站默认兑奖范围 (0=总公司, 1=分公司, 4=销售站)', '1');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1008, '销售站默认信用额度', '100000');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1009, '七龙星开奖周期描述', 'Every DAY');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1010, '天天赢开奖周期描述', 'Every DAY');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1011, '时时彩开奖周期描述', 'Every 10 Minutes');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1012, '快三开奖周期描述', 'Every 10 Minutes');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1013, '11选5开奖周期描述', 'Every 1 Hour');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1014, '终端退票限额', '1');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1015, '分公司退票限额', '1');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1016, '是否启用分公司退票限额（1=限制，2=不限制）', '1');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1101, 'Lucky5滚动字幕1', 'Welcome to buy lottery tickets!!');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1102, 'Lucky5滚动字幕2', ' ');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1103, 'Lucky5滚动字幕3', ' ');
insert into SYS_PARAMETER (SYS_DEFAULT_SEQ, SYS_DEFAULT_DESC, SYS_DEFAULT_VALUE) values (1104, 'TDS版本号', '1.0.0');

commit;

prompt 正在导入初始化数据 [INIT DATA -> 21-init_game_ts.sql ]......
SET DEFINE OFF;

insert into INF_GAMES (GAME_CODE,GAME_MARK,BASIC_TYPE,FULL_NAME,SHORT_NAME,ISSUING_ORGANIZATION) values (12,12,1,'Lucky5','Lucky5','CLS');


insert into GP_STATIC (GAME_CODE,DRAW_MODE,SINGLEBET_AMOUNT,SINGLETICKET_MAX_ISSUES,LIMIT_BIG_PRIZE,LIMIT_PAYMENT,LIMIT_PAYMENT2,LIMIT_CANCEL2,ABANDON_REWARD_COLLECT)
               values (12,1,1000,12,40000000,4000000000,4000000,1,2);

insert into GP_DYNAMIC (GAME_CODE,SINGLELINE_MAX_AMOUNT,SINGLETICKET_MAX_LINE,SINGLETICKET_MAX_AMOUNT,CANCEL_SEC,
                        SALER_PAY_LIMIT,SALER_CANCEL_LIMIT,ISSUE_CLOSE_ALERT_TIME,IS_PAY,IS_SALE,IS_CANCEL,IS_AUTO_DRAW,
                        SERVICE_TIME_1,SERVICE_TIME_2,AUDIT_SINGLE_TICKET_SALE,AUDIT_SINGLE_TICKET_PAY,
                        AUDIT_SINGLE_TICKET_CANCEL,CALC_WINNING_CODE)
               values  (12,100,5,4000000,0,400000,1,300,1,1,1,1,'00:00-23:59','-',400000,400000,400000,'');

insert into GP_HISTORY (HIS_HIS_CODE,HIS_MODIFY_DATE,GAME_CODE,IS_OPEN_RISK,RISK_PARAM) values (0,sysdate,12,1,'0:800000000');

insert into GP_POLICY (HIS_POLICY_CODE,HIS_MODIFY_DATE,GAME_CODE,THEORY_RATE,FUND_RATE,ADJ_RATE,TAX_THRESHOLD,TAX_RATE,DRAW_LIMIT_DAY) values (0,sysdate,12,727,0,30,0,0,30);

insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,1, 'Pick 2','Lucky5 Pick 2',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,2, 'Pick 3','Lucky5 Pick 3',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,3, 'Pick 4','Lucky5 Pick 4',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,4, 'Pick 5','Lucky5 Pick 5',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,5, 'Pick 6','Lucky5 Pick 6',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,6, 'Pick 7','Lucky5 Pick 7',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,7, 'Pick 8','Lucky5 Pick 8',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,8, 'Straight A','Lucky5 Straight A',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,9, 'Box AB','Lucky5 Box AB',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,10,'Box ABC','Lucky5 Box ABC',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,11,'Straight AB','Lucky5 Straight AB',1);
insert into GP_RULE (HIS_RULE_CODE,HIS_MODIFY_DATE,GAME_CODE,RULE_CODE,RULE_NAME,RULE_DESC,RULE_ENABLE) values (0,sysdate,12,12,'Straight ABC','Lucky5 Straight ABC',1);

insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 1,'Pick 2','Lucky5 Pick 2');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 2,'Pick 3','Lucky5 Pick 3');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 3,'Pick 4','Lucky5 Pick 4');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 4,'Pick 5','Lucky5 Pick 5');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 5,'Pick 6','Lucky5 Pick 6');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 6,'Pick 7','Lucky5 Pick 7');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 7,'Pick 8','Lucky5 Pick 8');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 8,'Straight A','Lucky5 Straight A');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12, 9,'Box AB','Lucky5 Box AB');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12,10,'Box ABC','Lucky5 Box ABC');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12,11,'Straight AB','Lucky5 Straight AB');
insert into GP_WIN_RULE (HIS_WIN_CODE,HIS_MODIFY_DATE,GAME_CODE,WRULE_CODE,WRULE_NAME,WRULE_DESC) values (0,sysdate,12,12,'Straight ABC','Lucky5 Straight ABC');

insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 1,'Pick 2','Lucky5 Pick 2',4000  , 1);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 2,'Pick 3','Lucky5 Pick 3',12000 , 2);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 3,'Pick 4','Lucky5 Pick 4',48000 , 3);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 4,'Pick 5','Lucky5 Pick 5',336000, 4);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 5,'Pick 6','Lucky5 Pick 6',56000 , 5);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 6,'Pick 7','Lucky5 Pick 7',16000 , 6);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 7,'Pick 8','Lucky5 Pick 8',6000  , 7);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 8,'Straight A','Lucky5 Straight A',8000 , 8);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12, 9,'Box AB','Lucky5 Box AB',40000 , 9);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12,10,'Box ABC','Lucky5 Box ABC',120000,10);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12,11,'Straight AB','Lucky5 Straight AB',80000 ,11);
insert into GP_PRIZE_RULE (HIS_PRIZE_CODE,HIS_MODIFY_DATE,GAME_CODE,PRULE_LEVEL,PRULE_NAME,PRULE_DESC,LEVEL_PRIZE,DISP_ORDER) values (0,sysdate,12,12,'Straight ABC','Lucky5 Straight ABC',720000,12);

commit;

-- 奖池初始化
insert into iss_game_pool (game_code, pool_code, pool_amount_after, adj_time, pool_desc, pool_name) values (12, 0, 0, sysdate, 'Instant2 Prize Pool', 'Instant2 Prize Pool');
insert into iss_game_pool_his (his_code, game_code, issue_number, pool_code, change_amount, pool_amount_before, pool_amount_after, adj_time, pool_adj_type, adj_reason, pool_flow) values (F_GET_GAME_HIS_CODE_SEQ, 12, 0, 0, 0, 0, 0, sysdate, 7, 'Initialization', null);

-- 调节基金初始化
insert into adj_game_current (game_code, pool_amount_before, pool_amount_after) values (12, 0, 0);
insert into adj_game_his (his_code, game_code, issue_number, adj_change_type, adj_amount, adj_amount_before, adj_amount_after, adj_time) values (F_GET_GAME_HIS_CODE_SEQ, 12, 0, 8, 0, 0, 0, sysdate);

commit;

prompt 正在导入初始化数据 [INIT DATA -> 22-init_other_ts.sql ]......
-- 全国游戏授权
insert into AUTH_ORG (ORG_CODE,GAME_CODE,PAY_COMMISSION_RATE,SALE_COMMISSION_RATE,AUTH_TIME,ALLOW_PAY,ALLOW_SALE,ALLOW_CANCEL) values ('00',12,0,0,sysdate,1,1,1);


-- RNG Clients
insert into inf_devices
  (device_id, device_name, ip_addr, device_status, device_type, game_code)
values
  (1, 'RNG Device 1', '172.16.34.1', 0, 1, 12);
insert into inf_devices
  (device_id, device_name, ip_addr, device_status, device_type, game_code)
values
  (2, 'RNG Device 2', '172.16.34.2', 0, 1, 12);
commit;

-- MIS初始化一条日结记录，作为最初的内容
insert into his_day_settle (settle_id, opt_date, settle_date, sell_seq, cancel_seq, pay_seq, win_seq) values (0, to_date('2000-01-01','yyyy-mm-dd'), to_date('2000-01-01','yyyy-mm-dd'), 0, 0, 0, 0);
commit;

-- 票面欢迎语
insert into sys_ticket_memo (his_code, game_code, ticket_memo, set_admin, set_time) values (0, 0, 'Thanks for supporting!', 1, to_date('2010-01-01','yyyy-mm-dd'));
commit;

--终端类型
insert into inf_terminal_types (TERM_TYPE_ID,TERM_TYPE_DESC) values (1,'ST300');
insert into inf_terminal_types (TERM_TYPE_ID,TERM_TYPE_DESC) values (2,'GDS688-3');

--软件
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (1, 'sbin', 'System Environment',sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (2, 'comm', 'Communication Service', sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (3, 'gui', 'GUI', sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (4, 'tds', 'Terminal Display System', sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (5, 'driver', 'Device Drivers', sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (6, 'resources', 'Service Repositories', sysdate);
insert into UPG_SOFTWARE (soft_id, soft_name, soft_describe, create_date) values (7, 'upgrade', 'Upgrade Service', sysdate);

commit;

--软件版本
insert into upg_software_ver
select '1.0.00',soft_id,1,sysdate,soft_name||'Initial Version',0,'96e79218965eb72c92a549dd5a330113' from UPG_SOFTWARE;

commit;
