$axure.loadCurrentPage({
  "url":"站点服务.html",
  "generationDate":new Date(1444726798345.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5b91162ee59c48d382c693378acd2214",
    "type":"Axure:Page",
    "name":"站点服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62026d2c208b497ca77e8661f625b5e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":60},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b4e271d45d40a9b99e67a0130db888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":60},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"a5ffc207b4ed4401a54c26841b9e20e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":114,
              "y":106},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ddeea6d391046be968d842b10b427bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":114,
                  "y":106},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"50529a99467b4d609a097d9be858061c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfe7c4ac24974261847467b1e49b7040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"4e0433862e9f47f295119545faf8c460",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":111},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dc08bff570545b0808c35388b7fa68e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":111},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"a0cd9dafce19405e9dbfa474f702684a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08c515c170cc473f900e2a75356ac284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"32fb82e0f9ea4dea959c140f48881a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":343,
              "y":114},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55240d9a00534f078cefbe49f9632535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":343,
                  "y":114},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"961bf951d1dc45a1b55f25779f4241a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":114,
              "y":128},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee636f7423341ad8dcde5288d21066c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":114,
                  "y":128},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"0c4ea0b53b1f4113a33351e71dcb1cb0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":132},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48648ae78bfd4046924f945a609caebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":132},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"8056853d73f74f20a81a1d4e11d7b2e1",
          "label":"搜索框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":144,
              "y":202},
            "size":{
              "width":167,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入登录账号"},
{
          "id":"19197ffcc572456fa3c61c367cc11378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":176},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b8341afdd08438c9092122b128213c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":176},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4611b02f8194e0c939fe87e704a93ff",
          "label":"站点信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":119,
              "y":245},
            "size":{
              "width":267,
              "height":323},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"664aa4e0c0ff44abb92adb287fdacf5e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"757e96415545477c9738578519473b7b",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":0},
                    "size":{
                      "width":260,
                      "height":319},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84bca153383043bdbc488a0ef9b43640",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":4,
                          "y":0},
                        "size":{
                          "width":260,
                          "height":319},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/站点服务/u20.png"}},
{
                  "id":"8056fad902e544a1a9fee36110502ebc",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8354b09864e40189387e842b5be1817",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e7c339e8dab244c5a14e7c1cc226c72a",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":40},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"456c0f22d14d4ad5a4ed1e944a6fb61d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":40},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"794fbc76491a45b09ae50f9e39586f13",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":73},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e09e1ddf8b2f4fdeb60e7c58aa14817d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":73},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aa9e197ff7b5406abca6b8a9bcd1de5e",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":84,
                      "y":11},
                    "size":{
                      "width":86,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d4fbe3d685549e48b45307be29e16a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":84,
                          "y":11},
                        "size":{
                          "width":86,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"944fb057ecca4cf683996010629d8198",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":85,
                      "y":40},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c4fd2eb1d444d9a91e3f584f3d5ebdb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":85,
                          "y":40},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"09d0a5cc11c247eeac89647d8375880c",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":73},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f1f46c8410049158a4c9d0737a5de83",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":73},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"83a9b5b5809c4c16bf44e8bfddf88f4a",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":6,
                      "y":126},
                    "size":{
                      "width":79,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5afbc6ac6d54eba97930fd1224c2c59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":6,
                          "y":126},
                        "size":{
                          "width":79,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 交易流水",
                              "target":{
                                "targetType":"page",
                                "url":"交易流水.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u34.png"}},
{
                  "id":"17a91d01f5ec4138b3f2f5dfbfca41a6",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":185,
                      "y":126},
                    "size":{
                      "width":77,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fee34d57c8ba400094f4cf6b70447c7d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":185,
                          "y":126},
                        "size":{
                          "width":77,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 站点入库",
                              "target":{
                                "targetType":"page",
                                "url":"站点入库.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u36.png"}},
{
                  "id":"e1c8589d64474945bf27ff8fa349590a",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":8,
                      "y":176},
                    "size":{
                      "width":74,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f09982659b8e4403b6c5d523c9c1e6f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":8,
                          "y":176},
                        "size":{
                          "width":74,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 站点充值",
                              "target":{
                                "targetType":"page",
                                "url":"站点充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u38.png"}},
{
                  "id":"af5cb272244a42a1956e86c3926d81ae",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":183,
                      "y":176},
                    "size":{
                      "width":80,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6b2d57fb87994017b22c9da29d9f78f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":183,
                          "y":176},
                        "size":{
                          "width":80,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单管理",
                              "target":{
                                "targetType":"page",
                                "url":"订单管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u40.png"}},
{
                  "id":"7cb4c70bbe8746cab612a75a77c747e2",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":7,
                      "y":226},
                    "size":{
                      "width":76,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05e0ff2453c34300a659b401db578392",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":7,
                          "y":226},
                        "size":{
                          "width":76,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 提现申请",
                              "target":{
                                "targetType":"page",
                                "url":"提现申请.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u42.png"}},
{
                  "id":"41a7c5b253e94a0bb6c7c7f9850ad348",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":98,
                      "y":226},
                    "size":{
                      "width":75,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bad35eb631548c79950d31b15b788c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":98,
                          "y":226},
                        "size":{
                          "width":75,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 站点退货",
                              "target":{
                                "targetType":"page",
                                "url":"站点退货.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u44.png"}},
{
                  "id":"4a56b84ba45e4a4d931bf70c800c7aad",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":99,
                      "y":126},
                    "size":{
                      "width":75,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e522498d4b63465cbd64e1aa22527131",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":99,
                          "y":126},
                        "size":{
                          "width":75,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 资金日结",
                              "target":{
                                "targetType":"page",
                                "url":"资金日结.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u44.png"}},
{
                  "id":"8d3a48fdebda42af960135ec30ae00c7",
                  "label":"",
                  "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6600},
                    "location":{
                      "x":98,
                      "y":176},
                    "size":{
                      "width":75,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba896a113a4740ac92bfa8213612616e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a4611b02f8194e0c939fe87e704a93ff",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6600},
                        "location":{
                          "x":98,
                          "y":176},
                        "size":{
                          "width":75,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 兑奖页面",
                              "target":{
                                "targetType":"page",
                                "url":"兑奖页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/站点服务/u44.png"}}]}]},
{
          "id":"a57050c58383446ba11d818e74ced3e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":318,
              "y":209},
            "size":{
              "width":60,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66861ab01f8544dab3d233ecb067e11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":318,
                  "y":209},
                "size":{
                  "width":60,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 站点信息",
                      "objectsToFades":[{
                          "objectPath":["a4611b02f8194e0c939fe87e704a93ff"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/站点服务/u50.png"}},
{
          "id":"8ed11c029a994e57b3944791b755c353",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":131},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fd177503d38444989d537b13c7d5a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":131},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改登录密码/u27.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "62026d2c208b497ca77e8661f625b5e6":{
      "scriptId":"u0"},
    "15b4e271d45d40a9b99e67a0130db888":{
      "scriptId":"u1"},
    "a5ffc207b4ed4401a54c26841b9e20e1":{
      "scriptId":"u2"},
    "5ddeea6d391046be968d842b10b427bc":{
      "scriptId":"u3"},
    "50529a99467b4d609a097d9be858061c":{
      "scriptId":"u4"},
    "cfe7c4ac24974261847467b1e49b7040":{
      "scriptId":"u5"},
    "4e0433862e9f47f295119545faf8c460":{
      "scriptId":"u6"},
    "3dc08bff570545b0808c35388b7fa68e":{
      "scriptId":"u7"},
    "a0cd9dafce19405e9dbfa474f702684a":{
      "scriptId":"u8"},
    "08c515c170cc473f900e2a75356ac284":{
      "scriptId":"u9"},
    "32fb82e0f9ea4dea959c140f48881a46":{
      "scriptId":"u10"},
    "55240d9a00534f078cefbe49f9632535":{
      "scriptId":"u11"},
    "961bf951d1dc45a1b55f25779f4241a7":{
      "scriptId":"u12"},
    "7ee636f7423341ad8dcde5288d21066c":{
      "scriptId":"u13"},
    "0c4ea0b53b1f4113a33351e71dcb1cb0":{
      "scriptId":"u14"},
    "48648ae78bfd4046924f945a609caebf":{
      "scriptId":"u15"},
    "8056853d73f74f20a81a1d4e11d7b2e1":{
      "scriptId":"u16"},
    "19197ffcc572456fa3c61c367cc11378":{
      "scriptId":"u17"},
    "7b8341afdd08438c9092122b128213c7":{
      "scriptId":"u18"},
    "a4611b02f8194e0c939fe87e704a93ff":{
      "scriptId":"u19"},
    "757e96415545477c9738578519473b7b":{
      "scriptId":"u20"},
    "84bca153383043bdbc488a0ef9b43640":{
      "scriptId":"u21"},
    "8056fad902e544a1a9fee36110502ebc":{
      "scriptId":"u22"},
    "c8354b09864e40189387e842b5be1817":{
      "scriptId":"u23"},
    "e7c339e8dab244c5a14e7c1cc226c72a":{
      "scriptId":"u24"},
    "456c0f22d14d4ad5a4ed1e944a6fb61d":{
      "scriptId":"u25"},
    "794fbc76491a45b09ae50f9e39586f13":{
      "scriptId":"u26"},
    "e09e1ddf8b2f4fdeb60e7c58aa14817d":{
      "scriptId":"u27"},
    "aa9e197ff7b5406abca6b8a9bcd1de5e":{
      "scriptId":"u28"},
    "3d4fbe3d685549e48b45307be29e16a8":{
      "scriptId":"u29"},
    "944fb057ecca4cf683996010629d8198":{
      "scriptId":"u30"},
    "1c4fd2eb1d444d9a91e3f584f3d5ebdb":{
      "scriptId":"u31"},
    "09d0a5cc11c247eeac89647d8375880c":{
      "scriptId":"u32"},
    "9f1f46c8410049158a4c9d0737a5de83":{
      "scriptId":"u33"},
    "83a9b5b5809c4c16bf44e8bfddf88f4a":{
      "scriptId":"u34"},
    "d5afbc6ac6d54eba97930fd1224c2c59":{
      "scriptId":"u35"},
    "17a91d01f5ec4138b3f2f5dfbfca41a6":{
      "scriptId":"u36"},
    "fee34d57c8ba400094f4cf6b70447c7d":{
      "scriptId":"u37"},
    "e1c8589d64474945bf27ff8fa349590a":{
      "scriptId":"u38"},
    "f09982659b8e4403b6c5d523c9c1e6f5":{
      "scriptId":"u39"},
    "af5cb272244a42a1956e86c3926d81ae":{
      "scriptId":"u40"},
    "6b2d57fb87994017b22c9da29d9f78f5":{
      "scriptId":"u41"},
    "7cb4c70bbe8746cab612a75a77c747e2":{
      "scriptId":"u42"},
    "05e0ff2453c34300a659b401db578392":{
      "scriptId":"u43"},
    "41a7c5b253e94a0bb6c7c7f9850ad348":{
      "scriptId":"u44"},
    "5bad35eb631548c79950d31b15b788c2":{
      "scriptId":"u45"},
    "4a56b84ba45e4a4d931bf70c800c7aad":{
      "scriptId":"u46"},
    "e522498d4b63465cbd64e1aa22527131":{
      "scriptId":"u47"},
    "8d3a48fdebda42af960135ec30ae00c7":{
      "scriptId":"u48"},
    "ba896a113a4740ac92bfa8213612616e":{
      "scriptId":"u49"},
    "a57050c58383446ba11d818e74ced3e4":{
      "scriptId":"u50"},
    "66861ab01f8544dab3d233ecb067e11a":{
      "scriptId":"u51"},
    "8ed11c029a994e57b3944791b755c353":{
      "scriptId":"u52"},
    "8fd177503d38444989d537b13c7d5a69":{
      "scriptId":"u53"}}});