$axure.loadCurrentPage({
  "url":"账户余额查询_1.html",
  "generationDate":new Date(1443166057912.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"ea5d874e6ce04522b2d61bb5ce30012f",
    "type":"Axure:Page",
    "name":"账户余额查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2064a8fac8cb49e093668d4c4a59ae13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":520,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f451b283f1f44234adfb4e898c4f8094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"a28557d2a9c54672a52f122d2ab8c8e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":520,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca4c6eefbfe64424894beb5ee06330d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":520,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"f3e2dce0b8fe4208beed714756c0daad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":177},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c24f044bff4a9a828dcac61e6df440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":177},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300c2b2e838c4c948bd49bb73dedabf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":126},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dbd40ad21194f8f9a2bce42c2fb2f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":126},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad791e5112184bf8b0c8c084d014afc4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":405},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a9ab800a8dd64d5bb87c9fcde2b47701",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6366e3d1d4764382bbba53dbab0c6dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":126},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5c6db820c72482da7e56c8071cdd444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":126},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22f25d2d0f354bec89d97c8c22a9401c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":67},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e99dafc675e147bdab890b8e306686de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":67},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"455a0ffe041647f79207d7d7cee45f52",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":64},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"cac6733d062b4be7b7ac4baae36fbe02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":222},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"158a22df9b5a40ad90e1e235c4a25495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":222},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54a86b079e3642c0b19f9c3b4cda610a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":264},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13a8644129748bfbab62400b3286e12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":264},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2064a8fac8cb49e093668d4c4a59ae13":{
      "scriptId":"u0"},
    "f451b283f1f44234adfb4e898c4f8094":{
      "scriptId":"u1"},
    "a28557d2a9c54672a52f122d2ab8c8e1":{
      "scriptId":"u2"},
    "ca4c6eefbfe64424894beb5ee06330d9":{
      "scriptId":"u3"},
    "f3e2dce0b8fe4208beed714756c0daad":{
      "scriptId":"u4"},
    "51c24f044bff4a9a828dcac61e6df440":{
      "scriptId":"u5"},
    "300c2b2e838c4c948bd49bb73dedabf7":{
      "scriptId":"u6"},
    "2dbd40ad21194f8f9a2bce42c2fb2f14":{
      "scriptId":"u7"},
    "ad791e5112184bf8b0c8c084d014afc4":{
      "scriptId":"u8"},
    "a9ab800a8dd64d5bb87c9fcde2b47701":{
      "scriptId":"u9"},
    "6366e3d1d4764382bbba53dbab0c6dc4":{
      "scriptId":"u10"},
    "e5c6db820c72482da7e56c8071cdd444":{
      "scriptId":"u11"},
    "22f25d2d0f354bec89d97c8c22a9401c":{
      "scriptId":"u12"},
    "e99dafc675e147bdab890b8e306686de":{
      "scriptId":"u13"},
    "455a0ffe041647f79207d7d7cee45f52":{
      "scriptId":"u14"},
    "cac6733d062b4be7b7ac4baae36fbe02":{
      "scriptId":"u15"},
    "158a22df9b5a40ad90e1e235c4a25495":{
      "scriptId":"u16"},
    "54a86b079e3642c0b19f9c3b4cda610a":{
      "scriptId":"u17"},
    "b13a8644129748bfbab62400b3286e12":{
      "scriptId":"u18"}}});