$axure.loadCurrentPage({
  "url":"盘点报表_1.html",
  "generationDate":new Date(1443166051137.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"e0952664352740cd80294d52bbded0c9",
    "type":"Axure:Page",
    "name":"盘点报表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a5ee1f3d13864e9a81e121cce3ef22ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-1,
              "y":0},
            "size":{
              "width":1100,
              "height":603}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0391729de84415a5b5f859b279a93f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-1,
                  "y":0},
                "size":{
                  "width":1100,
                  "height":603}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点报表/u0.png"}},
{
          "id":"5ffbe69c39af4b37814c38c0ad027a1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":1100,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b17b366e381f46e992d218a6c2bfa75b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":1100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/盘点报表/u2.png"}},
{
          "id":"4570ad32bf97402e9998960f532d76d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":521,
              "y":50},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e34c5ecceba54ed6bce542f3de043b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":521,
                  "y":50},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09cf5c7dfd6748a5904056835e4404ae",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":1080,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531694986e1b495cad769520f6bd1c25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":124,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3611791841d7494b9154f9959a588ca2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":124,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u7.png"}},
{
              "id":"35ae773dd8314d19a8acd36ccb75ce41",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48ec292f8c7143f9a00464a6876bbc7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u21.png"}},
{
              "id":"1cf4f1fadc8e44e2870942705458faa8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98baa40bdf6c4fa8a0e5533e55eaae71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u21.png"}},
{
              "id":"3c1aa0e68e3e4aeba5435be0aab7926a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":0},
                "size":{
                  "width":153,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3adaf4724434fc597f967ee48e990b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u9.png"}},
{
              "id":"3eae3a342c4c4e53b61c846f914d6eb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":36},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d98d251d019f42ea83fa9233157ee97b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":36},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"478fc8c51ba64b09a4e0e2f71e85bd59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":66},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52ec5fd1ec4e4493a91f248bc96137b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":66},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"71c29eaa59b7445cac1509a8b8d6e57d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":277,
                  "y":0},
                "size":{
                  "width":153,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49bf993dd0c0413895436605b022a9a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":277,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u9.png"}},
{
              "id":"f7d7ad3189374089bb679299814c3d87",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":277,
                  "y":36},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e976347d50174ea5b5d56b85638ec9eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":277,
                      "y":36},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"10c592449b474e3297b5a23d63dad7cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":277,
                  "y":66},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f48af68d5a43465ca838d1bb492522fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":277,
                      "y":66},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"512d5fbaecf14ba3a2b9449edcbb5473",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":581,
                  "y":0},
                "size":{
                  "width":161,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f66b78680914386917f1d96f351ccd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":581,
                      "y":0},
                    "size":{
                      "width":161,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u15.png"}},
{
              "id":"5c081d000374461885fa6a30e353ae29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":581,
                  "y":36},
                "size":{
                  "width":161,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c0a8e043b7c48af9e53096a975ae4ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":581,
                      "y":36},
                    "size":{
                      "width":161,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/批次入库单/u13.png"}},
{
              "id":"c61b492fc4f849b9b4de985a9e234e84",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":581,
                  "y":66},
                "size":{
                  "width":161,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb40f69994854cd4a4e24ba2a462cb09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":581,
                      "y":66},
                    "size":{
                      "width":161,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/批次入库单/u13.png"}},
{
              "id":"22ee33632ac84b97b84fd308101e1038",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":0},
                "size":{
                  "width":168,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a814c3dd370c4a9d9a131557b9df182a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":0},
                    "size":{
                      "width":168,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u17.png"}},
{
              "id":"1884a877e906427bbcfc63b5f3ee86ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":36},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6f4948c204a4ec79514e5419516a9a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":36},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u31.png"}},
{
              "id":"979ab4ded37b4532ac42e3994924d78e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":66},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1bb0095eb264d68aca9466edde28b40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":66},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u31.png"}},
{
              "id":"31ffb20876d544c4a8142b1396e74330",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74c37917aac14fe6be107196c2b079c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u21.png"}},
{
              "id":"82f9cb52460b47be95673b3c8563f742",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":96},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92997710b7514186ba6a1cb8f472def6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":96},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"3bb7f0f4072c497c936070b527a0f45d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":277,
                  "y":96},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0b002ad4b574d33be8bfa18138e010e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":277,
                      "y":96},
                    "size":{
                      "width":153,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u23.png"}},
{
              "id":"2341631cef6c48c19e2cba12c4e96f01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":581,
                  "y":96},
                "size":{
                  "width":161,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"734acdb5dea64b66b3c8afb29e647fba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":581,
                      "y":96},
                    "size":{
                      "width":161,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/批次入库单/u13.png"}},
{
              "id":"37046d8939be4dec884b2c7aa6c29533",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":96},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d064abca0ef8461292f4612612675a41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":96},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u31.png"}},
{
              "id":"d929adc613d647acab1b921a0a509fda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":126},
                "size":{
                  "width":124,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d67a3253c45c43a3bb85ca5f50cc3b54",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":126},
                    "size":{
                      "width":124,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u63.png"}},
{
              "id":"0a6455c63075454a86ca16e0e455f31a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":124,
                  "y":126},
                "size":{
                  "width":153,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3824f7d2fdeb4b05b7b65ed98400553a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":124,
                      "y":126},
                    "size":{
                      "width":153,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u65.png"}},
{
              "id":"e5442996581643deac6c5cb3342da92d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":277,
                  "y":126},
                "size":{
                  "width":153,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eab57166f7674895b05299abeb205c4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":277,
                      "y":126},
                    "size":{
                      "width":153,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u65.png"}},
{
              "id":"b1acf2424e2246c390de34634c432916",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":581,
                  "y":126},
                "size":{
                  "width":161,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2059c5d00e35457db60b51b07d7fd4b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":581,
                      "y":126},
                    "size":{
                      "width":161,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u71.png"}},
{
              "id":"b35595d736b443cb9d5ad25ccc4564d7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":742,
                  "y":126},
                "size":{
                  "width":168,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25e3ee08c982459d8d6dc9455d47d3d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":742,
                      "y":126},
                    "size":{
                      "width":168,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u73.png"}},
{
              "id":"fa834e9a121943c98af2f73d2e9e1e7a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":0},
                "size":{
                  "width":151,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c2b0ec9ca4b4ba6a8afb3912fa4ebf9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":0},
                    "size":{
                      "width":151,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u13.png"}},
{
              "id":"855bf86e94424c518cf19d99218220f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":36},
                "size":{
                  "width":151,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6a3a767beaa48148263b7cfd85f693f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":36},
                    "size":{
                      "width":151,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u27.png"}},
{
              "id":"7e89b70fac8d457582db3333e434fdfd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":66},
                "size":{
                  "width":151,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d203250383b54af3a217eafa0919b4f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":66},
                    "size":{
                      "width":151,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u27.png"}},
{
              "id":"a13898334fb44d8c88b0d01b539b6b49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":96},
                "size":{
                  "width":151,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7ed3f0497414dd485968687da934e4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":96},
                    "size":{
                      "width":151,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u27.png"}},
{
              "id":"ae2cb727c72149c6b6f86368d59791f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":430,
                  "y":126},
                "size":{
                  "width":151,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"426b23ab82fb4329aba3ea2dc9699ec2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":430,
                      "y":126},
                    "size":{
                      "width":151,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u69.png"}},
{
              "id":"3405de3015724ff48b1f606c06a8be10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":910,
                  "y":0},
                "size":{
                  "width":170,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb54adbf9154435fb620cd28d0340ad1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":910,
                      "y":0},
                    "size":{
                      "width":170,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u19.png"}},
{
              "id":"14735843544f46c39fe20b84c62e1e6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":910,
                  "y":36},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9ef0ff33cba4b8ebd120515b1858dae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":910,
                      "y":36},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u33.png"}},
{
              "id":"e3c63252a4974f2280bc2fa20ccf2998",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":910,
                  "y":66},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5531637c19bc44938703e4f103a3a5b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":910,
                      "y":66},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u33.png"}},
{
              "id":"5b4cf7a1605a4e98bdac097394c95bc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":910,
                  "y":96},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97f7c2a4b5f8485dafd77b9e73852848",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":910,
                      "y":96},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u33.png"}},
{
              "id":"16be036268df4807aae16e6123ecd201",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":910,
                  "y":126},
                "size":{
                  "width":170,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5583cdfa2ba04367a25f8d7b0f8d356e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":910,
                      "y":126},
                    "size":{
                      "width":170,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/盘点报表_1/u75.png"}}]},
{
          "id":"3d15ebfc2edc4d22af47241758551113",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":126},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ea28e25be4d4b578846e86022d5d2cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":126},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"539d0863ef644fa387fc85c24376495d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":907,
              "y":126},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db56928fc9c24cff8dee83c0a50447ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":907,
                  "y":126},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c07f75b775d840beb6acd5b2a766e9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":334},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2184a925915148338f6ed820efed6997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":334},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b2e756cc0e8441c9fca2da886daf1b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":334},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"010515ed534147a1aaa87f8ef32c7698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":334},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"583c62a846924a96af9887e95d3b3c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":374},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f2f341474b48bb80cee0f2f2a97315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":374},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a5ee1f3d13864e9a81e121cce3ef22ae":{
      "scriptId":"u0"},
    "9f0391729de84415a5b5f859b279a93f":{
      "scriptId":"u1"},
    "5ffbe69c39af4b37814c38c0ad027a1f":{
      "scriptId":"u2"},
    "b17b366e381f46e992d218a6c2bfa75b":{
      "scriptId":"u3"},
    "4570ad32bf97402e9998960f532d76d1":{
      "scriptId":"u4"},
    "e34c5ecceba54ed6bce542f3de043b0f":{
      "scriptId":"u5"},
    "09cf5c7dfd6748a5904056835e4404ae":{
      "scriptId":"u6"},
    "531694986e1b495cad769520f6bd1c25":{
      "scriptId":"u7"},
    "3611791841d7494b9154f9959a588ca2":{
      "scriptId":"u8"},
    "3c1aa0e68e3e4aeba5435be0aab7926a":{
      "scriptId":"u9"},
    "e3adaf4724434fc597f967ee48e990b1":{
      "scriptId":"u10"},
    "71c29eaa59b7445cac1509a8b8d6e57d":{
      "scriptId":"u11"},
    "49bf993dd0c0413895436605b022a9a8":{
      "scriptId":"u12"},
    "fa834e9a121943c98af2f73d2e9e1e7a":{
      "scriptId":"u13"},
    "0c2b0ec9ca4b4ba6a8afb3912fa4ebf9":{
      "scriptId":"u14"},
    "512d5fbaecf14ba3a2b9449edcbb5473":{
      "scriptId":"u15"},
    "3f66b78680914386917f1d96f351ccd1":{
      "scriptId":"u16"},
    "22ee33632ac84b97b84fd308101e1038":{
      "scriptId":"u17"},
    "a814c3dd370c4a9d9a131557b9df182a":{
      "scriptId":"u18"},
    "3405de3015724ff48b1f606c06a8be10":{
      "scriptId":"u19"},
    "cb54adbf9154435fb620cd28d0340ad1":{
      "scriptId":"u20"},
    "35ae773dd8314d19a8acd36ccb75ce41":{
      "scriptId":"u21"},
    "48ec292f8c7143f9a00464a6876bbc7b":{
      "scriptId":"u22"},
    "3eae3a342c4c4e53b61c846f914d6eb1":{
      "scriptId":"u23"},
    "d98d251d019f42ea83fa9233157ee97b":{
      "scriptId":"u24"},
    "f7d7ad3189374089bb679299814c3d87":{
      "scriptId":"u25"},
    "e976347d50174ea5b5d56b85638ec9eb":{
      "scriptId":"u26"},
    "855bf86e94424c518cf19d99218220f7":{
      "scriptId":"u27"},
    "e6a3a767beaa48148263b7cfd85f693f":{
      "scriptId":"u28"},
    "5c081d000374461885fa6a30e353ae29":{
      "scriptId":"u29"},
    "0c0a8e043b7c48af9e53096a975ae4ad":{
      "scriptId":"u30"},
    "1884a877e906427bbcfc63b5f3ee86ef":{
      "scriptId":"u31"},
    "c6f4948c204a4ec79514e5419516a9a3":{
      "scriptId":"u32"},
    "14735843544f46c39fe20b84c62e1e6a":{
      "scriptId":"u33"},
    "b9ef0ff33cba4b8ebd120515b1858dae":{
      "scriptId":"u34"},
    "1cf4f1fadc8e44e2870942705458faa8":{
      "scriptId":"u35"},
    "98baa40bdf6c4fa8a0e5533e55eaae71":{
      "scriptId":"u36"},
    "478fc8c51ba64b09a4e0e2f71e85bd59":{
      "scriptId":"u37"},
    "52ec5fd1ec4e4493a91f248bc96137b5":{
      "scriptId":"u38"},
    "10c592449b474e3297b5a23d63dad7cc":{
      "scriptId":"u39"},
    "f48af68d5a43465ca838d1bb492522fa":{
      "scriptId":"u40"},
    "7e89b70fac8d457582db3333e434fdfd":{
      "scriptId":"u41"},
    "d203250383b54af3a217eafa0919b4f2":{
      "scriptId":"u42"},
    "c61b492fc4f849b9b4de985a9e234e84":{
      "scriptId":"u43"},
    "fb40f69994854cd4a4e24ba2a462cb09":{
      "scriptId":"u44"},
    "979ab4ded37b4532ac42e3994924d78e":{
      "scriptId":"u45"},
    "e1bb0095eb264d68aca9466edde28b40":{
      "scriptId":"u46"},
    "e3c63252a4974f2280bc2fa20ccf2998":{
      "scriptId":"u47"},
    "5531637c19bc44938703e4f103a3a5b8":{
      "scriptId":"u48"},
    "31ffb20876d544c4a8142b1396e74330":{
      "scriptId":"u49"},
    "74c37917aac14fe6be107196c2b079c8":{
      "scriptId":"u50"},
    "82f9cb52460b47be95673b3c8563f742":{
      "scriptId":"u51"},
    "92997710b7514186ba6a1cb8f472def6":{
      "scriptId":"u52"},
    "3bb7f0f4072c497c936070b527a0f45d":{
      "scriptId":"u53"},
    "b0b002ad4b574d33be8bfa18138e010e":{
      "scriptId":"u54"},
    "a13898334fb44d8c88b0d01b539b6b49":{
      "scriptId":"u55"},
    "d7ed3f0497414dd485968687da934e4a":{
      "scriptId":"u56"},
    "2341631cef6c48c19e2cba12c4e96f01":{
      "scriptId":"u57"},
    "734acdb5dea64b66b3c8afb29e647fba":{
      "scriptId":"u58"},
    "37046d8939be4dec884b2c7aa6c29533":{
      "scriptId":"u59"},
    "d064abca0ef8461292f4612612675a41":{
      "scriptId":"u60"},
    "5b4cf7a1605a4e98bdac097394c95bc5":{
      "scriptId":"u61"},
    "97f7c2a4b5f8485dafd77b9e73852848":{
      "scriptId":"u62"},
    "d929adc613d647acab1b921a0a509fda":{
      "scriptId":"u63"},
    "d67a3253c45c43a3bb85ca5f50cc3b54":{
      "scriptId":"u64"},
    "0a6455c63075454a86ca16e0e455f31a":{
      "scriptId":"u65"},
    "3824f7d2fdeb4b05b7b65ed98400553a":{
      "scriptId":"u66"},
    "e5442996581643deac6c5cb3342da92d":{
      "scriptId":"u67"},
    "eab57166f7674895b05299abeb205c4b":{
      "scriptId":"u68"},
    "ae2cb727c72149c6b6f86368d59791f8":{
      "scriptId":"u69"},
    "426b23ab82fb4329aba3ea2dc9699ec2":{
      "scriptId":"u70"},
    "b1acf2424e2246c390de34634c432916":{
      "scriptId":"u71"},
    "2059c5d00e35457db60b51b07d7fd4b9":{
      "scriptId":"u72"},
    "b35595d736b443cb9d5ad25ccc4564d7":{
      "scriptId":"u73"},
    "25e3ee08c982459d8d6dc9455d47d3d4":{
      "scriptId":"u74"},
    "16be036268df4807aae16e6123ecd201":{
      "scriptId":"u75"},
    "5583cdfa2ba04367a25f8d7b0f8d356e":{
      "scriptId":"u76"},
    "3d15ebfc2edc4d22af47241758551113":{
      "scriptId":"u77"},
    "9ea28e25be4d4b578846e86022d5d2cf":{
      "scriptId":"u78"},
    "539d0863ef644fa387fc85c24376495d":{
      "scriptId":"u79"},
    "db56928fc9c24cff8dee83c0a50447ca":{
      "scriptId":"u80"},
    "c07f75b775d840beb6acd5b2a766e9b7":{
      "scriptId":"u81"},
    "2184a925915148338f6ed820efed6997":{
      "scriptId":"u82"},
    "8b2e756cc0e8441c9fca2da886daf1b9":{
      "scriptId":"u83"},
    "010515ed534147a1aaa87f8ef32c7698":{
      "scriptId":"u84"},
    "583c62a846924a96af9887e95d3b3c66":{
      "scriptId":"u85"},
    "70f2f341474b48bb80cee0f2f2a97315":{
      "scriptId":"u86"}}});