$axure.loadCurrentPage({
  "url":"出货单出库.html",
  "generationDate":new Date(1443166049965.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"37a86ca640ef40dea0fbabe318df8954",
    "type":"Axure:Page",
    "name":"出货单出库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14fa434f993840d2abc3aea18c4a06dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-3},
            "size":{
              "width":880,
              "height":663}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479469099cc241d5bc3cbeeeddefbed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-3},
                "size":{
                  "width":880,
                  "height":663}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调拨出库/u0.png"}},
{
          "id":"42db16b1e6964f8ab9669790922a30a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":880,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de477e60a104f51be67e3c78fb0183b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":880,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调拨出库/u2.png"}},
{
          "id":"6710451a9fc547bdab8c1d0d20f3a5c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":386,
              "y":40},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11450f8363b3405eb0fdd116b6a41987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":386,
                  "y":40},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04830f84b8cf49ea890581a7c02188af",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":613},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"799c9f1735a44722bb5aa4b19f1a5147",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":290},
            "size":{
              "width":660,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db70457076fa499893878490e9d1803e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":290},
                "size":{
                  "width":660,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调拨出库/u7.png"}},
{
          "id":"2c0d6e8812dd4655871c5a6196353dbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":306},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b018522397964683b109631d0e4c7184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":306},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0b2f04f19624a2994b5beab38ac9220",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":306},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b85ddbbe4ac4c4eaad29ffa4ff077da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":306},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e061e3683694af9911126a4bac6bf05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":306},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ee5f8b5c9194ad18d93e74a20afc339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":306},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a988e64a623c47ee9a259c065e2540d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":348},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d14c13cdf0d4879a6655daf0666cdba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":348},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8d5a9fd7520491cbd88a18b66970cec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":348},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e8d834979842b3833dbff3a236af09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":348},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bf6815c76b940fbba2713c843d01c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":390},
            "size":{
              "width":659,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c3a6fc246f7462485478ee5514f90e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":390},
                "size":{
                  "width":659,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调拨出库/u19.png"}},
{
          "id":"0709a9fdb3f84ea3aae69f5367645fd6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":626,
              "y":431},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30366e51a84b42e395cc6ffbc724dc10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":626,
                  "y":431},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"a749fe6fda3745abb04541a64072d292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":626,
              "y":459},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe0be26930dc4e70bce5f76e628e936b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":626,
                  "y":459},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"d4530022cc9849948f94df0805839a6c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":613},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"0585021f9361423c8faa8c9f0665d35c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":558},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 出库信息",
                      "objectsToFades":[{
                          "objectPath":["b418affb5ff74005beae50182e211905"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"02bc63a0306e4ef390bd33ac337a5229",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":160},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82e0c97b9df40fb836507d5495676db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":160},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5006a9914fa4f8abba8a5a96aed0b0d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":188,
              "y":160},
            "size":{
              "width":338,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f2a20f6f644bd7944a4bc83b9ce8c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC},
                "size":{
                  "width":112,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12dfe1438d4943809f2e2dd9bfed6c6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC},
                    "size":{
                      "width":112,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/出货单出库/u30.png"}},
{
              "id":"325e0adca763446fbc447464040ad600",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":22},
                "size":{
                  "width":112,
                  "height":21}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa74e817032d4498add466c3f29219e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":22},
                    "size":{
                      "width":112,
                      "height":21}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u40.png"}},
{
              "id":"8b168d4f2b04470fb7e881f2a9f3988e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":43},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ea170501e8f4bcb9aae63d44631a42f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":112,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u46.png"}},
{
              "id":"f56a9e4693f7476394ffd66acc2ca445",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC},
                "location":{
                  "x":112,
                  "y":0},
                "size":{
                  "width":112,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afb8831c571d4e149a93768a877ade80",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC},
                    "location":{
                      "x":112,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/出货单出库/u30.png"}},
{
              "id":"25eec261e665413d890e0db14a10c42d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":112,
                  "y":22},
                "size":{
                  "width":112,
                  "height":21}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fa26590d2d74b9194888081288ec1df",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":112,
                      "y":22},
                    "size":{
                      "width":112,
                      "height":21}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u40.png"}},
{
              "id":"31cda45e295d49d9a4db0287147ff5d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":112,
                  "y":43},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61e1900affe24485908e94d5dd22cb94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":112,
                      "y":43},
                    "size":{
                      "width":112,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u46.png"}},
{
              "id":"09bbc8e89ed64331820c709f4fa48106",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC},
                "location":{
                  "x":224,
                  "y":0},
                "size":{
                  "width":114,
                  "height":22}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"27422cc2d3ab415c93f99f186a9a6d36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC},
                    "location":{
                      "x":224,
                      "y":0},
                    "size":{
                      "width":114,
                      "height":22}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/出货单出库/u34.png"}},
{
              "id":"61fd98887a9a42a6bd452e25248b0cd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":22},
                "size":{
                  "width":114,
                  "height":21}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e00c8b7da8b14ab0b85dffb3b0be62f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":22},
                    "size":{
                      "width":114,
                      "height":21}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u44.png"}},
{
              "id":"51dc164f31ad464d8ffd326f0116ecb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":43},
                "size":{
                  "width":114,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0820f9e4377340d39e97daadef2294a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":43},
                    "size":{
                      "width":114,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u50.png"}},
{
              "id":"b25df2edb1404f25934990794cc3355b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":63},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34157445b6844fb3b65ea3f54e885bdb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":63},
                    "size":{
                      "width":112,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u52.png"}},
{
              "id":"125ee936857b4d31bda72f9ba3a425f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":112,
                  "y":63},
                "size":{
                  "width":112,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8cf4669b98e44b39cc985eafc744736",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":112,
                      "y":63},
                    "size":{
                      "width":112,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u52.png"}},
{
              "id":"1d3d6493eb814f49a30ea9dc32c9542c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":224,
                  "y":63},
                "size":{
                  "width":114,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7bae73f7ddd1493e8e59e8259c046373",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":224,
                      "y":63},
                    "size":{
                      "width":114,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/调拨出库/u56.png"}}]},
{
          "id":"57044918caaa45e09d26418a44bb1ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":254},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17626ddbe1ce4c468517d7976ed041a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":254},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22204cc01cc84ca6a09fef49e7fadd4f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":254},
            "size":{
              "width":250,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b418affb5ff74005beae50182e211905",
          "label":"出库信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":390},
            "size":{
              "width":659,
              "height":214},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7b4b95db849845749c12848235f1158c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2f38887350ce48dc801cbadb55043851",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-30,
                      "y":-10},
                    "size":{
                      "width":690,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ad95cc013af49b990bf8508cba57cad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-30,
                          "y":-10},
                        "size":{
                          "width":690,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/调拨出库/u102.png"}},
{
                  "id":"3ce136b729244d8a8882876beb60f23d",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":332,
                      "y":40},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f018c7c2f4545639d753913dc0a697b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":332,
                          "y":40},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"403fac2e43284975a7bf8553bad8dccc",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":40},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c312b184d9a422da8f18cff8d07aca2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":102,
                          "y":40},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d01d59b8de7f48bd94607f31660872f4",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":73},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd720c8663d44fe68f348fc455559918",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":102,
                          "y":73},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"29f982ddbff94a3facafcf9b501e4977",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":332,
                      "y":73},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f28266249f2f403387fe7fc95422dc18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":332,
                          "y":73},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2727bc6b85e04927bb6c00fdf571aa7a",
                  "label":"",
                  "parentDynamicPanel":"b418affb5ff74005beae50182e211905",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":583,
                      "y":176},
                    "size":{
                      "width":55,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 出库信息",
                              "objectsToFades":[{
                                  "objectPath":["b418affb5ff74005beae50182e211905"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"0b4ab825424d45189860a07cd23ee11f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":138,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8861f458827447dbac5d8abe7e1dd9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c8898d5500c491dadc168a9a7dd9738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":209,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63cccb4553443d9804cb5a89457f786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e48dc2e826a43debaad9082e468b4d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":289,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63735884c14c4b29961f6f4681ff8f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":289,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d97225f58fb4ee1acc294a155e5bbab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":359,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6245739bf27a46668f16358f1148cdc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":359,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7d1633800a146a48ee96c45d5cac01f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":445,
              "y":404},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f8f5e1b4c3c4ce8984a8af81b4d181f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":404},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"315cf16ec46e4c4c854bee9073cb34b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":490,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef80798f5644b6a91363dd07de14ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18756289947e44f2b378eec8676ff049",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":569,
              "y":404},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4371dda9b02e409e8abb01d75c00c165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":569,
                  "y":404},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3074fca652ab46969de3b4d152af4527",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":94},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be445b6ccb9d40f8963cd398933ca54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":94},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "14fa434f993840d2abc3aea18c4a06dd":{
      "scriptId":"u0"},
    "479469099cc241d5bc3cbeeeddefbed9":{
      "scriptId":"u1"},
    "42db16b1e6964f8ab9669790922a30a6":{
      "scriptId":"u2"},
    "8de477e60a104f51be67e3c78fb0183b":{
      "scriptId":"u3"},
    "6710451a9fc547bdab8c1d0d20f3a5c3":{
      "scriptId":"u4"},
    "11450f8363b3405eb0fdd116b6a41987":{
      "scriptId":"u5"},
    "04830f84b8cf49ea890581a7c02188af":{
      "scriptId":"u6"},
    "799c9f1735a44722bb5aa4b19f1a5147":{
      "scriptId":"u7"},
    "db70457076fa499893878490e9d1803e":{
      "scriptId":"u8"},
    "2c0d6e8812dd4655871c5a6196353dbb":{
      "scriptId":"u9"},
    "b018522397964683b109631d0e4c7184":{
      "scriptId":"u10"},
    "e0b2f04f19624a2994b5beab38ac9220":{
      "scriptId":"u11"},
    "0b85ddbbe4ac4c4eaad29ffa4ff077da":{
      "scriptId":"u12"},
    "9e061e3683694af9911126a4bac6bf05":{
      "scriptId":"u13"},
    "2ee5f8b5c9194ad18d93e74a20afc339":{
      "scriptId":"u14"},
    "a988e64a623c47ee9a259c065e2540d6":{
      "scriptId":"u15"},
    "7d14c13cdf0d4879a6655daf0666cdba":{
      "scriptId":"u16"},
    "a8d5a9fd7520491cbd88a18b66970cec":{
      "scriptId":"u17"},
    "54e8d834979842b3833dbff3a236af09":{
      "scriptId":"u18"},
    "5bf6815c76b940fbba2713c843d01c19":{
      "scriptId":"u19"},
    "2c3a6fc246f7462485478ee5514f90e4":{
      "scriptId":"u20"},
    "0709a9fdb3f84ea3aae69f5367645fd6":{
      "scriptId":"u21"},
    "30366e51a84b42e395cc6ffbc724dc10":{
      "scriptId":"u22"},
    "a749fe6fda3745abb04541a64072d292":{
      "scriptId":"u23"},
    "fe0be26930dc4e70bce5f76e628e936b":{
      "scriptId":"u24"},
    "d4530022cc9849948f94df0805839a6c":{
      "scriptId":"u25"},
    "0585021f9361423c8faa8c9f0665d35c":{
      "scriptId":"u26"},
    "02bc63a0306e4ef390bd33ac337a5229":{
      "scriptId":"u27"},
    "e82e0c97b9df40fb836507d5495676db":{
      "scriptId":"u28"},
    "f5006a9914fa4f8abba8a5a96aed0b0d":{
      "scriptId":"u29"},
    "07f2a20f6f644bd7944a4bc83b9ce8c5":{
      "scriptId":"u30"},
    "12dfe1438d4943809f2e2dd9bfed6c6b":{
      "scriptId":"u31"},
    "f56a9e4693f7476394ffd66acc2ca445":{
      "scriptId":"u32"},
    "afb8831c571d4e149a93768a877ade80":{
      "scriptId":"u33"},
    "09bbc8e89ed64331820c709f4fa48106":{
      "scriptId":"u34"},
    "27422cc2d3ab415c93f99f186a9a6d36":{
      "scriptId":"u35"},
    "325e0adca763446fbc447464040ad600":{
      "scriptId":"u36"},
    "fa74e817032d4498add466c3f29219e5":{
      "scriptId":"u37"},
    "25eec261e665413d890e0db14a10c42d":{
      "scriptId":"u38"},
    "4fa26590d2d74b9194888081288ec1df":{
      "scriptId":"u39"},
    "61fd98887a9a42a6bd452e25248b0cd5":{
      "scriptId":"u40"},
    "e00c8b7da8b14ab0b85dffb3b0be62f3":{
      "scriptId":"u41"},
    "8b168d4f2b04470fb7e881f2a9f3988e":{
      "scriptId":"u42"},
    "4ea170501e8f4bcb9aae63d44631a42f":{
      "scriptId":"u43"},
    "31cda45e295d49d9a4db0287147ff5d1":{
      "scriptId":"u44"},
    "61e1900affe24485908e94d5dd22cb94":{
      "scriptId":"u45"},
    "51dc164f31ad464d8ffd326f0116ecb2":{
      "scriptId":"u46"},
    "0820f9e4377340d39e97daadef2294a3":{
      "scriptId":"u47"},
    "b25df2edb1404f25934990794cc3355b":{
      "scriptId":"u48"},
    "34157445b6844fb3b65ea3f54e885bdb":{
      "scriptId":"u49"},
    "125ee936857b4d31bda72f9ba3a425f1":{
      "scriptId":"u50"},
    "b8cf4669b98e44b39cc985eafc744736":{
      "scriptId":"u51"},
    "1d3d6493eb814f49a30ea9dc32c9542c":{
      "scriptId":"u52"},
    "7bae73f7ddd1493e8e59e8259c046373":{
      "scriptId":"u53"},
    "57044918caaa45e09d26418a44bb1ce6":{
      "scriptId":"u54"},
    "17626ddbe1ce4c468517d7976ed041a5":{
      "scriptId":"u55"},
    "22204cc01cc84ca6a09fef49e7fadd4f":{
      "scriptId":"u56"},
    "b418affb5ff74005beae50182e211905":{
      "scriptId":"u57"},
    "2f38887350ce48dc801cbadb55043851":{
      "scriptId":"u58"},
    "9ad95cc013af49b990bf8508cba57cad":{
      "scriptId":"u59"},
    "3ce136b729244d8a8882876beb60f23d":{
      "scriptId":"u60"},
    "0f018c7c2f4545639d753913dc0a697b":{
      "scriptId":"u61"},
    "403fac2e43284975a7bf8553bad8dccc":{
      "scriptId":"u62"},
    "6c312b184d9a422da8f18cff8d07aca2":{
      "scriptId":"u63"},
    "d01d59b8de7f48bd94607f31660872f4":{
      "scriptId":"u64"},
    "fd720c8663d44fe68f348fc455559918":{
      "scriptId":"u65"},
    "29f982ddbff94a3facafcf9b501e4977":{
      "scriptId":"u66"},
    "f28266249f2f403387fe7fc95422dc18":{
      "scriptId":"u67"},
    "2727bc6b85e04927bb6c00fdf571aa7a":{
      "scriptId":"u68"},
    "0b4ab825424d45189860a07cd23ee11f":{
      "scriptId":"u69"},
    "c8861f458827447dbac5d8abe7e1dd9f":{
      "scriptId":"u70"},
    "0c8898d5500c491dadc168a9a7dd9738":{
      "scriptId":"u71"},
    "e63cccb4553443d9804cb5a89457f786":{
      "scriptId":"u72"},
    "2e48dc2e826a43debaad9082e468b4d2":{
      "scriptId":"u73"},
    "63735884c14c4b29961f6f4681ff8f9d":{
      "scriptId":"u74"},
    "0d97225f58fb4ee1acc294a155e5bbab":{
      "scriptId":"u75"},
    "6245739bf27a46668f16358f1148cdc5":{
      "scriptId":"u76"},
    "d7d1633800a146a48ee96c45d5cac01f":{
      "scriptId":"u77"},
    "0f8f5e1b4c3c4ce8984a8af81b4d181f":{
      "scriptId":"u78"},
    "315cf16ec46e4c4c854bee9073cb34b5":{
      "scriptId":"u79"},
    "2ef80798f5644b6a91363dd07de14ed9":{
      "scriptId":"u80"},
    "18756289947e44f2b378eec8676ff049":{
      "scriptId":"u81"},
    "4371dda9b02e409e8abb01d75c00c165":{
      "scriptId":"u82"},
    "3074fca652ab46969de3b4d152af4527":{
      "scriptId":"u83"},
    "be445b6ccb9d40f8963cd398933ca54e":{
      "scriptId":"u84"}}});