$axure.loadCurrentPage({
  "url":"批次入库.html",
  "generationDate":new Date(1443166048239.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"9350ee5e796e48179e60314a986fe69b",
    "type":"Axure:Page",
    "name":"批次入库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5435d4c3cd2f44878b83f5f1e84dcf74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-3},
            "size":{
              "width":960,
              "height":670}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ba4916503e4fdcb70a4c0278564cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-3},
                "size":{
                  "width":960,
                  "height":670}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u80.png"}},
{
          "id":"b93235594c3343b58b59bf5b66efe48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":960,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a0c2f90f1a4401a8b83a207219a013b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":960,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u87.png"}},
{
          "id":"90013a58d92c48d793dfdb69a3f85c6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":435,
              "y":40},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c36fc71f05b74799b5fdd1c99105406d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":435,
                  "y":40},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18ba8d52583749508ab58430420b5596",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":123},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"515d3ea59c8241f08f6132521daf825b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":123},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a34b6df4ef2441e7a747ce19bcf3112c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":123},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe7ed0f61ea34734b7c73c8fca3f7e54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":382,
                  "y":123},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a400187c04cf403c8665986b9dc15baf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":120},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c06ec80d05024cd487f3bd84b256b97c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":120},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"79ab6459ec3341bcb74a56953d1a6352",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":180},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0374e4fb287e475c81c326d6ff736ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":180},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3b120e1db9044b4affc3b3cb6b4c597",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":170},
            "size":{
              "width":309,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"db6fd7b964b84f52a5df670b43a4ea1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":221},
            "size":{
              "width":720,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"896bea728d1e4beb8e53be00d4e0f950",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":221},
                "size":{
                  "width":720,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u105.png"}},
{
          "id":"a3f65602dc0049e0a204741da7f9716d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b0873658b3490f97cc76ace51c0122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a4e178f4ddc48079352929412441bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75aef486620349d9a9e22ad7657aaf0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b467168ab34ddc94098a0aa150dddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fd467114f2417aa42a2be73d1e7404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85ece043316c4800b182d32f7576384f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":282},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28fd6ec45b864d879cbfde23634f2fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":282},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"800fa9a51aae47569986204b16b4efc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":282},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e58c21cb39a040d9a824c3e79c07efb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":282},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"260b60c1d1024b6bbb6ec9a70567ded5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":330},
            "size":{
              "width":719,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91eba80292f6445ea9f0be63aadd5efb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":330},
                "size":{
                  "width":719,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u117.png"}},
{
          "id":"8f25b7e4f77a448dbe4453f87badbb89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":374},
            "size":{
              "width":20,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aebe3860c8e946beb216eaf997624f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":374},
                "size":{
                  "width":20,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"2c68dfff46614a4d8d66c93834862881",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":402},
            "size":{
              "width":20,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ddf9822fa18418fa35d82fcbfa9db67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":402},
                "size":{
                  "width":20,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"05ba1c727e0a40d78c8e7fb0c8532f03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":760,
              "y":530},
            "size":{
              "width":70,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"614272582eaf46a897ccd08cf39009ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":760,
                  "y":530},
                "size":{
                  "width":70,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提交后信息",
                      "objectsToFades":[{
                          "objectPath":["c644e5d236d2469cbbdef88428b32013"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/批次入库/u33.png"}},
{
          "id":"29905451cde348748cb371cdbeacf395",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6699CC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":321,
              "y":610},
            "size":{
              "width":90,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da263cba12ff47fdb089592e279c5de7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699CC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":321,
                  "y":610},
                "size":{
                  "width":90,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/出货单列表/u185.png",
            "selected~":"images/订单列表/u175_selected.png",
            "mouseOver~":"images/订单列表/u175_mouseOver.png",
            "mouseDown~":"images/订单列表/u175_selected.png"}},
{
          "id":"e99fd8c8e5b74f1b84937bf4c98f89d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6699CC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":500,
              "y":610},
            "size":{
              "width":90,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826ac7c9f41f423d95c7be912d25c3e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699CC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":500,
                  "y":610},
                "size":{
                  "width":90,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单列表/u185.png",
            "selected~":"images/订单列表/u175_selected.png",
            "mouseOver~":"images/订单列表/u175_mouseOver.png",
            "mouseDown~":"images/订单列表/u175_selected.png"}},
{
          "id":"c644e5d236d2469cbbdef88428b32013",
          "label":"提交后信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":131,
              "y":330},
            "size":{
              "width":720,
              "height":240},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7302a9a4a90849399805d0c889015a6e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"81b204aa97f94f66a9e99aaf08164788",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":1},
                    "size":{
                      "width":718,
                      "height":239}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25cc4aeaa46c4a58b9b42b6c3866330a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":1},
                        "size":{
                          "width":718,
                          "height":239}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/批次入库/u40.png"}},
{
                  "id":"0f34d5cbb11a4bc8978969685e0785f8",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":364,
                      "y":44},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1706bcf654bd4359b6a943db8e926c6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":364,
                          "y":44},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6fa59a5c1f07495ea960305d23ab19cc",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":113,
                      "y":44},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"655dcc38f9c240008517bb39b37fd791",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":113,
                          "y":44},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7b9c80df3b6e4110b7caec044290272a",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":113,
                      "y":80},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"762e24b83edd4969bb6c48908af4170b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":113,
                          "y":80},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72969b0a5ef9475ebe0a0b85093f0046",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":364,
                      "y":80},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c7165970d80452abbaabd0807aadcc1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":364,
                          "y":80},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"518d046abbc646f795a0736d77acb0ed",
                  "label":"",
                  "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CCFF},
                    "location":{
                      "x":630,
                      "y":200},
                    "size":{
                      "width":70,
                      "height":30},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2930e4fa76034201bf8b2e3b1e39b437",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c644e5d236d2469cbbdef88428b32013",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00CCFF},
                        "location":{
                          "x":630,
                          "y":200},
                        "size":{
                          "width":70,
                          "height":30},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 提交后信息",
                              "objectsToFades":[{
                                  "objectPath":["c644e5d236d2469cbbdef88428b32013"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/批次入库/u33.png"}}]}]},
{
          "id":"eec56e64625d4126b5ba307721011a23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":149,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e34b5123a44e6997f1a2e1b27a082f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f842ff0a0584290acc218373c71ea0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":220,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a07ee9d125400ab0378f193579a365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e6d68849f084e4e943837e5bf99f5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":300,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807446f22fee4a168a8e9645e80dcf5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b80838897ab48eab620caf386ec8e54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":370,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04196da5a5fb4ae9b9ef24d1822c3ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e647091d9cf6446084363c37bb4f9944",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":456,
              "y":344},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"921c5c3e85f74b0dbe4fb6ce4e319bb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":344},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8609472fa45f4db492d27c6333fe0338",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":501,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eac1b82576d4e80ba5e4a68a9eb591f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":501,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90b6ca6fcbb1471a970d3df90d01d363",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":580,
              "y":344},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62c9af54250446ab8f3b57cd4d1d2e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":344},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5435d4c3cd2f44878b83f5f1e84dcf74":{
      "scriptId":"u0"},
    "e1ba4916503e4fdcb70a4c0278564cee":{
      "scriptId":"u1"},
    "b93235594c3343b58b59bf5b66efe48e":{
      "scriptId":"u2"},
    "2a0c2f90f1a4401a8b83a207219a013b":{
      "scriptId":"u3"},
    "90013a58d92c48d793dfdb69a3f85c6f":{
      "scriptId":"u4"},
    "c36fc71f05b74799b5fdd1c99105406d":{
      "scriptId":"u5"},
    "18ba8d52583749508ab58430420b5596":{
      "scriptId":"u6"},
    "515d3ea59c8241f08f6132521daf825b":{
      "scriptId":"u7"},
    "a34b6df4ef2441e7a747ce19bcf3112c":{
      "scriptId":"u8"},
    "fe7ed0f61ea34734b7c73c8fca3f7e54":{
      "scriptId":"u9"},
    "a400187c04cf403c8665986b9dc15baf":{
      "scriptId":"u10"},
    "c06ec80d05024cd487f3bd84b256b97c":{
      "scriptId":"u11"},
    "79ab6459ec3341bcb74a56953d1a6352":{
      "scriptId":"u12"},
    "0374e4fb287e475c81c326d6ff736ddb":{
      "scriptId":"u13"},
    "e3b120e1db9044b4affc3b3cb6b4c597":{
      "scriptId":"u14"},
    "db6fd7b964b84f52a5df670b43a4ea1e":{
      "scriptId":"u15"},
    "896bea728d1e4beb8e53be00d4e0f950":{
      "scriptId":"u16"},
    "a3f65602dc0049e0a204741da7f9716d":{
      "scriptId":"u17"},
    "c9b0873658b3490f97cc76ace51c0122":{
      "scriptId":"u18"},
    "1a4e178f4ddc48079352929412441bbb":{
      "scriptId":"u19"},
    "75aef486620349d9a9e22ad7657aaf0a":{
      "scriptId":"u20"},
    "27b467168ab34ddc94098a0aa150dddc":{
      "scriptId":"u21"},
    "80fd467114f2417aa42a2be73d1e7404":{
      "scriptId":"u22"},
    "85ece043316c4800b182d32f7576384f":{
      "scriptId":"u23"},
    "28fd6ec45b864d879cbfde23634f2fca":{
      "scriptId":"u24"},
    "800fa9a51aae47569986204b16b4efc8":{
      "scriptId":"u25"},
    "e58c21cb39a040d9a824c3e79c07efb7":{
      "scriptId":"u26"},
    "260b60c1d1024b6bbb6ec9a70567ded5":{
      "scriptId":"u27"},
    "91eba80292f6445ea9f0be63aadd5efb":{
      "scriptId":"u28"},
    "8f25b7e4f77a448dbe4453f87badbb89":{
      "scriptId":"u29"},
    "aebe3860c8e946beb216eaf997624f4f":{
      "scriptId":"u30"},
    "2c68dfff46614a4d8d66c93834862881":{
      "scriptId":"u31"},
    "2ddf9822fa18418fa35d82fcbfa9db67":{
      "scriptId":"u32"},
    "05ba1c727e0a40d78c8e7fb0c8532f03":{
      "scriptId":"u33"},
    "614272582eaf46a897ccd08cf39009ea":{
      "scriptId":"u34"},
    "29905451cde348748cb371cdbeacf395":{
      "scriptId":"u35"},
    "da263cba12ff47fdb089592e279c5de7":{
      "scriptId":"u36"},
    "e99fd8c8e5b74f1b84937bf4c98f89d9":{
      "scriptId":"u37"},
    "826ac7c9f41f423d95c7be912d25c3e7":{
      "scriptId":"u38"},
    "c644e5d236d2469cbbdef88428b32013":{
      "scriptId":"u39"},
    "81b204aa97f94f66a9e99aaf08164788":{
      "scriptId":"u40"},
    "25cc4aeaa46c4a58b9b42b6c3866330a":{
      "scriptId":"u41"},
    "0f34d5cbb11a4bc8978969685e0785f8":{
      "scriptId":"u42"},
    "1706bcf654bd4359b6a943db8e926c6c":{
      "scriptId":"u43"},
    "6fa59a5c1f07495ea960305d23ab19cc":{
      "scriptId":"u44"},
    "655dcc38f9c240008517bb39b37fd791":{
      "scriptId":"u45"},
    "7b9c80df3b6e4110b7caec044290272a":{
      "scriptId":"u46"},
    "762e24b83edd4969bb6c48908af4170b":{
      "scriptId":"u47"},
    "72969b0a5ef9475ebe0a0b85093f0046":{
      "scriptId":"u48"},
    "4c7165970d80452abbaabd0807aadcc1":{
      "scriptId":"u49"},
    "518d046abbc646f795a0736d77acb0ed":{
      "scriptId":"u50"},
    "2930e4fa76034201bf8b2e3b1e39b437":{
      "scriptId":"u51"},
    "eec56e64625d4126b5ba307721011a23":{
      "scriptId":"u52"},
    "e2e34b5123a44e6997f1a2e1b27a082f":{
      "scriptId":"u53"},
    "0f842ff0a0584290acc218373c71ea0b":{
      "scriptId":"u54"},
    "c9a07ee9d125400ab0378f193579a365":{
      "scriptId":"u55"},
    "4e6d68849f084e4e943837e5bf99f5a1":{
      "scriptId":"u56"},
    "807446f22fee4a168a8e9645e80dcf5e":{
      "scriptId":"u57"},
    "5b80838897ab48eab620caf386ec8e54":{
      "scriptId":"u58"},
    "04196da5a5fb4ae9b9ef24d1822c3ac5":{
      "scriptId":"u59"},
    "e647091d9cf6446084363c37bb4f9944":{
      "scriptId":"u60"},
    "921c5c3e85f74b0dbe4fb6ce4e319bb3":{
      "scriptId":"u61"},
    "8609472fa45f4db492d27c6333fe0338":{
      "scriptId":"u62"},
    "3eac1b82576d4e80ba5e4a68a9eb591f":{
      "scriptId":"u63"},
    "90b6ca6fcbb1471a970d3df90d01d363":{
      "scriptId":"u64"},
    "d62c9af54250446ab8f3b57cd4d1d2e3":{
      "scriptId":"u65"}}});