$axure.loadCurrentPage({
  "url":"退货管理_1.html",
  "generationDate":new Date(1442224859132.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"936d336eb2f04bf8a0eacb9112627e4a",
    "type":"Axure:Page",
    "name":"退货管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ee3a3c645f349c680fb8473a2e26c05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442.5,
              "y":9},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470cb21b09b9416daa2716084fec8ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442.5,
                  "y":9},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 方案列表",
                      "objectsToFades":[{
                          "objectPath":["e34d5b176d6148fab09aeb32eeef8a5f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"f6003be49f56462e8373f754cbea179b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":453,
              "y":56},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0afcc36cd99741d4b0cfc79fb460d4cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":453,
                  "y":56},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"560d036966414598b629e7307640c979",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":663,
              "y":61},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"728c69fec7064306b75c1aea0cca35f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":663,
                  "y":61},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"0f7f7c50cec0448282b644d0cbbb9ac7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":61},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d24deeb09134dfeb8e85372697f59f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":61},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"05a92d0f433d488f897167ed0bb8cbed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":61},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d94931bb074a159bea8383137d4f4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":61},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"49e0507a63a04b2cb4d96d86fe0ebf28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":682,
              "y":64},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263374e96e8042d89c7377f691d39aed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":682,
                  "y":64},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a773b3816cf74a21b56d370efcfa9e6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":453,
              "y":78},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b279cb279c2d449385ff3478349a0571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":453,
                  "y":78},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"4cbe4a21eebd415ea1433ffb4c767b8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":82},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a2162786a904fc68304490e88bcbd1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":82},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"6ff96f0ae57346f08577907965f2d362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":159},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c66a76389e7e4b4caa8bacd2f984b9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":159},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121f2917a2d943b1bc8fd1ebe4582271",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":185},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d058baaf3dc400b9e6882a048957060",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":91,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82ce4068496e4d56ad4c40a0e8ca1342",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":91,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u21.png"}},
{
              "id":"b573a2abfeb046229f79bd2c38ed6bd5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":91,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"090a7a2879ba425682d5033b0f72ee92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":91,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u27.png"}},
{
              "id":"e2a5307b37ee463291354fafcb0eb10c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":91,
                  "y":0},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1c07cf24d104796bbfd34f48006d49e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":91,
                      "y":0},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u23.png"}},
{
              "id":"426cd7ff0d7e41728f1a7c6f5f524a70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":91,
                  "y":30},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6ef5ca034a341778c32e529b918fe95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":91,
                      "y":30},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u29.png"}},
{
              "id":"4ab9f040899f4ebc870303b1f2a513bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":0},
                "size":{
                  "width":83,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e04f59cc8fee4bf7aa29d362b4eb7ab1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":0},
                    "size":{
                      "width":83,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u25.png"}},
{
              "id":"322a5231a7364581b9a32bd8403036be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":30},
                "size":{
                  "width":83,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e018dc37a5b48d8b5cf3016b5692a86",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":30},
                    "size":{
                      "width":83,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u31.png"}}]},
{
          "id":"a5a6b6713b04438cbde9b2c1f97e22bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":81},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f278de55e544733812c3284c6c0d881",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":81},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"944f80c18cae45f2bb1ae17a41f6b55d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":492,
              "y":454},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d35d1f1b4984f86a487872a95e4406f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":492,
                  "y":454},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"cd27d88a99824281a027955f8683b33d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":605,
              "y":454},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10743c819bdc48e2bf1cecfd01650542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":605,
                  "y":454},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"9002bf52a4044b26a011403a6b9ddf82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":268},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6757198de5b4106882b514b21ac1b86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":268},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8d9bec4a8544a9e993eae97806006ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":300},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb846190825441be91bfbe594115dcc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":300},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0428bc31c60c4839b113023e5b7e8315",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":323},
            "size":{
              "width":246,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9629044373784210992fde6142abc438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":323},
                "size":{
                  "width":246,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u47.png"}},
{
          "id":"9f15d949f5c64d3bb0c4dd669ab194a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63a22249da14503971d52fdccc0157b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"e980c3830a1f408da13dec1023d4dc29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":56},
            "size":{
              "width":272,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02724f24dc2e45859fa177b0c8f508b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":56},
                "size":{
                  "width":272,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u51.png"}},
{
          "id":"35096ef0e8e34bf587d5219112c55b13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":70,
              "y":81},
            "size":{
              "width":272,
              "height":39},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5053fadab8f433fbe20196c7bc8855a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":70,
                  "y":81},
                "size":{
                  "width":272,
                  "height":39},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u53.png"}},
{
          "id":"38e0bca299a64a86aaf019825bfd5de8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":85},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674c74c20cec4698a3a1056ce84c3920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":85},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"772a0555bde14057950e26557ecf1bbf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":84},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d24f801d6e4413a9a833127bd6f493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":84},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"5446c4194e6c4e4692a920cc93a8e110",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":69,
              "y":56},
            "size":{
              "width":273,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae6977fe41b44c69b7253a5e3c4f1c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":69,
                  "y":56},
                "size":{
                  "width":273,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u59.png"}},
{
          "id":"bd68d577e80e4087b45a11f1a8143cb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":62},
            "size":{
              "width":15,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99100003529d4e3080c9bc516f1fdd54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":62},
                "size":{
                  "width":15,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"f1cef481996440d696490d93a83babf0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":62},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b93f82ae5d3d4c239ade6300ccc1b168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":62},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"9ca3125b0e644f3bbffedd53ddc855b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":303,
              "y":65},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a828fbe1acf948dabc9b58ca69542686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":303,
                  "y":65},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e93d51b5ce4a5d8e7670247eef468e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":62},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d45b338427643d3a43b176a7642572a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":62},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"80ed893eb4004bfc9d625fe51657d577",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":262,
              "y":143},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"743b15c9c8ac4bd4a96f651fdbe8accc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":262,
                  "y":143},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"e34d5b176d6148fab09aeb32eeef8a5f",
          "label":"方案列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":455,
              "y":208},
            "size":{
              "width":267,
              "height":115},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"55a559b935f94ea299af15452414585d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b842434ad3d6485fa934075a91734f2a",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CC99},
                    "size":{
                      "width":260,
                      "height":110},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86632e7a1c2341b2a1c6e776e65c1bd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00CC99},
                        "size":{
                          "width":260,
                          "height":110},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单管理_1/u66.png"}},
{
                  "id":"1cfb39a56b0e4d81920f0f3537ff73fa",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4b7c3c2355241619f4c1bb652ebabef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f287addb4684bfd8adde054755c80d0",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":117,
                      "y":12},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7ef6594ef46489f92eaeee942e13bd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":117,
                          "y":12},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f133388b8921474089b0a5aea80f293c",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":181,
                      "y":12},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df48c4f66c574e0cad9e87889f441e64",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":181,
                          "y":12},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a9c0f9d153d149b99c0b5243b9698356",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":38},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23f833f8f3c1455ea1ab848d6ba27aa8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":38},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64cecd6a8f9e4e7f849b19848b07864d",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":64},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc2f79db99054035b5c00b6f35675a9b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":64},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8f15689d7fcd45e68cc75b8479a5ce9c",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":38},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"444cfe11826d4c2a91f30817e3d178e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":121,
                          "y":38},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0e46e8b06d5e436d9fa5bf491b3d60b2",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":38},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76d10ea3ab5d48f9ada7e06bb3899dae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":38},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fe2b05148e5a493487cfb23a126a5b2c",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":64},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38bb605f57e34632abaa28e089ce61d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":121,
                          "y":64},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e524861871a74f64a2b0f0258210db9d",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":64},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"032e6912093b43369d56ce6ab6cf232e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":64},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2aa50a357e3f429ab412dff5e43505a5",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":11},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43ca43748fd34a89b96f7e535388dc6d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":11},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"379724ec459842a9a80f269424f7c42f",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":37},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23d97f4679f141cf9594fb5d48a3e2e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":37},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"95121b5061d140739efec5db76a8bb60",
                  "label":"",
                  "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":63},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5389803c1195495794feaaebdd34ba68",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e34d5b176d6148fab09aeb32eeef8a5f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":63},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]}]}]},
{
          "id":"9e4044dff0434fe8ba04b0013c6c0b9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":688,
              "y":154.5},
            "size":{
              "width":27,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd20b320fcb148e895fd9b92401908d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":688,
                  "y":154.5},
                "size":{
                  "width":27,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 方案列表",
                      "objectsToFades":[{
                          "objectPath":["e34d5b176d6148fab09aeb32eeef8a5f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单管理/u138.png"}},
{
          "id":"3bbbdc449c5345ce89e89407ba7b8c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":108,
              "y":211},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e138392a574c80bd6f3e770315f871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":211},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55e757daf80f41e1b6a0cd4c14aec676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":170,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32205e9a0454abead895dc67d2a7423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e89de71158043a1a809e86e011ebdcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":266,
              "y":210},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba3a8bcd435c481da7ca079cd4e40a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":266,
                  "y":210},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1904ada043a64e1ca449d82ac0047e2f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":226},
            "size":{
              "width":227,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提现管理/u31_line.png"}},
{
          "id":"7aa59c3256ad4a45b7c92be43faa307b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":239},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc2682bea7ac4762b5faa9bf82858de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":239},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284e564f92e94844aacd4b5d996b3416",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":239},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"962d707fd3024037a3f0b4c2e3e34d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":239},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8af94b7dd3f14e5eb8c03a500d526d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":239},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09bea99f7ddc4d57968d93126ae0e7db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":239},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b56b3d62d394d86b89818347b15cda3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":255},
            "size":{
              "width":225,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提现管理/u38_line.png"}},
{
          "id":"fc8fc72cb3714a37972bbee79e43317c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":268},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbba8604ad954c52a682f19af261ec69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":268},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48e5b67eeab54a428b4825044d0c7619",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":268},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf86b1f52964c0583fb2e738f8eec24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":268},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f17f04d74fc44e83bcb30cbcaff248ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":268},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59817803b6414bab9862d5da780dd70c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":268},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f6a2b341d80477e8df6c1938a1b924a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":283},
            "size":{
              "width":227,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提现管理/u31_line.png"}},
{
          "id":"5e68a9e643264ce88b4f1bf7fc1b0467",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":296},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac13e233b991492c9dba33e8e909cc04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":296},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61afc8e47efa47e683d3f42b3e7db20a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":296},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ec5eb9195ab40af9c3f57646fff03a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":296},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a618f54f5d43478408078eaffdda00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":296},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7a75b0dbfc42ab8f56af110de22564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":296},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ee3a3c645f349c680fb8473a2e26c05":{
      "scriptId":"u0"},
    "470cb21b09b9416daa2716084fec8ec1":{
      "scriptId":"u1"},
    "f6003be49f56462e8373f754cbea179b":{
      "scriptId":"u2"},
    "0afcc36cd99741d4b0cfc79fb460d4cc":{
      "scriptId":"u3"},
    "560d036966414598b629e7307640c979":{
      "scriptId":"u4"},
    "728c69fec7064306b75c1aea0cca35f8":{
      "scriptId":"u5"},
    "0f7f7c50cec0448282b644d0cbbb9ac7":{
      "scriptId":"u6"},
    "1d24deeb09134dfeb8e85372697f59f1":{
      "scriptId":"u7"},
    "05a92d0f433d488f897167ed0bb8cbed":{
      "scriptId":"u8"},
    "01d94931bb074a159bea8383137d4f4b":{
      "scriptId":"u9"},
    "49e0507a63a04b2cb4d96d86fe0ebf28":{
      "scriptId":"u10"},
    "263374e96e8042d89c7377f691d39aed":{
      "scriptId":"u11"},
    "a773b3816cf74a21b56d370efcfa9e6f":{
      "scriptId":"u12"},
    "b279cb279c2d449385ff3478349a0571":{
      "scriptId":"u13"},
    "4cbe4a21eebd415ea1433ffb4c767b8a":{
      "scriptId":"u14"},
    "3a2162786a904fc68304490e88bcbd1f":{
      "scriptId":"u15"},
    "6ff96f0ae57346f08577907965f2d362":{
      "scriptId":"u16"},
    "c66a76389e7e4b4caa8bacd2f984b9bb":{
      "scriptId":"u17"},
    "121f2917a2d943b1bc8fd1ebe4582271":{
      "scriptId":"u18"},
    "0d058baaf3dc400b9e6882a048957060":{
      "scriptId":"u19"},
    "82ce4068496e4d56ad4c40a0e8ca1342":{
      "scriptId":"u20"},
    "e2a5307b37ee463291354fafcb0eb10c":{
      "scriptId":"u21"},
    "f1c07cf24d104796bbfd34f48006d49e":{
      "scriptId":"u22"},
    "4ab9f040899f4ebc870303b1f2a513bc":{
      "scriptId":"u23"},
    "e04f59cc8fee4bf7aa29d362b4eb7ab1":{
      "scriptId":"u24"},
    "b573a2abfeb046229f79bd2c38ed6bd5":{
      "scriptId":"u25"},
    "090a7a2879ba425682d5033b0f72ee92":{
      "scriptId":"u26"},
    "426cd7ff0d7e41728f1a7c6f5f524a70":{
      "scriptId":"u27"},
    "e6ef5ca034a341778c32e529b918fe95":{
      "scriptId":"u28"},
    "322a5231a7364581b9a32bd8403036be":{
      "scriptId":"u29"},
    "4e018dc37a5b48d8b5cf3016b5692a86":{
      "scriptId":"u30"},
    "a5a6b6713b04438cbde9b2c1f97e22bb":{
      "scriptId":"u31"},
    "9f278de55e544733812c3284c6c0d881":{
      "scriptId":"u32"},
    "944f80c18cae45f2bb1ae17a41f6b55d":{
      "scriptId":"u33"},
    "6d35d1f1b4984f86a487872a95e4406f":{
      "scriptId":"u34"},
    "cd27d88a99824281a027955f8683b33d":{
      "scriptId":"u35"},
    "10743c819bdc48e2bf1cecfd01650542":{
      "scriptId":"u36"},
    "9002bf52a4044b26a011403a6b9ddf82":{
      "scriptId":"u37"},
    "d6757198de5b4106882b514b21ac1b86":{
      "scriptId":"u38"},
    "b8d9bec4a8544a9e993eae97806006ad":{
      "scriptId":"u39"},
    "fb846190825441be91bfbe594115dcc9":{
      "scriptId":"u40"},
    "0428bc31c60c4839b113023e5b7e8315":{
      "scriptId":"u41"},
    "9629044373784210992fde6142abc438":{
      "scriptId":"u42"},
    "9f15d949f5c64d3bb0c4dd669ab194a9":{
      "scriptId":"u43"},
    "b63a22249da14503971d52fdccc0157b":{
      "scriptId":"u44"},
    "e980c3830a1f408da13dec1023d4dc29":{
      "scriptId":"u45"},
    "02724f24dc2e45859fa177b0c8f508b1":{
      "scriptId":"u46"},
    "35096ef0e8e34bf587d5219112c55b13":{
      "scriptId":"u47"},
    "d5053fadab8f433fbe20196c7bc8855a":{
      "scriptId":"u48"},
    "38e0bca299a64a86aaf019825bfd5de8":{
      "scriptId":"u49"},
    "674c74c20cec4698a3a1056ce84c3920":{
      "scriptId":"u50"},
    "772a0555bde14057950e26557ecf1bbf":{
      "scriptId":"u51"},
    "75d24f801d6e4413a9a833127bd6f493":{
      "scriptId":"u52"},
    "5446c4194e6c4e4692a920cc93a8e110":{
      "scriptId":"u53"},
    "ae6977fe41b44c69b7253a5e3c4f1c3a":{
      "scriptId":"u54"},
    "bd68d577e80e4087b45a11f1a8143cb6":{
      "scriptId":"u55"},
    "99100003529d4e3080c9bc516f1fdd54":{
      "scriptId":"u56"},
    "f1cef481996440d696490d93a83babf0":{
      "scriptId":"u57"},
    "b93f82ae5d3d4c239ade6300ccc1b168":{
      "scriptId":"u58"},
    "9ca3125b0e644f3bbffedd53ddc855b6":{
      "scriptId":"u59"},
    "a828fbe1acf948dabc9b58ca69542686":{
      "scriptId":"u60"},
    "c3e93d51b5ce4a5d8e7670247eef468e":{
      "scriptId":"u61"},
    "2d45b338427643d3a43b176a7642572a":{
      "scriptId":"u62"},
    "80ed893eb4004bfc9d625fe51657d577":{
      "scriptId":"u63"},
    "743b15c9c8ac4bd4a96f651fdbe8accc":{
      "scriptId":"u64"},
    "e34d5b176d6148fab09aeb32eeef8a5f":{
      "scriptId":"u65"},
    "b842434ad3d6485fa934075a91734f2a":{
      "scriptId":"u66"},
    "86632e7a1c2341b2a1c6e776e65c1bd2":{
      "scriptId":"u67"},
    "1cfb39a56b0e4d81920f0f3537ff73fa":{
      "scriptId":"u68"},
    "b4b7c3c2355241619f4c1bb652ebabef":{
      "scriptId":"u69"},
    "3f287addb4684bfd8adde054755c80d0":{
      "scriptId":"u70"},
    "c7ef6594ef46489f92eaeee942e13bd3":{
      "scriptId":"u71"},
    "f133388b8921474089b0a5aea80f293c":{
      "scriptId":"u72"},
    "df48c4f66c574e0cad9e87889f441e64":{
      "scriptId":"u73"},
    "a9c0f9d153d149b99c0b5243b9698356":{
      "scriptId":"u74"},
    "23f833f8f3c1455ea1ab848d6ba27aa8":{
      "scriptId":"u75"},
    "64cecd6a8f9e4e7f849b19848b07864d":{
      "scriptId":"u76"},
    "dc2f79db99054035b5c00b6f35675a9b":{
      "scriptId":"u77"},
    "8f15689d7fcd45e68cc75b8479a5ce9c":{
      "scriptId":"u78"},
    "444cfe11826d4c2a91f30817e3d178e9":{
      "scriptId":"u79"},
    "0e46e8b06d5e436d9fa5bf491b3d60b2":{
      "scriptId":"u80"},
    "76d10ea3ab5d48f9ada7e06bb3899dae":{
      "scriptId":"u81"},
    "fe2b05148e5a493487cfb23a126a5b2c":{
      "scriptId":"u82"},
    "38bb605f57e34632abaa28e089ce61d4":{
      "scriptId":"u83"},
    "e524861871a74f64a2b0f0258210db9d":{
      "scriptId":"u84"},
    "032e6912093b43369d56ce6ab6cf232e":{
      "scriptId":"u85"},
    "2aa50a357e3f429ab412dff5e43505a5":{
      "scriptId":"u86"},
    "43ca43748fd34a89b96f7e535388dc6d":{
      "scriptId":"u87"},
    "379724ec459842a9a80f269424f7c42f":{
      "scriptId":"u88"},
    "23d97f4679f141cf9594fb5d48a3e2e2":{
      "scriptId":"u89"},
    "95121b5061d140739efec5db76a8bb60":{
      "scriptId":"u90"},
    "5389803c1195495794feaaebdd34ba68":{
      "scriptId":"u91"},
    "9e4044dff0434fe8ba04b0013c6c0b9b":{
      "scriptId":"u92"},
    "bd20b320fcb148e895fd9b92401908d8":{
      "scriptId":"u93"},
    "3bbbdc449c5345ce89e89407ba7b8c2b":{
      "scriptId":"u94"},
    "67e138392a574c80bd6f3e770315f871":{
      "scriptId":"u95"},
    "55e757daf80f41e1b6a0cd4c14aec676":{
      "scriptId":"u96"},
    "c32205e9a0454abead895dc67d2a7423":{
      "scriptId":"u97"},
    "8e89de71158043a1a809e86e011ebdcf":{
      "scriptId":"u98"},
    "ba3a8bcd435c481da7ca079cd4e40a8b":{
      "scriptId":"u99"},
    "1904ada043a64e1ca449d82ac0047e2f":{
      "scriptId":"u100"},
    "7aa59c3256ad4a45b7c92be43faa307b":{
      "scriptId":"u101"},
    "dc2682bea7ac4762b5faa9bf82858de5":{
      "scriptId":"u102"},
    "284e564f92e94844aacd4b5d996b3416":{
      "scriptId":"u103"},
    "962d707fd3024037a3f0b4c2e3e34d5b":{
      "scriptId":"u104"},
    "8af94b7dd3f14e5eb8c03a500d526d5f":{
      "scriptId":"u105"},
    "09bea99f7ddc4d57968d93126ae0e7db":{
      "scriptId":"u106"},
    "8b56b3d62d394d86b89818347b15cda3":{
      "scriptId":"u107"},
    "fc8fc72cb3714a37972bbee79e43317c":{
      "scriptId":"u108"},
    "bbba8604ad954c52a682f19af261ec69":{
      "scriptId":"u109"},
    "48e5b67eeab54a428b4825044d0c7619":{
      "scriptId":"u110"},
    "2cf86b1f52964c0583fb2e738f8eec24":{
      "scriptId":"u111"},
    "f17f04d74fc44e83bcb30cbcaff248ed":{
      "scriptId":"u112"},
    "59817803b6414bab9862d5da780dd70c":{
      "scriptId":"u113"},
    "0f6a2b341d80477e8df6c1938a1b924a":{
      "scriptId":"u114"},
    "5e68a9e643264ce88b4f1bf7fc1b0467":{
      "scriptId":"u115"},
    "ac13e233b991492c9dba33e8e909cc04":{
      "scriptId":"u116"},
    "61afc8e47efa47e683d3f42b3e7db20a":{
      "scriptId":"u117"},
    "8ec5eb9195ab40af9c3f57646fff03a3":{
      "scriptId":"u118"},
    "57a618f54f5d43478408078eaffdda00":{
      "scriptId":"u119"},
    "db7a75b0dbfc42ab8f56af110de22564":{
      "scriptId":"u120"}}});