$axure.loadCurrentPage({
  "url":"还款凭证.html",
  "generationDate":new Date(1443166055709.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"0b6b460a6f0f4281b7399c1532547d9b",
    "type":"Axure:Page",
    "name":"还款凭证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"adf103cfece24679bae14a5e36545c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":10},
            "size":{
              "width":440,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d51b9e9dfcf44df6a457f0a1c8824f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":10},
                "size":{
                  "width":440,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现审批/u95.png"}},
{
          "id":"22988a25745948febfebe26ebaca2f9c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":51},
            "size":{
              "width":420,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提现审批/u97_line.png"}},
{
          "id":"5f4e8faba9be44ce8b5426526110a267",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":231,
              "y":28},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f37e574a8da14a0e8caab78fc5811a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":231,
                  "y":28},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2221c4ea384a43c6a075ebaa1c004aa5",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":83},
            "size":{
              "width":400,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8734701facdb44b3bdea219fe6c6cae6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8821f411f864557b7dd6769d6190cd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"b06cbe84722d4bdca246373ce15a9cef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"965f84407aae47e2b6f70bd24b1dd295",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"cbf2384faa1644369d5100f724b4c53c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4de0ad2bb05468c9762e304926ce205",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"2bfc28c6f7f04180bd0c9dd2c4f6f7ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29e6de39b26143ef94351931b2deb543",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"7f220791c887456492241a41722e7a82",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62fd1973555b4e0ebb9535c66da687ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"38ce2e5fd6ed49ca9ee2ab0af72a6c19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"beb2b5973f574686a52dd250e05db8e8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"762451e1145f44ca9cf644f3281cf2ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a5e625679254b59bf7f81d1bd430a08",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"b9a3c85ab4064b04a89e10c6fb0f620c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02e4164fe471407eb425382e35ba42ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"ee9048e2ed00401aa4cbc925f5c07f7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae5624d33abb49a8ba7d055b514eeed7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"b18ea8a2b2d749af94a41c8de10c4b92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"10cc559b46614dd6890d4735767757b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u107.png"}},
{
              "id":"83e6452f0e1a439989c94bf35430549d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bfd08f91c4db466fb76940bcc68aa593",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u107.png"}},
{
              "id":"ae5daf3696d742288e395d45978cc51a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6ef44b79bc0448cb139ecc542830818",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u123.png"}}]},
{
          "id":"b37f7c89d73742a6b0b57ed0ee3ede06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":63},
            "size":{
              "width":177,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ef6db3d182472881b2b25986c1a090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":63},
                "size":{
                  "width":177,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "adf103cfece24679bae14a5e36545c3e":{
      "scriptId":"u0"},
    "d51b9e9dfcf44df6a457f0a1c8824f9d":{
      "scriptId":"u1"},
    "22988a25745948febfebe26ebaca2f9c":{
      "scriptId":"u2"},
    "5f4e8faba9be44ce8b5426526110a267":{
      "scriptId":"u3"},
    "f37e574a8da14a0e8caab78fc5811a4c":{
      "scriptId":"u4"},
    "2221c4ea384a43c6a075ebaa1c004aa5":{
      "scriptId":"u5"},
    "8734701facdb44b3bdea219fe6c6cae6":{
      "scriptId":"u6"},
    "c8821f411f864557b7dd6769d6190cd6":{
      "scriptId":"u7"},
    "2bfc28c6f7f04180bd0c9dd2c4f6f7ef":{
      "scriptId":"u8"},
    "29e6de39b26143ef94351931b2deb543":{
      "scriptId":"u9"},
    "762451e1145f44ca9cf644f3281cf2ad":{
      "scriptId":"u10"},
    "4a5e625679254b59bf7f81d1bd430a08":{
      "scriptId":"u11"},
    "b18ea8a2b2d749af94a41c8de10c4b92":{
      "scriptId":"u12"},
    "10cc559b46614dd6890d4735767757b8":{
      "scriptId":"u13"},
    "b06cbe84722d4bdca246373ce15a9cef":{
      "scriptId":"u14"},
    "965f84407aae47e2b6f70bd24b1dd295":{
      "scriptId":"u15"},
    "7f220791c887456492241a41722e7a82":{
      "scriptId":"u16"},
    "62fd1973555b4e0ebb9535c66da687ee":{
      "scriptId":"u17"},
    "b9a3c85ab4064b04a89e10c6fb0f620c":{
      "scriptId":"u18"},
    "02e4164fe471407eb425382e35ba42ec":{
      "scriptId":"u19"},
    "83e6452f0e1a439989c94bf35430549d":{
      "scriptId":"u20"},
    "bfd08f91c4db466fb76940bcc68aa593":{
      "scriptId":"u21"},
    "cbf2384faa1644369d5100f724b4c53c":{
      "scriptId":"u22"},
    "c4de0ad2bb05468c9762e304926ce205":{
      "scriptId":"u23"},
    "38ce2e5fd6ed49ca9ee2ab0af72a6c19":{
      "scriptId":"u24"},
    "beb2b5973f574686a52dd250e05db8e8":{
      "scriptId":"u25"},
    "ee9048e2ed00401aa4cbc925f5c07f7d":{
      "scriptId":"u26"},
    "ae5624d33abb49a8ba7d055b514eeed7":{
      "scriptId":"u27"},
    "ae5daf3696d742288e395d45978cc51a":{
      "scriptId":"u28"},
    "c6ef44b79bc0448cb139ecc542830818":{
      "scriptId":"u29"},
    "b37f7c89d73742a6b0b57ed0ee3ede06":{
      "scriptId":"u30"},
    "53ef6db3d182472881b2b25986c1a090":{
      "scriptId":"u31"}}});