$axure.loadCurrentPage({
  "url":"扫描测试.html",
  "generationDate":new Date(1444726799307.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dc6da472074e490f9e006674c15c6fa5",
    "type":"Axure:Page",
    "name":"扫描测试",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"336d6b24417843a3b7b3c319ed370ea2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":60},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cbebace9850403ba881c22bd19eaba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":60},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"9d1f5d497b7646b99979b703530054d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":78,
              "y":106},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e49cc5850d5843d088c34e30e4856e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":78,
                  "y":106},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"f631a49c3d684d12bae3218d7e6271d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bf91c76a75e417cbf5564055ccb17f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"d07734e3d06a4113b7bc3a7d37366d40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":111},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d075446c6d7d417cbf1c119b32d98112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":111},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"e81f20d29f4c4899bc7330c2bfeda3c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cd26414df54dc69f4e55ba327abc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"90186a98e3614896b23a4456979d7336",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":307,
              "y":114},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd579edc5fb49da9827bf2be40de9d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":114},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5efdaec005b549c28e53235019145164",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":78,
              "y":128},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf7f70b7b7947f09f3a32d5482110b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":78,
                  "y":128},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"051f56465a5f447bb797642988c5cb2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":132},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b0411db0bab4ac98aac68f6532a3ee1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":132},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"fda7aec858e34017bc4f8961fd1c9d5c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":131},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33853ce9572f4e9e91b4ee4316b77980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":131},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改登录密码/u27.png"}},
{
          "id":"24e5009fd087450bb8355cfb2e663ae2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":127,
              "y":200},
            "size":{
              "width":173,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c8a1658029c4245adb2c3fb63d0555f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":127,
                  "y":200},
                "size":{
                  "width":173,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 扫描中",
                      "objectsToFades":[{
                          "objectPath":["0725707707de44dfbfe9bc9bd522be2a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/扫描测试/u18.png"}},
{
          "id":"0725707707de44dfbfe9bc9bd522be2a",
          "label":"扫描中",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":79,
              "y":190},
            "size":{
              "width":267,
              "height":50},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9a3fb8af776f4b04adad66126cf83bd1",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ce4a87fe347e4a8dacf07edcd712f474",
                  "label":"",
                  "parentDynamicPanel":"0725707707de44dfbfe9bc9bd522be2a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":0,
                      "y":2},
                    "size":{
                      "width":260,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25f915018bb545fa91121bdb328fb589",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0725707707de44dfbfe9bc9bd522be2a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":0,
                          "y":2},
                        "size":{
                          "width":260,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/站点退货/u215.png"}},
{
                  "id":"e22cf96fc9f24809a651168ece60582a",
                  "label":"",
                  "parentDynamicPanel":"0725707707de44dfbfe9bc9bd522be2a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":10},
                    "size":{
                      "width":28,
                      "height":30},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09404d00fe1640b1a9f61b2e217b28b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0725707707de44dfbfe9bc9bd522be2a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":47,
                          "y":10},
                        "size":{
                          "width":28,
                          "height":30},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/站点入库/u100.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "336d6b24417843a3b7b3c319ed370ea2":{
      "scriptId":"u0"},
    "0cbebace9850403ba881c22bd19eaba5":{
      "scriptId":"u1"},
    "9d1f5d497b7646b99979b703530054d3":{
      "scriptId":"u2"},
    "e49cc5850d5843d088c34e30e4856e39":{
      "scriptId":"u3"},
    "f631a49c3d684d12bae3218d7e6271d7":{
      "scriptId":"u4"},
    "8bf91c76a75e417cbf5564055ccb17f9":{
      "scriptId":"u5"},
    "d07734e3d06a4113b7bc3a7d37366d40":{
      "scriptId":"u6"},
    "d075446c6d7d417cbf1c119b32d98112":{
      "scriptId":"u7"},
    "e81f20d29f4c4899bc7330c2bfeda3c3":{
      "scriptId":"u8"},
    "28cd26414df54dc69f4e55ba327abc25":{
      "scriptId":"u9"},
    "90186a98e3614896b23a4456979d7336":{
      "scriptId":"u10"},
    "3cd579edc5fb49da9827bf2be40de9d3":{
      "scriptId":"u11"},
    "5efdaec005b549c28e53235019145164":{
      "scriptId":"u12"},
    "6bf7f70b7b7947f09f3a32d5482110b1":{
      "scriptId":"u13"},
    "051f56465a5f447bb797642988c5cb2d":{
      "scriptId":"u14"},
    "8b0411db0bab4ac98aac68f6532a3ee1":{
      "scriptId":"u15"},
    "fda7aec858e34017bc4f8961fd1c9d5c":{
      "scriptId":"u16"},
    "33853ce9572f4e9e91b4ee4316b77980":{
      "scriptId":"u17"},
    "24e5009fd087450bb8355cfb2e663ae2":{
      "scriptId":"u18"},
    "3c8a1658029c4245adb2c3fb63d0555f":{
      "scriptId":"u19"},
    "0725707707de44dfbfe9bc9bd522be2a":{
      "scriptId":"u20"},
    "ce4a87fe347e4a8dacf07edcd712f474":{
      "scriptId":"u21"},
    "25f915018bb545fa91121bdb328fb589":{
      "scriptId":"u22"},
    "e22cf96fc9f24809a651168ece60582a":{
      "scriptId":"u23"},
    "09404d00fe1640b1a9f61b2e217b28b1":{
      "scriptId":"u24"}}});