$axure.loadCurrentPage({
  "url":"签退.html",
  "generationDate":new Date(1444726798092.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1b28b3f21f349fe8f79d4bb589509bd",
    "type":"Axure:Page",
    "name":"签退",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8bb93bc9b943475f855d72e152cff372",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":295,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f1f701a0c64804b0678aeb82dd0d5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":295,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"3fba99c46dee4a0790dc1a3ae41d4399",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":73,
              "y":126},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b434d913478d475d9b2d22ac4c9e1c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":73,
                  "y":126},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"b4ffaae02e964118a701977de4b9e338",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba227019c54d4d4fb2766b89c366427d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"f4b6b4a31e67491cbc2751979049a168",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":131},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf4bdd0635f455ba575b4a86bd4ad1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":131},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"96ae1af122d04bd88ad36924463a3456",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"315e5e75e9d143309b975dc447a15c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"45f9973e7b9d47b4b18862741885bb77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":302,
              "y":134},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b9a9993d50c4887b2d157a479ca5499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":134},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8001a3ab379940309c7c6652cae445cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":73,
              "y":148},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e2c521564a402595ebb8509ad2cda6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":73,
                  "y":148},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"819d56d1711141dca613de1f8de7059b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":152},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5ea557c9e64e0eaf642ce8e7d3c25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":152},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签退",
                      "objectsToFades":[{
                          "objectPath":["5b6bf5715eed4dc2b287213d416a426b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"89b36bcef0b446bb8eb13f1b581f9c68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":85,
              "y":371},
            "size":{
              "width":245,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8c2b9707a84cd5b37af1e1e61099f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":85,
                  "y":371},
                "size":{
                  "width":245,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"77d493c369c445c691413c0a32a8dc15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":203},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724d66b887954f90a5c6d0b86a6942bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":203},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b0fef1391dd466e96726f9002e534df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":252},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50f83f9ee9324c9b96e98883771f0e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":252},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecd4a48dd6674b94acd545cfacac848c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":224},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"02bd57002c37465cb6aa02b97188891e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":274},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"2b1fccabf25e488fb4852e310876ccb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":158,
              "y":203},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e72d782a6a354ccca8a387763fe73324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":203},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77405cc5c06a4f959a7fd8b3f8f886cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":157,
              "y":252},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06736fd10aee43fe9653a9c340d3652e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":252},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b6bf5715eed4dc2b287213d416a426b",
          "label":"签退",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":180},
            "size":{
              "width":100,
              "height":90}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fadfc788565d428ea7596d6ce03095b3",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2eeb8421bca34d14a717bed333a5745c",
                  "label":"",
                  "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e475b1447794ab4a0f5f229977c0483",
                      "label":"",
                      "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2420edc19f904122ab02456b67301f85",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF666666},
                            "size":{
                              "width":100,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/签退/u30.png"}},
{
                      "id":"75248e54bf904e4da050732972fac7d5",
                      "label":"",
                      "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF666666},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7474161a4fe74926a5f73706934c57c7",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF666666},
                            "location":{
                              "x":0,
                              "y":30},
                            "size":{
                              "width":100,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/签退/u30.png"}},
{
                      "id":"6332b5a828d14ea78e4f644baab29385",
                      "label":"",
                      "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF66CC99},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0e6ad850ac934d98a4e1d86e7a75b1ce",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"5b6bf5715eed4dc2b287213d416a426b",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF66CC99},
                            "location":{
                              "x":0,
                              "y":60},
                            "size":{
                              "width":100,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"fadeWidget",
                                  "description":"显示 签退确认,<br>隐藏 签退",
                                  "objectsToFades":[{
                                      "objectPath":["b1b4807c20574fc490be5cc15d77f2ba"],
                                      "fadeInfo":{
                                        "fadeType":"show",
                                        "options":{
                                          "showType":"none"}}},
{
                                      "objectPath":["5b6bf5715eed4dc2b287213d416a426b"],
                                      "fadeInfo":{
                                        "fadeType":"hide",
                                        "options":{
                                          "showType":"none"}}}]}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/签退/u34.png"}}]}]}]},
{
          "id":"9a1bc1ca7e8a4069bc98ac24e7e1923c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":302},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9c805b3b40e84e828db3ec62a3d9b637",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":304},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7a9b587360147c8b6f6e4f20f882258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":304},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1b4807c20574fc490be5cc15d77f2ba",
          "label":"签退确认",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":301},
            "size":{
              "width":245,
              "height":139}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b1ff5988ce81489b8eae2ea114e0bf59",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"36c3932093cb49479a16aecb1e5114a8",
                  "label":"",
                  "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3d99298da054694afc08367f6b58e61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/签退/u40.png"}},
{
                  "id":"3b46a99748544308baa910057952c154",
                  "label":"",
                  "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9900},
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83732cd11a6842349defd2f3c48d1299",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9900},
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":120,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 签退确认",
                              "objectsToFades":[{
                                  "objectPath":["b1b4807c20574fc490be5cc15d77f2ba"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/签退/u42.png"}},
{
                  "id":"005abd46057b40a19af0617615c53946",
                  "label":"",
                  "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF9900},
                    "location":{
                      "x":120,
                      "y":100},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45fe8a111af144b69b76d512db514561",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF9900},
                        "location":{
                          "x":120,
                          "y":100},
                        "size":{
                          "width":120,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/签退/u42.png"}},
{
                  "id":"3c106b43b516480fb815c1e5182e4eaa",
                  "label":"",
                  "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":42,
                      "y":45},
                    "size":{
                      "width":157,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8aa5735d9d5644c18bdd42e0a54640cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b1b4807c20574fc490be5cc15d77f2ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":42,
                          "y":45},
                        "size":{
                          "width":157,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"0474e27b7cc3415e942e979259a63dfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":123,
              "y":471},
            "size":{
              "width":144,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d05b18258cb4165b6c2a7c84bef3c35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":471},
                "size":{
                  "width":144,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8bb93bc9b943475f855d72e152cff372":{
      "scriptId":"u0"},
    "15f1f701a0c64804b0678aeb82dd0d5f":{
      "scriptId":"u1"},
    "3fba99c46dee4a0790dc1a3ae41d4399":{
      "scriptId":"u2"},
    "b434d913478d475d9b2d22ac4c9e1c2f":{
      "scriptId":"u3"},
    "b4ffaae02e964118a701977de4b9e338":{
      "scriptId":"u4"},
    "ba227019c54d4d4fb2766b89c366427d":{
      "scriptId":"u5"},
    "f4b6b4a31e67491cbc2751979049a168":{
      "scriptId":"u6"},
    "caf4bdd0635f455ba575b4a86bd4ad1a":{
      "scriptId":"u7"},
    "96ae1af122d04bd88ad36924463a3456":{
      "scriptId":"u8"},
    "315e5e75e9d143309b975dc447a15c3f":{
      "scriptId":"u9"},
    "45f9973e7b9d47b4b18862741885bb77":{
      "scriptId":"u10"},
    "9b9a9993d50c4887b2d157a479ca5499":{
      "scriptId":"u11"},
    "8001a3ab379940309c7c6652cae445cc":{
      "scriptId":"u12"},
    "67e2c521564a402595ebb8509ad2cda6":{
      "scriptId":"u13"},
    "819d56d1711141dca613de1f8de7059b":{
      "scriptId":"u14"},
    "9f5ea557c9e64e0eaf642ce8e7d3c25a":{
      "scriptId":"u15"},
    "89b36bcef0b446bb8eb13f1b581f9c68":{
      "scriptId":"u16"},
    "6a8c2b9707a84cd5b37af1e1e61099f9":{
      "scriptId":"u17"},
    "77d493c369c445c691413c0a32a8dc15":{
      "scriptId":"u18"},
    "724d66b887954f90a5c6d0b86a6942bc":{
      "scriptId":"u19"},
    "2b0fef1391dd466e96726f9002e534df":{
      "scriptId":"u20"},
    "50f83f9ee9324c9b96e98883771f0e0e":{
      "scriptId":"u21"},
    "ecd4a48dd6674b94acd545cfacac848c":{
      "scriptId":"u22"},
    "02bd57002c37465cb6aa02b97188891e":{
      "scriptId":"u23"},
    "2b1fccabf25e488fb4852e310876ccb4":{
      "scriptId":"u24"},
    "e72d782a6a354ccca8a387763fe73324":{
      "scriptId":"u25"},
    "77405cc5c06a4f959a7fd8b3f8f886cf":{
      "scriptId":"u26"},
    "06736fd10aee43fe9653a9c340d3652e":{
      "scriptId":"u27"},
    "5b6bf5715eed4dc2b287213d416a426b":{
      "scriptId":"u28"},
    "2eeb8421bca34d14a717bed333a5745c":{
      "scriptId":"u29"},
    "7e475b1447794ab4a0f5f229977c0483":{
      "scriptId":"u30"},
    "2420edc19f904122ab02456b67301f85":{
      "scriptId":"u31"},
    "75248e54bf904e4da050732972fac7d5":{
      "scriptId":"u32"},
    "7474161a4fe74926a5f73706934c57c7":{
      "scriptId":"u33"},
    "6332b5a828d14ea78e4f644baab29385":{
      "scriptId":"u34"},
    "0e6ad850ac934d98a4e1d86e7a75b1ce":{
      "scriptId":"u35"},
    "9a1bc1ca7e8a4069bc98ac24e7e1923c":{
      "scriptId":"u36"},
    "9c805b3b40e84e828db3ec62a3d9b637":{
      "scriptId":"u37"},
    "d7a9b587360147c8b6f6e4f20f882258":{
      "scriptId":"u38"},
    "b1b4807c20574fc490be5cc15d77f2ba":{
      "scriptId":"u39"},
    "36c3932093cb49479a16aecb1e5114a8":{
      "scriptId":"u40"},
    "d3d99298da054694afc08367f6b58e61":{
      "scriptId":"u41"},
    "3b46a99748544308baa910057952c154":{
      "scriptId":"u42"},
    "83732cd11a6842349defd2f3c48d1299":{
      "scriptId":"u43"},
    "005abd46057b40a19af0617615c53946":{
      "scriptId":"u44"},
    "45fe8a111af144b69b76d512db514561":{
      "scriptId":"u45"},
    "3c106b43b516480fb815c1e5182e4eaa":{
      "scriptId":"u46"},
    "8aa5735d9d5644c18bdd42e0a54640cc":{
      "scriptId":"u47"},
    "0474e27b7cc3415e942e979259a63dfd":{
      "scriptId":"u48"},
    "6d05b18258cb4165b6c2a7c84bef3c35":{
      "scriptId":"u49"}}});