$axure.loadCurrentPage({
  "url":"入库管理.html",
  "generationDate":new Date(1443166045569.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"de20192fab7f4b549f57544b8de3a39c",
    "type":"Axure:Page",
    "name":"入库管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c9f2dcb094d4df2beede2f7a2b23079",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":960,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67bc409a342b4715b687ac51d615b69c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":960,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物品类别管理/u0.png"}},
{
          "id":"ce0a69b49cbd41b0b8691fe2f8fe89c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399CC},
            "size":{
              "width":960,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29db80e2b24945c9807140f998fc4c77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC},
                "size":{
                  "width":960,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物品类别管理/u2.png"}},
{
          "id":"25958367b45e4026a6e775dd15b415b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":111},
            "size":{
              "width":944,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"644ad7abe41443d0ab41a8bced689be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":111},
                "size":{
                  "width":944,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物品类别管理/u4.png"}},
{
          "id":"0ff9155a49ab4e62812e620cb0e78083",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":9,
              "y":111},
            "size":{
              "width":944,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b762d7201744229aa2a1ec0b9e47f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":9,
                  "y":111},
                "size":{
                  "width":944,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物品类别管理/u6.png"}},
{
          "id":"7d47fe20cfaf42ffb4626dc207c0b41f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":64},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0921ceb4d848fe926b5174a70448f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":64},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"659ecd92094f40439cf864841941c88b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":63},
            "size":{
              "width":50,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"95a295ec73e441fbbe6b8f1079916851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":24,
              "y":120},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1a86554189e4f3e8e2969a0b81e7445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":24,
                  "y":120},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"661fbf9266fc4733b4ea975f791c1c2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":68,
              "y":120},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6bd4d97c56b47da953126fe65221eec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":120},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f003ece4442d4802905d38b2e97c322e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":170,
              "y":120},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33bb91805e78452d9201a7d838e84308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":120},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0e51f15519e4a4cb7418ae66beccac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":156},
            "size":{
              "width":8,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228ca9beaa38483daa830d67ad97c155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":156},
                "size":{
                  "width":8,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e918fb5e68a74e05a5ede08ab223393d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":156},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241e26b6fefc4a3ea75f30a3e88757f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":156},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b71be88f0d3547ccb11ad7af17ec358c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":156},
            "size":{
              "width":65,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d71643973e4feebcfbc766ceef3ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":156},
                "size":{
                  "width":65,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"580c296731f0418c9369ef70aa1c3c6c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":171},
            "size":{
              "width":935,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库管理/u23_line.png"}},
{
          "id":"70b361fe43eb463aa2dbe9082f232173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":181},
            "size":{
              "width":7,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e73e336df3a41dfbd20859accec6217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":181},
                "size":{
                  "width":7,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a730f954244d3db5f6213c400cfeb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceba0f98646a4322bd3bfe85a707e946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":181},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fde0455ab1b496e8e3c9cd4de7086ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":181},
            "size":{
              "width":65,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78663d5d1d0f49579db11b8168f0963d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":181},
                "size":{
                  "width":65,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0b4c4f097f649bf912ba36d530759ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":196},
            "size":{
              "width":935,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/入库管理/u23_line.png"}},
{
          "id":"ad2dfa4b9a5a4e41930d3b24f39ef70e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":62},
            "size":{
              "width":123,
              "height":17}},
          "adaptiveStyles":{
}},
{
          "id":"469a026fa2ad4402ba8649882a168815",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":276,
              "y":120},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f883cb8274254c5a8b284fc308005fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":120},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb94ff968fe6428b864cbae773235304",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":673,
              "y":151},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae628b4ddc24204b9d6860d24ad9378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":673,
                  "y":151},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7af0ce7257a54644b63b21548df22550",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":673,
              "y":181},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43fd40d3a1d847d093f257ab408eded0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":673,
                  "y":181},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f38e244e21914681ad15b7df5aa4a053",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":155},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7347aefc266b4522a53307e0e861b041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":155},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c30c32d4e8a45d197f7b047f3c75d1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":180},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25990dbdad3f4f86a5d48adc721a2f25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":180},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4bef84c0acf4e828fd141737b08dc2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":673,
              "y":213},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5f27b7a6ce409791ea0ea09722ebea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":673,
                  "y":213},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1cde8f7acc4024aa48dee1d89efdfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":673,
              "y":239},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fadf27c184744ec78fdd84051a1a7714",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":673,
                  "y":239},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16d73819f50745e4af136a97848162a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":64},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f7002a215c4704ab4649706719ba9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":64},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80b3b322946740fab6fc867c3f3f7c10",
          "label":"日期输入框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":342.5,
              "y":62},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"75d69705433b45f5b75a8156e0a91f8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":64},
            "size":{
              "width":22,
              "height":19},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580625efa71546e1b475075694d5538d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":64},
                "size":{
                  "width":22,
                  "height":19},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 日历 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["ed4c233cb30f4aba8c4cb9434c90a735"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单列表/u56.png"}},
{
          "id":"ed4c233cb30f4aba8c4cb9434c90a735",
          "label":"日历",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":426.5,
              "y":84},
            "size":{
              "width":208,
              "height":219},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"73d4f6d7d3964d838f05aca76595ea8a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8bc559c205064420b976b86650ef7780",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":1},
                    "size":{
                      "width":206,
                      "height":217},
                    "borderWidth":"2",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"501ce00e9e4b483f87166450eefc3116",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":1},
                        "size":{
                          "width":206,
                          "height":217},
                        "borderWidth":"2",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单列表/u59.png"}},
{
                  "id":"9e941d6c070549c7a5a5ba6f4ad97f7b",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":4,
                      "y":9},
                    "size":{
                      "width":200,
                      "height":203},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68932570d0f74d8f833481a5b974b555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":4,
                          "y":9},
                        "size":{
                          "width":200,
                          "height":203},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单列表/u61.png"}},
{
                  "id":"09117a12dfbb4423996a4a5d52838de5",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":91,
                      "y":122},
                    "size":{
                      "width":25,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 日期输入框 = &quot;2011-8-24&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["80b3b322946740fab6fc867c3f3f7c10"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"2011-8-24",
                                        "stos":[]}]}]}},
{
                              "action":"fadeWidget",
                              "description":"隐藏 日历 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["ed4c233cb30f4aba8c4cb9434c90a735"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"3848b709ab434647a6b63b732e9f3e04",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":191},
                    "size":{
                      "width":50,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 日期输入框 = &quot;&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["80b3b322946740fab6fc867c3f3f7c10"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true},
{
                  "id":"72ad5b05c342450390ba10d2ba47cbdc",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":147,
                      "y":191},
                    "size":{
                      "width":50,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 日历 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["ed4c233cb30f4aba8c4cb9434c90a735"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"cb75bb6f23e242abb439662a1fbe2932",
                  "label":"",
                  "parentDynamicPanel":"ed4c233cb30f4aba8c4cb9434c90a735",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":69,
                      "y":191},
                    "size":{
                      "width":69,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 日期输入框 = &quot;[[Year]]-[[Month]]-[[Day]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["80b3b322946740fab6fc867c3f3f7c10"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[Year]]-[[Month]]-[[Day]]",
                                        "localVariables":{
},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"year"},
{
                                            "sto":"var",
                                            "name":"month"},
{
                                            "sto":"var",
                                            "name":"day"}]}]}]}},
{
                              "action":"fadeWidget",
                              "description":"隐藏 日历 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["ed4c233cb30f4aba8c4cb9434c90a735"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"4e83b608ba6b46638e9b6434aafca58e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":62},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 物品入库",
                      "objectsToFades":[{
                          "objectPath":["9b0dcef7fa9343b2b835838cbd5b671a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"59a8f35a221e43f295e7a3edfcaef55c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":753,
              "y":151},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b357c185d56c4675ae75d6309cf039bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":753,
                  "y":151},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b0dcef7fa9343b2b835838cbd5b671a",
          "label":"物品入库",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":190,
              "y":72},
            "size":{
              "width":600,
              "height":388},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"63396c24d6b443bb9011d86e453aa179",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9e04a93f328d4ca48f78c481f1a03ba7",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":0,
                      "y":-16},
                    "size":{
                      "width":600,
                      "height":390}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9d2ef1a8f9114ec7929bea7ceec70f56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":0,
                          "y":-16},
                        "size":{
                          "width":600,
                          "height":390}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/入库管理/u64.png"}},
{
                  "id":"cecae3e1743c4fccaf9ea50abf2e5b6f",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":600,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc7bce568638494e882a25c2ee293ca5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "size":{
                          "width":600,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/入库管理/u66.png"}},
{
                  "id":"c1012f12ca3f4208ba96d40d84873353",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099CC,
                      "opacity":1},
                    "location":{
                      "x":254,
                      "y":41},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71beb4452d9144bea651ced5e9aa910a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099CC,
                          "opacity":1},
                        "location":{
                          "x":254,
                          "y":41},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"55d8be6d8e2b4584beaf490f2e572d79",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":127,
                      "y":162},
                    "size":{
                      "width":373,
                      "height":124}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b352f091aff4b828ed12d963791eb87",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF33CCCC},
                        "size":{
                          "width":187,
                          "height":28}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"75b0834f568e4bc7be8793febd5d535c",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF33CCCC},
                            "size":{
                              "width":187,
                              "height":28}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u71.png"}},
{
                      "id":"cde7d3640b8c4ab6890a3bfb3d26dc6f",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":28},
                        "size":{
                          "width":187,
                          "height":28}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"61db12a0b44f4d5286c5ac10d147c6b9",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":28},
                            "size":{
                              "width":187,
                              "height":28}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u75.png"}},
{
                      "id":"e8f9ff72a1854d92b2df494a40d31c2b",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":56},
                        "size":{
                          "width":187,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d5f788da24bd49d385ba4c7f3df5530a",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":56},
                            "size":{
                              "width":187,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u79.png"}},
{
                      "id":"68d8ecccc8fa4e3787cc8eefc30c6c84",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF33CCCC},
                        "location":{
                          "x":187,
                          "y":0},
                        "size":{
                          "width":186,
                          "height":28}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f6fb9f42cd974aec87a0b1c050d06c0d",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF33CCCC},
                            "location":{
                              "x":187,
                              "y":0},
                            "size":{
                              "width":186,
                              "height":28}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u73.png"}},
{
                      "id":"8706f44ad5da4cc89597bb2abc68ca6c",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":187,
                          "y":28},
                        "size":{
                          "width":186,
                          "height":28}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3035a76c57014c8a86184678b0d9ca0b",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":187,
                              "y":28},
                            "size":{
                              "width":186,
                              "height":28}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u77.png"}},
{
                      "id":"22d4b6565ce84a40b24699f3ba1c36cc",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":187,
                          "y":56},
                        "size":{
                          "width":186,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"25e79f643b1f431099916c52ed66a91b",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":187,
                              "y":56},
                            "size":{
                              "width":186,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u81.png"}},
{
                      "id":"33e4aa8f1b5e4283b67410558ece875d",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":187,
                          "height":32}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8aefd58762bb4d89af3ad2ab6613286e",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":92},
                            "size":{
                              "width":187,
                              "height":32}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u83.png"}},
{
                      "id":"d618445d49db4de49e7b1a9bd775dca0",
                      "label":"",
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":187,
                          "y":92},
                        "size":{
                          "width":186,
                          "height":32}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"fff7bc8fc6fc41ea8d70ad6f2902d57e",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":187,
                              "y":92},
                            "size":{
                              "width":186,
                              "height":32}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/入库管理/u85.png"}}]},
{
                  "id":"03c24809f8bd4e57a1ecd4cb63488a7f",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":128},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c710cedd70844ccba6caa53d35c32a38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63,
                          "y":128},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ec95d6de91384f37826ea22e1219b2a2",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":325},
                    "size":{
                      "width":60,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 物品入库",
                              "objectsToFades":[{
                                  "objectPath":["9b0dcef7fa9343b2b835838cbd5b671a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"8e268234672141cab7c47cce12c25bee",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":350,
                      "y":325},
                    "size":{
                      "width":60,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"c0b598a2ee89489992a2e9d2336d64df",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":195},
                    "size":{
                      "width":120,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"ba325f0bb4cc4bd790491466cb489c06",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":98},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"061badf411ed450db548d132b4d183a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":100,
                          "y":98},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a5f7ff133614299be565aa4dd51260c",
                  "label":"",
                  "parentDynamicPanel":"9b0dcef7fa9343b2b835838cbd5b671a",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":153,
                      "y":98},
                    "size":{
                      "width":120,
                      "height":22}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "4c9f2dcb094d4df2beede2f7a2b23079":{
      "scriptId":"u0"},
    "67bc409a342b4715b687ac51d615b69c":{
      "scriptId":"u1"},
    "ce0a69b49cbd41b0b8691fe2f8fe89c9":{
      "scriptId":"u2"},
    "29db80e2b24945c9807140f998fc4c77":{
      "scriptId":"u3"},
    "25958367b45e4026a6e775dd15b415b0":{
      "scriptId":"u4"},
    "644ad7abe41443d0ab41a8bced689be3":{
      "scriptId":"u5"},
    "0ff9155a49ab4e62812e620cb0e78083":{
      "scriptId":"u6"},
    "4b762d7201744229aa2a1ec0b9e47f3a":{
      "scriptId":"u7"},
    "7d47fe20cfaf42ffb4626dc207c0b41f":{
      "scriptId":"u8"},
    "7b0921ceb4d848fe926b5174a70448f3":{
      "scriptId":"u9"},
    "659ecd92094f40439cf864841941c88b":{
      "scriptId":"u10"},
    "95a295ec73e441fbbe6b8f1079916851":{
      "scriptId":"u11"},
    "b1a86554189e4f3e8e2969a0b81e7445":{
      "scriptId":"u12"},
    "661fbf9266fc4733b4ea975f791c1c2f":{
      "scriptId":"u13"},
    "f6bd4d97c56b47da953126fe65221eec":{
      "scriptId":"u14"},
    "f003ece4442d4802905d38b2e97c322e":{
      "scriptId":"u15"},
    "33bb91805e78452d9201a7d838e84308":{
      "scriptId":"u16"},
    "b0e51f15519e4a4cb7418ae66beccac6":{
      "scriptId":"u17"},
    "228ca9beaa38483daa830d67ad97c155":{
      "scriptId":"u18"},
    "e918fb5e68a74e05a5ede08ab223393d":{
      "scriptId":"u19"},
    "241e26b6fefc4a3ea75f30a3e88757f9":{
      "scriptId":"u20"},
    "b71be88f0d3547ccb11ad7af17ec358c":{
      "scriptId":"u21"},
    "b5d71643973e4feebcfbc766ceef3ed9":{
      "scriptId":"u22"},
    "580c296731f0418c9369ef70aa1c3c6c":{
      "scriptId":"u23"},
    "70b361fe43eb463aa2dbe9082f232173":{
      "scriptId":"u24"},
    "6e73e336df3a41dfbd20859accec6217":{
      "scriptId":"u25"},
    "16a730f954244d3db5f6213c400cfeb5":{
      "scriptId":"u26"},
    "ceba0f98646a4322bd3bfe85a707e946":{
      "scriptId":"u27"},
    "8fde0455ab1b496e8e3c9cd4de7086ed":{
      "scriptId":"u28"},
    "78663d5d1d0f49579db11b8168f0963d":{
      "scriptId":"u29"},
    "e0b4c4f097f649bf912ba36d530759ce":{
      "scriptId":"u30"},
    "ad2dfa4b9a5a4e41930d3b24f39ef70e":{
      "scriptId":"u31"},
    "469a026fa2ad4402ba8649882a168815":{
      "scriptId":"u32"},
    "f883cb8274254c5a8b284fc308005fb1":{
      "scriptId":"u33"},
    "eb94ff968fe6428b864cbae773235304":{
      "scriptId":"u34"},
    "1ae628b4ddc24204b9d6860d24ad9378":{
      "scriptId":"u35"},
    "7af0ce7257a54644b63b21548df22550":{
      "scriptId":"u36"},
    "43fd40d3a1d847d093f257ab408eded0":{
      "scriptId":"u37"},
    "f38e244e21914681ad15b7df5aa4a053":{
      "scriptId":"u38"},
    "7347aefc266b4522a53307e0e861b041":{
      "scriptId":"u39"},
    "4c30c32d4e8a45d197f7b047f3c75d1c":{
      "scriptId":"u40"},
    "25990dbdad3f4f86a5d48adc721a2f25":{
      "scriptId":"u41"},
    "d4bef84c0acf4e828fd141737b08dc2d":{
      "scriptId":"u42"},
    "fe5f27b7a6ce409791ea0ea09722ebea":{
      "scriptId":"u43"},
    "0e1cde8f7acc4024aa48dee1d89efdfb":{
      "scriptId":"u44"},
    "fadf27c184744ec78fdd84051a1a7714":{
      "scriptId":"u45"},
    "16d73819f50745e4af136a97848162a6":{
      "scriptId":"u46"},
    "b8f7002a215c4704ab4649706719ba9a":{
      "scriptId":"u47"},
    "80b3b322946740fab6fc867c3f3f7c10":{
      "scriptId":"u48"},
    "75d69705433b45f5b75a8156e0a91f8c":{
      "scriptId":"u49"},
    "580625efa71546e1b475075694d5538d":{
      "scriptId":"u50"},
    "ed4c233cb30f4aba8c4cb9434c90a735":{
      "scriptId":"u51"},
    "8bc559c205064420b976b86650ef7780":{
      "scriptId":"u52"},
    "501ce00e9e4b483f87166450eefc3116":{
      "scriptId":"u53"},
    "9e941d6c070549c7a5a5ba6f4ad97f7b":{
      "scriptId":"u54"},
    "68932570d0f74d8f833481a5b974b555":{
      "scriptId":"u55"},
    "09117a12dfbb4423996a4a5d52838de5":{
      "scriptId":"u56"},
    "3848b709ab434647a6b63b732e9f3e04":{
      "scriptId":"u57"},
    "72ad5b05c342450390ba10d2ba47cbdc":{
      "scriptId":"u58"},
    "cb75bb6f23e242abb439662a1fbe2932":{
      "scriptId":"u59"},
    "4e83b608ba6b46638e9b6434aafca58e":{
      "scriptId":"u60"},
    "59a8f35a221e43f295e7a3edfcaef55c":{
      "scriptId":"u61"},
    "b357c185d56c4675ae75d6309cf039bb":{
      "scriptId":"u62"},
    "9b0dcef7fa9343b2b835838cbd5b671a":{
      "scriptId":"u63"},
    "9e04a93f328d4ca48f78c481f1a03ba7":{
      "scriptId":"u64"},
    "9d2ef1a8f9114ec7929bea7ceec70f56":{
      "scriptId":"u65"},
    "cecae3e1743c4fccaf9ea50abf2e5b6f":{
      "scriptId":"u66"},
    "dc7bce568638494e882a25c2ee293ca5":{
      "scriptId":"u67"},
    "c1012f12ca3f4208ba96d40d84873353":{
      "scriptId":"u68"},
    "71beb4452d9144bea651ced5e9aa910a":{
      "scriptId":"u69"},
    "55d8be6d8e2b4584beaf490f2e572d79":{
      "scriptId":"u70"},
    "8b352f091aff4b828ed12d963791eb87":{
      "scriptId":"u71"},
    "75b0834f568e4bc7be8793febd5d535c":{
      "scriptId":"u72"},
    "68d8ecccc8fa4e3787cc8eefc30c6c84":{
      "scriptId":"u73"},
    "f6fb9f42cd974aec87a0b1c050d06c0d":{
      "scriptId":"u74"},
    "cde7d3640b8c4ab6890a3bfb3d26dc6f":{
      "scriptId":"u75"},
    "61db12a0b44f4d5286c5ac10d147c6b9":{
      "scriptId":"u76"},
    "8706f44ad5da4cc89597bb2abc68ca6c":{
      "scriptId":"u77"},
    "3035a76c57014c8a86184678b0d9ca0b":{
      "scriptId":"u78"},
    "e8f9ff72a1854d92b2df494a40d31c2b":{
      "scriptId":"u79"},
    "d5f788da24bd49d385ba4c7f3df5530a":{
      "scriptId":"u80"},
    "22d4b6565ce84a40b24699f3ba1c36cc":{
      "scriptId":"u81"},
    "25e79f643b1f431099916c52ed66a91b":{
      "scriptId":"u82"},
    "33e4aa8f1b5e4283b67410558ece875d":{
      "scriptId":"u83"},
    "8aefd58762bb4d89af3ad2ab6613286e":{
      "scriptId":"u84"},
    "d618445d49db4de49e7b1a9bd775dca0":{
      "scriptId":"u85"},
    "fff7bc8fc6fc41ea8d70ad6f2902d57e":{
      "scriptId":"u86"},
    "03c24809f8bd4e57a1ecd4cb63488a7f":{
      "scriptId":"u87"},
    "c710cedd70844ccba6caa53d35c32a38":{
      "scriptId":"u88"},
    "ec95d6de91384f37826ea22e1219b2a2":{
      "scriptId":"u89"},
    "8e268234672141cab7c47cce12c25bee":{
      "scriptId":"u90"},
    "c0b598a2ee89489992a2e9d2336d64df":{
      "scriptId":"u91"},
    "ba325f0bb4cc4bd790491466cb489c06":{
      "scriptId":"u92"},
    "061badf411ed450db548d132b4d183a7":{
      "scriptId":"u93"},
    "5a5f7ff133614299be565aa4dd51260c":{
      "scriptId":"u94"}}});