$axure.loadCurrentPage({
  "url":"调拨入库.html",
  "generationDate":new Date(1443166048348.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"09be683f32014acd9448331401542d16",
    "type":"Axure:Page",
    "name":"调拨入库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91266b15fce14cbcb38af9b268908826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":960,
              "height":650}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582338b109824ba29540750fc2659d6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":960,
                  "height":650}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调拨入库/u0.png"}},
{
          "id":"2ec47d95c6b34da5ab20f55213603aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":960,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de260a042ad4c8e8834a7594719f36b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":960,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u87.png"}},
{
          "id":"4135b28d1cc248ac917f1818313a9399",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":421,
              "y":40},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57d49175000446e2a72f0ae738599fe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":421,
                  "y":40},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6a1d0c4f40d4ba780c57a7ee175e7eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":180},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbee945018024fc7aaa157209c658fbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":180},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2014ddfbd52944c487e7ff252fb3a19c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":170},
            "size":{
              "width":309,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"d538940d896549f3acc8dcfe5451b5c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":221},
            "size":{
              "width":720,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fc2daf9a8424afbabfaf6586514db12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":221},
                "size":{
                  "width":720,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u105.png"}},
{
          "id":"3fbd992c4b874cd980c98e00206decd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b2dad5a3ab4212b9337b0a25506660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6b8304f5136438e9893e503652d8818",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05200f7e54294654a6da278f378fe172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58be5635a48a447a89479dfb72fe4f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":240},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b2805e1cf44eb29ab4195249b0fd3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":240},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3ab9d53ee59482c8f2293abeacfacd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":282},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7de791ec2549348f8a6c4c5febb291",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":282},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6daf888ceb6d4979a9a8fd3722c8b0da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":282},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5977180e29044fe987e1b1dcfcf7249a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":282},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aed444c98e14d5cb8a1c6a6a088e6f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":330},
            "size":{
              "width":719,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e176c29a7f84a34a15a8513071a62b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":330},
                "size":{
                  "width":719,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/入库管理_1/u117.png"}},
{
          "id":"b2966c028b87497c99916149fa4bc5ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":374},
            "size":{
              "width":20,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc403462a74426bbaf19d260bbc670e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":374},
                "size":{
                  "width":20,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"c8d6a89bbd4546a2b3a87fa26d201f72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":402},
            "size":{
              "width":20,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521230df7d184194a1f9a5dadd0a25a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":683,
                  "y":402},
                "size":{
                  "width":20,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/仓库管理/u195.png"}},
{
          "id":"dd53b2b9811349e8bfdc1ced76825698",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":520},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提交后信息",
                      "objectsToFades":[{
                          "objectPath":["8c550b0c457b4d5da028512fe9aeecc2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"aa7a57bf28e04f53a0776905d2c74e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6699CC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":321,
              "y":610},
            "size":{
              "width":90,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5272ab4dc5b482db426b3b69615d17c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699CC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":321,
                  "y":610},
                "size":{
                  "width":90,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/出货单列表/u185.png",
            "selected~":"images/订单列表/u175_selected.png",
            "mouseOver~":"images/订单列表/u175_mouseOver.png",
            "mouseDown~":"images/订单列表/u175_selected.png"}},
{
          "id":"db3d3fda0c5f4eafb11020e81035f881",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6699CC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":500,
              "y":610},
            "size":{
              "width":90,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b3f25fa1324c198d63e1d40369daf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699CC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399CC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":500,
                  "y":610},
                "size":{
                  "width":90,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单列表/u185.png",
            "selected~":"images/订单列表/u175_selected.png",
            "mouseOver~":"images/订单列表/u175_mouseOver.png",
            "mouseDown~":"images/订单列表/u175_selected.png"}},
{
          "id":"8c550b0c457b4d5da028512fe9aeecc2",
          "label":"提交后信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":132,
              "y":330},
            "size":{
              "width":719,
              "height":240},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"db9a4f2a982f4b32a8a69ae8e8afd658",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f8159e2294884c45b0bf8a5b5ebca4f3",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-30,
                      "y":-10},
                    "size":{
                      "width":750,
                      "height":250}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db58dbf8bfaf4301a66a74e18ab452e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-30,
                          "y":-10},
                        "size":{
                          "width":750,
                          "height":250}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/入库管理_1/u177.png"}},
{
                  "id":"6c792e158be84e92a85ba7ee37521295",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":364,
                      "y":44},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c61360d0dfe3473ea97cacb3367e54e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":364,
                          "y":44},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b5eee1c5003946078c4a9461cdf92698",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":113,
                      "y":44},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dac0bef84d0f4b1cba981cf1fd278108",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":113,
                          "y":44},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fcd394c888d14bc89bc923e82c061dff",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":113,
                      "y":80},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd4659ec4ae2456f9dfd906281dfb9f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":113,
                          "y":80},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"09ea0212440840ef86eecfa75a08ffeb",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":364,
                      "y":80},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"876fb39a887f4fdfb2254c9aa7bf1ef8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":364,
                          "y":80},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f9afd9e2913490da17c5c648835fa88",
                  "label":"",
                  "parentDynamicPanel":"8c550b0c457b4d5da028512fe9aeecc2",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":636,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 提交后信息",
                              "objectsToFades":[{
                                  "objectPath":["8c550b0c457b4d5da028512fe9aeecc2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"e695d8038d674a40a5677c4c625bac3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":149,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fe0c097207944c39e5ef4ef0720ffba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":149,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0f61ce5896d45dbacdaf04174b369e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":220,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d99e2b0ec9437a9c74254621ee0e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"482b7c833fef49e1a6a72df46e753ad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":300,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd26a528e54a4d2686385becd02da7af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a726983f90874f4dadebcedd16db1966",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":370,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af135df6730443690d8c5f57065392c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":370,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9d79cef0da6400e91610865ec232394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":456,
              "y":344},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20e233d13ac3451380c3feae10edaa80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":456,
                  "y":344},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0830aea3b3d44e5a8f45a25016d77dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":501,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7a02ca41cf4f3bbdb72ef12fa28a07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":501,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"959702a79c5c4d4f8c9a6ff923688fda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":580,
              "y":344},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f023135de8341fe818359720e9cedab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":344},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79c3a5f6ba074d8bac964f4583f4ccc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":114},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b00e6430c34698b3d486c1567e816b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":114},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "91266b15fce14cbcb38af9b268908826":{
      "scriptId":"u0"},
    "582338b109824ba29540750fc2659d6a":{
      "scriptId":"u1"},
    "2ec47d95c6b34da5ab20f55213603aa6":{
      "scriptId":"u2"},
    "5de260a042ad4c8e8834a7594719f36b":{
      "scriptId":"u3"},
    "4135b28d1cc248ac917f1818313a9399":{
      "scriptId":"u4"},
    "57d49175000446e2a72f0ae738599fe5":{
      "scriptId":"u5"},
    "b6a1d0c4f40d4ba780c57a7ee175e7eb":{
      "scriptId":"u6"},
    "bbee945018024fc7aaa157209c658fbc":{
      "scriptId":"u7"},
    "2014ddfbd52944c487e7ff252fb3a19c":{
      "scriptId":"u8"},
    "d538940d896549f3acc8dcfe5451b5c9":{
      "scriptId":"u9"},
    "0fc2daf9a8424afbabfaf6586514db12":{
      "scriptId":"u10"},
    "3fbd992c4b874cd980c98e00206decd3":{
      "scriptId":"u11"},
    "d3b2dad5a3ab4212b9337b0a25506660":{
      "scriptId":"u12"},
    "a6b8304f5136438e9893e503652d8818":{
      "scriptId":"u13"},
    "05200f7e54294654a6da278f378fe172":{
      "scriptId":"u14"},
    "58be5635a48a447a89479dfb72fe4f56":{
      "scriptId":"u15"},
    "56b2805e1cf44eb29ab4195249b0fd3c":{
      "scriptId":"u16"},
    "d3ab9d53ee59482c8f2293abeacfacd6":{
      "scriptId":"u17"},
    "da7de791ec2549348f8a6c4c5febb291":{
      "scriptId":"u18"},
    "6daf888ceb6d4979a9a8fd3722c8b0da":{
      "scriptId":"u19"},
    "5977180e29044fe987e1b1dcfcf7249a":{
      "scriptId":"u20"},
    "1aed444c98e14d5cb8a1c6a6a088e6f2":{
      "scriptId":"u21"},
    "5e176c29a7f84a34a15a8513071a62b3":{
      "scriptId":"u22"},
    "b2966c028b87497c99916149fa4bc5ce":{
      "scriptId":"u23"},
    "3fc403462a74426bbaf19d260bbc670e":{
      "scriptId":"u24"},
    "c8d6a89bbd4546a2b3a87fa26d201f72":{
      "scriptId":"u25"},
    "521230df7d184194a1f9a5dadd0a25a0":{
      "scriptId":"u26"},
    "dd53b2b9811349e8bfdc1ced76825698":{
      "scriptId":"u27"},
    "aa7a57bf28e04f53a0776905d2c74e82":{
      "scriptId":"u28"},
    "e5272ab4dc5b482db426b3b69615d17c":{
      "scriptId":"u29"},
    "db3d3fda0c5f4eafb11020e81035f881":{
      "scriptId":"u30"},
    "36b3f25fa1324c198d63e1d40369daf4":{
      "scriptId":"u31"},
    "8c550b0c457b4d5da028512fe9aeecc2":{
      "scriptId":"u32"},
    "f8159e2294884c45b0bf8a5b5ebca4f3":{
      "scriptId":"u33"},
    "db58dbf8bfaf4301a66a74e18ab452e7":{
      "scriptId":"u34"},
    "6c792e158be84e92a85ba7ee37521295":{
      "scriptId":"u35"},
    "c61360d0dfe3473ea97cacb3367e54e7":{
      "scriptId":"u36"},
    "b5eee1c5003946078c4a9461cdf92698":{
      "scriptId":"u37"},
    "dac0bef84d0f4b1cba981cf1fd278108":{
      "scriptId":"u38"},
    "fcd394c888d14bc89bc923e82c061dff":{
      "scriptId":"u39"},
    "bd4659ec4ae2456f9dfd906281dfb9f0":{
      "scriptId":"u40"},
    "09ea0212440840ef86eecfa75a08ffeb":{
      "scriptId":"u41"},
    "876fb39a887f4fdfb2254c9aa7bf1ef8":{
      "scriptId":"u42"},
    "9f9afd9e2913490da17c5c648835fa88":{
      "scriptId":"u43"},
    "e695d8038d674a40a5677c4c625bac3d":{
      "scriptId":"u44"},
    "1fe0c097207944c39e5ef4ef0720ffba":{
      "scriptId":"u45"},
    "c0f61ce5896d45dbacdaf04174b369e6":{
      "scriptId":"u46"},
    "47d99e2b0ec9437a9c74254621ee0e6e":{
      "scriptId":"u47"},
    "482b7c833fef49e1a6a72df46e753ad2":{
      "scriptId":"u48"},
    "dd26a528e54a4d2686385becd02da7af":{
      "scriptId":"u49"},
    "a726983f90874f4dadebcedd16db1966":{
      "scriptId":"u50"},
    "8af135df6730443690d8c5f57065392c":{
      "scriptId":"u51"},
    "d9d79cef0da6400e91610865ec232394":{
      "scriptId":"u52"},
    "20e233d13ac3451380c3feae10edaa80":{
      "scriptId":"u53"},
    "0830aea3b3d44e5a8f45a25016d77dc5":{
      "scriptId":"u54"},
    "9f7a02ca41cf4f3bbdb72ef12fa28a07":{
      "scriptId":"u55"},
    "959702a79c5c4d4f8c9a6ff923688fda":{
      "scriptId":"u56"},
    "6f023135de8341fe818359720e9cedab":{
      "scriptId":"u57"},
    "79c3a5f6ba074d8bac964f4583f4ccc0":{
      "scriptId":"u58"},
    "87b00e6430c34698b3d486c1567e816b":{
      "scriptId":"u59"}}});