$axure.loadCurrentPage({
  "url":"兑奖.html",
  "generationDate":new Date(1442224859182.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f55850cfe9cd42ba80fa0cb5e9be6dd6",
    "type":"Axure:Page",
    "name":"兑奖",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6dc41059eb894180941d64840451749d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":20},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92310d378fe34dc8b71abe503b12b0b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":20},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"f3662d96a9e341d695ebd2489907911a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":74,
              "y":66},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"930d2f9004eb46b49e9d39472f62f296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":74,
                  "y":66},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"3e7bb956f7ea4dd5b2a6bd9789057417",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":71},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71d4e4afe1e47c0abcc814336a272d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":71},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"e0ca02051a02430b8fd9608c0c31ae2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":321,
              "y":71},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1baa0334534f4808bfa43609cfcb86d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":321,
                  "y":71},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"37886e1ddb094802a41ebea11cb28c2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":71},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"052aa35b3ba84b2e9ae3e96bc489fe89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":71},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"a062753bd25c4f7bba63c99e49ffbe96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":303,
              "y":74},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3aa230b13b04fe681e9fec4b9865b57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":303,
                  "y":74},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"505edc655b6f4addadf50b424688eed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":74,
              "y":88},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993adb1d57804827beca7281f6fef967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":74,
                  "y":88},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"0933fa81629441509687e415ff458b86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":92},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946c9ec0fe5b4541981ea66608706df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":92},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"5df8a9b036b04dd6bb91ca0bac49c0f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":91},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb3657fb2094236ab9b7f1c17de1d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":91},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"9cb7168a00fd410fb82f0b28929d5a90",
          "label":"搜索框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":105,
              "y":181},
            "size":{
              "width":217,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 中奖等级",
                      "objectsToFades":[{
                          "objectPath":["09a5079f7c50448c8907cdc5c1940aed"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "placeholderText":"请输入登录账号"},
{
          "id":"7066fb6d9d8d4bf7a9bae4614d72ef38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":156},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b122fbacfe104e3a889242b32f76494e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":105,
                  "y":156},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09a5079f7c50448c8907cdc5c1940aed",
          "label":"中奖等级",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":74,
              "y":220},
            "size":{
              "width":267,
              "height":260},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8109bdeced084f0abb68407128c2e2dd",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"14e70086c24f4344adff42dc771b5f56",
                  "label":"",
                  "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":16},
                    "size":{
                      "width":105,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a69a48f9d1b4bafa8efcb4df6a6158f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":16},
                        "size":{
                          "width":105,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"75ea58e6899e4c5fb70b2001aaf256f7",
                  "label":"",
                  "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29,
                      "y":44},
                    "size":{
                      "width":131,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b81546daa9741239b4a4a5ad18ae980",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":29,
                          "y":44},
                        "size":{
                          "width":131,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"775a9d54bcfa4de8aabba936bd695e98",
                  "label":"",
                  "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":29,
                      "y":190},
                    "size":{
                      "width":84,
                      "height":23},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00cdac80dba14041bb8d4c05e356df94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":29,
                          "y":190},
                        "size":{
                          "width":84,
                          "height":23},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑奖页面/u45.png"}},
{
                  "id":"0bdd3e5192f2403f8b49d15a919658c9",
                  "label":"",
                  "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":154,
                      "y":190},
                    "size":{
                      "width":84,
                      "height":23},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"10"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d8fb06ab2cc4539aa1dbee75988abec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"09a5079f7c50448c8907cdc5c1940aed",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":154,
                          "y":190},
                        "size":{
                          "width":84,
                          "height":23},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"10"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑奖页面/u45.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "6dc41059eb894180941d64840451749d":{
      "scriptId":"u0"},
    "92310d378fe34dc8b71abe503b12b0b8":{
      "scriptId":"u1"},
    "f3662d96a9e341d695ebd2489907911a":{
      "scriptId":"u2"},
    "930d2f9004eb46b49e9d39472f62f296":{
      "scriptId":"u3"},
    "3e7bb956f7ea4dd5b2a6bd9789057417":{
      "scriptId":"u4"},
    "c71d4e4afe1e47c0abcc814336a272d0":{
      "scriptId":"u5"},
    "e0ca02051a02430b8fd9608c0c31ae2b":{
      "scriptId":"u6"},
    "1baa0334534f4808bfa43609cfcb86d0":{
      "scriptId":"u7"},
    "37886e1ddb094802a41ebea11cb28c2c":{
      "scriptId":"u8"},
    "052aa35b3ba84b2e9ae3e96bc489fe89":{
      "scriptId":"u9"},
    "a062753bd25c4f7bba63c99e49ffbe96":{
      "scriptId":"u10"},
    "c3aa230b13b04fe681e9fec4b9865b57":{
      "scriptId":"u11"},
    "505edc655b6f4addadf50b424688eed1":{
      "scriptId":"u12"},
    "993adb1d57804827beca7281f6fef967":{
      "scriptId":"u13"},
    "0933fa81629441509687e415ff458b86":{
      "scriptId":"u14"},
    "946c9ec0fe5b4541981ea66608706df1":{
      "scriptId":"u15"},
    "5df8a9b036b04dd6bb91ca0bac49c0f3":{
      "scriptId":"u16"},
    "efb3657fb2094236ab9b7f1c17de1d26":{
      "scriptId":"u17"},
    "9cb7168a00fd410fb82f0b28929d5a90":{
      "scriptId":"u18"},
    "7066fb6d9d8d4bf7a9bae4614d72ef38":{
      "scriptId":"u19"},
    "b122fbacfe104e3a889242b32f76494e":{
      "scriptId":"u20"},
    "09a5079f7c50448c8907cdc5c1940aed":{
      "scriptId":"u21"},
    "14e70086c24f4344adff42dc771b5f56":{
      "scriptId":"u22"},
    "7a69a48f9d1b4bafa8efcb4df6a6158f":{
      "scriptId":"u23"},
    "75ea58e6899e4c5fb70b2001aaf256f7":{
      "scriptId":"u24"},
    "2b81546daa9741239b4a4a5ad18ae980":{
      "scriptId":"u25"},
    "775a9d54bcfa4de8aabba936bd695e98":{
      "scriptId":"u26"},
    "00cdac80dba14041bb8d4c05e356df94":{
      "scriptId":"u27"},
    "0bdd3e5192f2403f8b49d15a919658c9":{
      "scriptId":"u28"},
    "1d8fb06ab2cc4539aa1dbee75988abec":{
      "scriptId":"u29"}}});