$axure.loadCurrentPage({
  "url":"充值.html",
  "generationDate":new Date(1443166056132.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"46bad6a8aa964936ac62bc802e7375a9",
    "type":"Axure:Page",
    "name":"充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cbff22fde4dd460182cb7748b431f56f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":520,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1309902a3345998d8837ac1c16c25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"296cad773ca44e11946fa8cb86cfa396",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":520,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c80eb4116ed446191e58d4694193811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":520,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"4b7c24adb1484f7b959f3abb58de8bfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":126},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5d7024faa6436d853f349f59c92293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":126},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9880671fa9c14d40b875ae01f50ff02d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":223},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7559691a9c430fb91f58a023ee700d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":223},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b583f326f26449ca91664072b9bc56f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":175},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f688b855eb774401ac12be4affd95a1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":175},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"242052135e9d40a99d4551472fdc3de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":268},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb3be2dfa4bf444da78c5557e6c55e36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":268},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"600a171035fd4bf781182a8640d8389a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":370},
            "size":{
              "width":88,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc04775751da47438f2bf00641729432",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":370},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ae0f32433b35413ca29ae7c7bb28f0e2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":220},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6160658bd6304a168544deec39b87064",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":175},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"176e90906e564f35b4177f98315de906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":175},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"118f2fb92174435e99287c7b89bf70fc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":265},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c68e1d17e77d44888379caa28173854d",
          "label":"充值凭证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":159,
              "y":194},
            "size":{
              "width":351,
              "height":166},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"27c74d7a70444dcea11b56eb66a4b774",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c80d01d82b814959b4c31db34ca76889",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":340,
                      "height":160}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"063400f25cd74de89fbca3b042209ef8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":340,
                          "height":160}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u19.png"}},
{
                  "id":"47a4b8d97c1f4c9db20c4fc406159c77",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":340,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec42df2d3aa24655acd8e7b8e0d42fdb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF009DD9},
                        "size":{
                          "width":340,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u21.png"}},
{
                  "id":"b9692904812b4ac78e6b13ba735975f8",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":40},
                    "size":{
                      "width":14,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"190f1709b53a4ee7935064a30a96c269",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":40},
                        "size":{
                          "width":14,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b55f5d342a4c489294e48c7a316e4470",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":110,
                      "y":56},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5d6ae70ba6044aa9b798fa4a7fdf907",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":110,
                          "y":56},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"88f0f322c31640d0b265d5746ca97bb2",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":73,
                      "y":110},
                    "size":{
                      "width":97,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"a2400687c49041b2b87f87de53111ae6",
                  "label":"",
                  "parentDynamicPanel":"c68e1d17e77d44888379caa28173854d",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":110},
                    "size":{
                      "width":60,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 充值凭证",
                              "objectsToFades":[{
                                  "objectPath":["c68e1d17e77d44888379caa28173854d"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"5c0e033bb0264ac68dfc26e473e4eb03",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":51},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"10f9f88d7cb645c39937ffa6e1199259",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":54},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddaa940733914a6cb29e546fb90e75cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":54},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e304338ef88408a94937c7c3abf7f91",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":124},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"38de56123e1e4b79a96d39e300d69043",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":0},
            "size":{
              "width":440,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f383ebcabb734270abb22a516dfd924f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":0},
                "size":{
                  "width":440,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现审批/u95.png"}},
{
          "id":"be9a48ac248c4b86b60838aeea92e563",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":41},
            "size":{
              "width":420,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/提现审批/u97_line.png"}},
{
          "id":"5387be0c26624de18725f13853717784",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":782,
              "y":17},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc9999b9fb9a40a198404ea3fdc7f50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":782,
                  "y":17},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"357bdf0bbd8b4a1ea3756075b31102de",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":82},
            "size":{
              "width":400,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32eff9500f174c5cb943b2e6d43690a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abdd12730ddf43b68aa3f79870671623",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"28e8772ca8de454a9fa94139dc6500c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a40ba7ba0efb4f95965719f90314b9b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"981df23279c9493891f39d8e4af701b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25cd148a10ec41d6b64102ef64c29cb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"282d4d325b624a51b47285f78813d76b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e299cda5cbaa48748ce03d0a1209a019",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"36b2d2538ad8402db07ce0a1bfa9ca20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41fcc26b9fd648509004f2aed7d48912",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"0c55f2d5ef6f4da4bf90310437cfd8ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a0d81879318460796ec3fbcd4a981be",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"1c9ef5b6b4244737a24b6d12ceaace45",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5d7517fa0484bdda060df4fc8546040",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"2382110baed841cbafe4a014e1000882",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0524b30ac71941b4ae457af9ef64b5a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/站点管理/u131.png"}},
{
              "id":"7b0e5cb8394d4758852787a500db1a7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0021b75d8c064876853ef134043f3c1f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u117.png"}},
{
              "id":"5f058dfa7dd946e898a6043e9c37930f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abe37242524a47eaa9bf2a5468a65bfa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u107.png"}},
{
              "id":"a294bc449eb44129953dd3a09c65c886",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab0dee043b28475abf05ebc433962e5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u107.png"}},
{
              "id":"b75cb6b4fd6c4c149ad0454419cc2210",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f0dfa70ba914ca4823e46e731f3b2ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/提现审批/u123.png"}}]},
{
          "id":"8bed6962e68b4f2e8006e30ce5fed41a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":634,
              "y":57},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba804ccf56e142c2b964416a366a4603",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":634,
                  "y":57},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cbff22fde4dd460182cb7748b431f56f":{
      "scriptId":"u0"},
    "5f1309902a3345998d8837ac1c16c25a":{
      "scriptId":"u1"},
    "296cad773ca44e11946fa8cb86cfa396":{
      "scriptId":"u2"},
    "5c80eb4116ed446191e58d4694193811":{
      "scriptId":"u3"},
    "4b7c24adb1484f7b959f3abb58de8bfe":{
      "scriptId":"u4"},
    "0e5d7024faa6436d853f349f59c92293":{
      "scriptId":"u5"},
    "9880671fa9c14d40b875ae01f50ff02d":{
      "scriptId":"u6"},
    "8d7559691a9c430fb91f58a023ee700d":{
      "scriptId":"u7"},
    "5b583f326f26449ca91664072b9bc56f":{
      "scriptId":"u8"},
    "f688b855eb774401ac12be4affd95a1b":{
      "scriptId":"u9"},
    "242052135e9d40a99d4551472fdc3de0":{
      "scriptId":"u10"},
    "bb3be2dfa4bf444da78c5557e6c55e36":{
      "scriptId":"u11"},
    "600a171035fd4bf781182a8640d8389a":{
      "scriptId":"u12"},
    "dc04775751da47438f2bf00641729432":{
      "scriptId":"u13"},
    "ae0f32433b35413ca29ae7c7bb28f0e2":{
      "scriptId":"u14"},
    "6160658bd6304a168544deec39b87064":{
      "scriptId":"u15"},
    "176e90906e564f35b4177f98315de906":{
      "scriptId":"u16"},
    "118f2fb92174435e99287c7b89bf70fc":{
      "scriptId":"u17"},
    "c68e1d17e77d44888379caa28173854d":{
      "scriptId":"u18"},
    "c80d01d82b814959b4c31db34ca76889":{
      "scriptId":"u19"},
    "063400f25cd74de89fbca3b042209ef8":{
      "scriptId":"u20"},
    "47a4b8d97c1f4c9db20c4fc406159c77":{
      "scriptId":"u21"},
    "ec42df2d3aa24655acd8e7b8e0d42fdb":{
      "scriptId":"u22"},
    "b9692904812b4ac78e6b13ba735975f8":{
      "scriptId":"u23"},
    "190f1709b53a4ee7935064a30a96c269":{
      "scriptId":"u24"},
    "b55f5d342a4c489294e48c7a316e4470":{
      "scriptId":"u25"},
    "e5d6ae70ba6044aa9b798fa4a7fdf907":{
      "scriptId":"u26"},
    "88f0f322c31640d0b265d5746ca97bb2":{
      "scriptId":"u27"},
    "a2400687c49041b2b87f87de53111ae6":{
      "scriptId":"u28"},
    "5c0e033bb0264ac68dfc26e473e4eb03":{
      "scriptId":"u29"},
    "10f9f88d7cb645c39937ffa6e1199259":{
      "scriptId":"u30"},
    "ddaa940733914a6cb29e546fb90e75cc":{
      "scriptId":"u31"},
    "0e304338ef88408a94937c7c3abf7f91":{
      "scriptId":"u32"},
    "38de56123e1e4b79a96d39e300d69043":{
      "scriptId":"u33"},
    "f383ebcabb734270abb22a516dfd924f":{
      "scriptId":"u34"},
    "be9a48ac248c4b86b60838aeea92e563":{
      "scriptId":"u35"},
    "5387be0c26624de18725f13853717784":{
      "scriptId":"u36"},
    "fc9999b9fb9a40a198404ea3fdc7f50c":{
      "scriptId":"u37"},
    "357bdf0bbd8b4a1ea3756075b31102de":{
      "scriptId":"u38"},
    "32eff9500f174c5cb943b2e6d43690a6":{
      "scriptId":"u39"},
    "abdd12730ddf43b68aa3f79870671623":{
      "scriptId":"u40"},
    "282d4d325b624a51b47285f78813d76b":{
      "scriptId":"u41"},
    "e299cda5cbaa48748ce03d0a1209a019":{
      "scriptId":"u42"},
    "1c9ef5b6b4244737a24b6d12ceaace45":{
      "scriptId":"u43"},
    "d5d7517fa0484bdda060df4fc8546040":{
      "scriptId":"u44"},
    "5f058dfa7dd946e898a6043e9c37930f":{
      "scriptId":"u45"},
    "abe37242524a47eaa9bf2a5468a65bfa":{
      "scriptId":"u46"},
    "28e8772ca8de454a9fa94139dc6500c6":{
      "scriptId":"u47"},
    "a40ba7ba0efb4f95965719f90314b9b1":{
      "scriptId":"u48"},
    "36b2d2538ad8402db07ce0a1bfa9ca20":{
      "scriptId":"u49"},
    "41fcc26b9fd648509004f2aed7d48912":{
      "scriptId":"u50"},
    "2382110baed841cbafe4a014e1000882":{
      "scriptId":"u51"},
    "0524b30ac71941b4ae457af9ef64b5a6":{
      "scriptId":"u52"},
    "a294bc449eb44129953dd3a09c65c886":{
      "scriptId":"u53"},
    "ab0dee043b28475abf05ebc433962e5c":{
      "scriptId":"u54"},
    "981df23279c9493891f39d8e4af701b4":{
      "scriptId":"u55"},
    "25cd148a10ec41d6b64102ef64c29cb1":{
      "scriptId":"u56"},
    "0c55f2d5ef6f4da4bf90310437cfd8ab":{
      "scriptId":"u57"},
    "4a0d81879318460796ec3fbcd4a981be":{
      "scriptId":"u58"},
    "7b0e5cb8394d4758852787a500db1a7e":{
      "scriptId":"u59"},
    "0021b75d8c064876853ef134043f3c1f":{
      "scriptId":"u60"},
    "b75cb6b4fd6c4c149ad0454419cc2210":{
      "scriptId":"u61"},
    "5f0dfa70ba914ca4823e46e731f3b2ec":{
      "scriptId":"u62"},
    "8bed6962e68b4f2e8006e30ce5fed41a":{
      "scriptId":"u63"},
    "ba804ccf56e142c2b964416a366a4603":{
      "scriptId":"u64"}}});