/****************************************************/
/****************  修改说明  ************************/
-- created by 陈震 @ 2015/9/8
--       新增超级用户
/***************************************************/

insert into adm_info (admin_id, admin_realname, admin_login, admin_password, admin_gender, admin_email, admin_birthday, admin_org, admin_address)
values (0, 'Super Administrator', 'super', '96e79218965eb72c92a549dd5a330112', 1, null, sysdate, '00', 'address');
insert into adm_info (admin_id, admin_realname, admin_login, admin_password, admin_gender, admin_email, admin_birthday, admin_org, admin_address)
values (1, 'Administrator', 'admin', '96e79218965eb72c92a549dd5a330112', 1, null, sysdate, '00', 'address');

insert into adm_role_admin(admin_id, role_id) values(0, 0);
insert into adm_role_admin(admin_id, role_id) values(1, 1);

insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (0, 'super', 1, '超级管理员', 'super');
select  f_get_adm_id_seq() from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (1, 'admin', 1, '系统管理员', 'admin');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (2, 'warehouseManager', 1, '仓库管理员', 'warehouseManager');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (3, 'marketManager', 1, '市场管理员', 'marketManager');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (4, 'payoutManager', 1, '兑奖员', 'payoutManager');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (5, 'fundManager', 1, '财务人员', 'fundManager');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (6, 'leader', 1, '部门经理', 'leader');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (7, 'headquarter', 1, '总部管理人员', 'headquarter');
select f_get_adm_id_seq from dual;
insert into adm_role (role_id, role_name, is_active, role_comment, role_code) values  (8, 'outlet', 1, '站点账户', 'outlet');
select f_get_adm_id_seq from dual;

--超级管理员
insert into adm_role_privilege select 0,p.privilege_id from adm_privilege p;
--系统管理员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1101);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1102);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1103);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1801);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1802);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1803);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (1,1805);
--仓库管理员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,10);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1203);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1204);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1205);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1209);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1002);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1003);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1006);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1101);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1201  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1202  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120301);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120302);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120303);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120304);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120305);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120401);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120402);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120403);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120501);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120502);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1206  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1207  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120901);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120902);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120903);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120904);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120905);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,120906);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (2,1803);
--市场管理员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,10);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,15);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,17);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1001);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1005);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1101);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1207);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1501);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1503);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1505);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1502);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1504);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1701);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1702);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1704);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1706);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1703);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1705);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1803);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (3,1804);
--兑奖员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,10);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,13);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,1207);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,1301);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,1303);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (4,1803);
--财务人员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,13);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,14);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,16);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1205);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1209);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1401);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1402);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1101  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,120501);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1206  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,120906);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1303  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140201);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140202);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140203);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1404  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1403  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1405  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140101);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140102);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140103);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1604  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1601  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1602  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1603  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1803  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,1407);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140701);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140702);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (5,140703);
--部门经理
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,10);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,13);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,14);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,16);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1203);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1204);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1205);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1209);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1401);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1002  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1004  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1003  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1006  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1101  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1102  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1103  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,120301);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,120401);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,120501);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1206  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,120904);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,120906);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1303  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,140103);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1604  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1601  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1602  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1603  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1803  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,19);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1901);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1902);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1903);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1904);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (6,1905);
--总部管理人员
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,10);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,12);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,13);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,16);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1203);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1204);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1205);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1209);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1002  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1004  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1101  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1102  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1201  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1202  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,120301);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,120401);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,120501);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1206  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1208  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,120904);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,120906);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1303  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1604  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1601  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1602  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1603  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1803  );
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,19);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1901);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1902);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1903);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1904);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (7,1905);
--站点账户
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,17);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,11);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,18);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1101);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1701);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1702);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1704);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1706);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1703);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1705);
insert into adm_role_privilege(ROLE_ID, PRIVILEGE_ID) values (8,1803);
commit;
