$axure.loadCurrentPage({
  "url":"站点入库.html",
  "generationDate":new Date(1444726798600.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c1f8cd03ba94a969d8bd9281b6d2026",
    "type":"Axure:Page",
    "name":"站点入库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9471c307d63c4e919a07105947a1595f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":79,
              "y":425},
            "size":{
              "width":267,
              "height":137},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"013932a52e9446a98d87e8dfc74655e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":79,
                  "y":425},
                "size":{
                  "width":267,
                  "height":137},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u0.png"}},
{
          "id":"3686e1528e104e028b11660104d6e9a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":34},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0957fe8ca5194df5acfe87ca7de346dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":34},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"567a9705b22342f59acc561869740484",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":79,
              "y":80},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e48c9b1339da4243be116e29f43d946a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":79,
                  "y":80},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"79ddbbe2582d47a5be233514eb3ad806",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":85},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f42ad18cc88481e94ce5874348c138d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":85},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"852fb12519ba43e1825a2cbe5808990f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":85},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ceed18c18c4d97a1c98b8ddab04944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":326,
                  "y":85},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"7c82268d972445e7b9b308a8dbb5a659",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":85},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6bdfd378b2465cad6d9833f9997d18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":91,
                  "y":85},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"38264155cd0842f09b04b3a69ea1c26f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":308,
              "y":88},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa2294732a745df9f4f0f5669234d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":308,
                  "y":88},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac1d0c0f6503467e912013ecb3cc80f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":79,
              "y":102},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6122781d054239a7cd7685ababec6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":79,
                  "y":102},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"1dbf6a3712d443d98de122d137446379",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":106},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822b36d429934428bc4f191df7e3ffcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":106},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"fdd5c911e21b47a48b856940327a9b47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":250},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f736259b4d3f41c8af4ff783655914e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":250},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0210da55683443b28d02dee5afc27bee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":276},
            "size":{
              "width":235,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/站点入库/u20_line.png"}},
{
          "id":"5c6a4f783cd34f5c8bdd5490dd56116a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":306},
            "size":{
              "width":235,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/站点入库/u20_line.png"}},
{
          "id":"525859510e724756a8006ceb9d14ac71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":332},
            "size":{
              "width":235,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/站点入库/u20_line.png"}},
{
          "id":"ea5e9f550eeb4c66bd8af2c295f60475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":288},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2738cf45594e0cad29a385b8b82d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":288},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80447bbc1a574b4fb95e1118d6f84bfd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":595,
              "y":30},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc81ed43a634d37a7b242bc350f5d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":595,
                  "y":30},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u25.png"}},
{
          "id":"d7c93d7fc8ca45b4a6b40d8d2cf42de4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":609,
              "y":77},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1f526d6a7f4cd5a5f1917fdac5f131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":609,
                  "y":77},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"dac12660c4d34a3c944b4c30fa6f180c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":82},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ccc552999594a6fb8ef5a0d9c279a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":82},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"3d8e7057b1334d8b8dcb9b9c58bbd8b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":856,
              "y":82},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"445e6bc3a410455e9548595a406035a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":856,
                  "y":82},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"8d520887e7574b198cce8d8c439b8fa8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":621,
              "y":82},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f33f6eeff404fc093b9b5efedec74c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":621,
                  "y":82},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"7e3bc49d83bd4871bb8085df9e7a8e6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":838,
              "y":85},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fa0c0d6b1984481982378c8b35e449f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":838,
                  "y":85},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9599c8b5f89d4c3dbc0d1a94cb36cdb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":609,
              "y":99},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e361afb9b311481faf82787daae51052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":609,
                  "y":99},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"f49f4f9798a84b539f497325ece728ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":103},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88dda855ff4b479ca1c2e631299f3362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":103},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"4a1e50bdf32e47fc965bf0d36d1e27ad",
          "label":"搜索框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":630,
              "y":260},
            "size":{
              "width":217,
              "height":35}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入登录账号"},
{
          "id":"19c299a865794482a52047e2d0c367e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":310},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f478de48e4874477a8a1ed22092413ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":310},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f912ff8d16e648c4b8f0cb662982a522",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":632,
              "y":321},
            "size":{
              "width":215,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed84e2b41f0a49a18850e3f444d5126e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":632,
                  "y":321},
                "size":{
                  "width":215,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u44.png"}},
{
          "id":"05827f392569462ea143106fa26331b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":179},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b0074339ad3451da09d991da3fb87b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":179},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c537ac356d564cfca61fdd1afcc30b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":96,
              "y":343},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58194e1e34da46d5b6f8489c09b8499c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":343},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013e475e66324268a3107d9c7499ac53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":120,
              "y":373},
            "size":{
              "width":189,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92dc1092f933454c9b8cc611d98ac250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":120,
                  "y":373},
                "size":{
                  "width":189,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u50.png"}},
{
          "id":"94a06494077842b79cd794da16b7918d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":111,
              "y":460},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09837f0753994a08b9abaa98fb91668f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":111,
                  "y":460},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u52.png"}},
{
          "id":"4053614137804874a2e2df77dc5cd699",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":186,
              "y":460},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aade8cc13c294eb6860449a94ac7f470",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":186,
                  "y":460},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u54.png"}},
{
          "id":"d480ce172caa4fac9779842e3cb9f31d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":253,
              "y":460},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6afd9fbd275947ef8d3cb93a6e4c6c8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":253,
                  "y":460},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u56.png"}},
{
          "id":"ae98c65fab354f02a1d3b9cf663e73cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":111,
              "y":484},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e0c5a0d877a4560abdab4e8e4ca570d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":111,
                  "y":484},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u58.png"}},
{
          "id":"711c334c4b264774828bbe0f7635187f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":186,
              "y":484},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab4cfb4033740ad8c5e7b2210f6bbc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":186,
                  "y":484},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u54.png"}},
{
          "id":"d6fe5f0774a4487685e5262a302f2f16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":253,
              "y":484},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af4c50ded28d42b2a9a9a56e089cffc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":253,
                  "y":484},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u56.png"}},
{
          "id":"7ee89bb8faa24a6ebdf112cf86de0774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":111,
              "y":508},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219b5f31046547b3aac5a83a56c8b432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":111,
                  "y":508},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u52.png"}},
{
          "id":"280e199d1da24cebb6926679ce9819dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":186,
              "y":508},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50acba23a5804a3b83f1829bc5124a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":186,
                  "y":508},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u54.png"}},
{
          "id":"da35f4f25c074fe88186ac784424402a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":253,
              "y":508},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81ea051733f04cf0872fd3e2f78a2222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":253,
                  "y":508},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u56.png"}},
{
          "id":"1eb2f701804048639ccf285c779e4976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":632,
              "y":238},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b3a10c0a19b44028630cd0f43b68169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":238},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c5c2429b204a2aad9c954bd3f03143",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":632,
              "y":212},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37bf754902e4a6db32524da8a723504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":632,
                  "y":212},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa8811adf94b4f45a212f26f92b05318",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":450},
            "size":{
              "width":235,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/出货单管理/u158_line.png"}},
{
          "id":"dbb156e4553949ffbc03619897e99126",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":111,
              "y":434},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e9894dd5bb408ba7397421f94e8026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":111,
                  "y":434},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u52.png"}},
{
          "id":"edf77cc1682144e89a0970b595d5f6a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":195,
              "y":434},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb347665b0d54f479605387f68d9f5af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":195,
                  "y":434},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u77.png"}},
{
          "id":"31a7ccc62ec14d1dbc4f68f4fc866513",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":267,
              "y":434},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6885c57fe1ae4fbf89dab6cd10fb2cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":267,
                  "y":434},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u77.png"}},
{
          "id":"7cf2971693274d018e194be602cf9cac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":289},
            "size":{
              "width":31,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c061ea780ac0436f8f3ba5a9404e9e45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":289},
                "size":{
                  "width":31,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u81.png"}},
{
          "id":"566787446ad2433193ca5634cda6d87c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":318},
            "size":{
              "width":31,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dc33db03c3b4351abade4954c9e05b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":318},
                "size":{
                  "width":31,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/站点入库/u81.png"}},
{
          "id":"58c99518245f4e268a5c089ea506f21b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":95,
              "y":256},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62f28fc21614836a8b7d0fd8dbc304d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":256},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eff4477a1284474a8b5ef105e9ff861",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":161,
              "y":256},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26d92e3c1f5641b3a7a79d4c00e837dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":256},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a953156fef3640e68f2fcb09490914f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":234,
              "y":256},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a9b1ba1ee3b4221af2d823c6c724e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":256},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3534bfb20944d5eaed41703fa85de57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":317},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca01f33e60124fcb9505dc9736c7f6ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":317},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d4c2dd0e1144e03ab055ccaec7ffdac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":150},
            "size":{
              "width":148,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"414d8775db8342c2acde1706febddbe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":150},
                "size":{
                  "width":148,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a39c387ea9054c7e87a39e5d6ffc6960",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":120,
              "y":208},
            "size":{
              "width":189,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b2b6696a494aff86adc753cb5c11cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":120,
                  "y":208},
                "size":{
                  "width":189,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 扫描中",
                      "objectsToFades":[{
                          "objectPath":["608c0418504a4ddeb2bdf16e0b52f3bf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/站点入库/u95.png"}},
{
          "id":"608c0418504a4ddeb2bdf16e0b52f3bf",
          "label":"扫描中",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":106,
              "y":204},
            "size":{
              "width":223,
              "height":35},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"bf54221fe42641d5abd0db109925fff6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4ed646bda0074a35aa2d0ab4c0e38e4a",
                  "label":"",
                  "parentDynamicPanel":"608c0418504a4ddeb2bdf16e0b52f3bf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":0,
                      "y":2},
                    "size":{
                      "width":221,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ff8c6f1b30e46eeb7e13a3c18bd021f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"608c0418504a4ddeb2bdf16e0b52f3bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":0,
                          "y":2},
                        "size":{
                          "width":221,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/站点入库/u98.png"}},
{
                  "id":"bb73d8a6055341398ec08aea8dbe40b7",
                  "label":"",
                  "parentDynamicPanel":"608c0418504a4ddeb2bdf16e0b52f3bf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":24,
                      "y":6},
                    "size":{
                      "width":24,
                      "height":24},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff9b13ff2a1547448e80966b8e1ce689",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"608c0418504a4ddeb2bdf16e0b52f3bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":24,
                          "y":6},
                        "size":{
                          "width":24,
                          "height":24},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/站点入库/u100.gif"}}]}]},
{
          "id":"8b27e639b6764b2486798eef7df3610e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":378,
              "y":301},
            "size":{
              "width":209,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58765b4c1a3c4e3a8eb50ca4fea23711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":301},
                "size":{
                  "width":209,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b13ef56505841ffaa2652c22a10201d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":890,
              "y":332},
            "size":{
              "width":368,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f607c736dcf440528e98eb96c0ad3a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":890,
                  "y":332},
                "size":{
                  "width":368,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9471c307d63c4e919a07105947a1595f":{
      "scriptId":"u0"},
    "013932a52e9446a98d87e8dfc74655e3":{
      "scriptId":"u1"},
    "3686e1528e104e028b11660104d6e9a8":{
      "scriptId":"u2"},
    "0957fe8ca5194df5acfe87ca7de346dd":{
      "scriptId":"u3"},
    "567a9705b22342f59acc561869740484":{
      "scriptId":"u4"},
    "e48c9b1339da4243be116e29f43d946a":{
      "scriptId":"u5"},
    "79ddbbe2582d47a5be233514eb3ad806":{
      "scriptId":"u6"},
    "9f42ad18cc88481e94ce5874348c138d":{
      "scriptId":"u7"},
    "852fb12519ba43e1825a2cbe5808990f":{
      "scriptId":"u8"},
    "f5ceed18c18c4d97a1c98b8ddab04944":{
      "scriptId":"u9"},
    "7c82268d972445e7b9b308a8dbb5a659":{
      "scriptId":"u10"},
    "6f6bdfd378b2465cad6d9833f9997d18":{
      "scriptId":"u11"},
    "38264155cd0842f09b04b3a69ea1c26f":{
      "scriptId":"u12"},
    "1aa2294732a745df9f4f0f5669234d88":{
      "scriptId":"u13"},
    "ac1d0c0f6503467e912013ecb3cc80f6":{
      "scriptId":"u14"},
    "fb6122781d054239a7cd7685ababec6d":{
      "scriptId":"u15"},
    "1dbf6a3712d443d98de122d137446379":{
      "scriptId":"u16"},
    "822b36d429934428bc4f191df7e3ffcd":{
      "scriptId":"u17"},
    "fdd5c911e21b47a48b856940327a9b47":{
      "scriptId":"u18"},
    "f736259b4d3f41c8af4ff783655914e2":{
      "scriptId":"u19"},
    "0210da55683443b28d02dee5afc27bee":{
      "scriptId":"u20"},
    "5c6a4f783cd34f5c8bdd5490dd56116a":{
      "scriptId":"u21"},
    "525859510e724756a8006ceb9d14ac71":{
      "scriptId":"u22"},
    "ea5e9f550eeb4c66bd8af2c295f60475":{
      "scriptId":"u23"},
    "4e2738cf45594e0cad29a385b8b82d98":{
      "scriptId":"u24"},
    "80447bbc1a574b4fb95e1118d6f84bfd":{
      "scriptId":"u25"},
    "7fc81ed43a634d37a7b242bc350f5d70":{
      "scriptId":"u26"},
    "d7c93d7fc8ca45b4a6b40d8d2cf42de4":{
      "scriptId":"u27"},
    "5d1f526d6a7f4cd5a5f1917fdac5f131":{
      "scriptId":"u28"},
    "dac12660c4d34a3c944b4c30fa6f180c":{
      "scriptId":"u29"},
    "9ccc552999594a6fb8ef5a0d9c279a2d":{
      "scriptId":"u30"},
    "3d8e7057b1334d8b8dcb9b9c58bbd8b0":{
      "scriptId":"u31"},
    "445e6bc3a410455e9548595a406035a5":{
      "scriptId":"u32"},
    "8d520887e7574b198cce8d8c439b8fa8":{
      "scriptId":"u33"},
    "9f33f6eeff404fc093b9b5efedec74c8":{
      "scriptId":"u34"},
    "7e3bc49d83bd4871bb8085df9e7a8e6b":{
      "scriptId":"u35"},
    "6fa0c0d6b1984481982378c8b35e449f":{
      "scriptId":"u36"},
    "9599c8b5f89d4c3dbc0d1a94cb36cdb3":{
      "scriptId":"u37"},
    "e361afb9b311481faf82787daae51052":{
      "scriptId":"u38"},
    "f49f4f9798a84b539f497325ece728ed":{
      "scriptId":"u39"},
    "88dda855ff4b479ca1c2e631299f3362":{
      "scriptId":"u40"},
    "4a1e50bdf32e47fc965bf0d36d1e27ad":{
      "scriptId":"u41"},
    "19c299a865794482a52047e2d0c367e6":{
      "scriptId":"u42"},
    "f478de48e4874477a8a1ed22092413ed":{
      "scriptId":"u43"},
    "f912ff8d16e648c4b8f0cb662982a522":{
      "scriptId":"u44"},
    "ed84e2b41f0a49a18850e3f444d5126e":{
      "scriptId":"u45"},
    "05827f392569462ea143106fa26331b4":{
      "scriptId":"u46"},
    "4b0074339ad3451da09d991da3fb87b5":{
      "scriptId":"u47"},
    "c537ac356d564cfca61fdd1afcc30b55":{
      "scriptId":"u48"},
    "58194e1e34da46d5b6f8489c09b8499c":{
      "scriptId":"u49"},
    "013e475e66324268a3107d9c7499ac53":{
      "scriptId":"u50"},
    "92dc1092f933454c9b8cc611d98ac250":{
      "scriptId":"u51"},
    "94a06494077842b79cd794da16b7918d":{
      "scriptId":"u52"},
    "09837f0753994a08b9abaa98fb91668f":{
      "scriptId":"u53"},
    "4053614137804874a2e2df77dc5cd699":{
      "scriptId":"u54"},
    "aade8cc13c294eb6860449a94ac7f470":{
      "scriptId":"u55"},
    "d480ce172caa4fac9779842e3cb9f31d":{
      "scriptId":"u56"},
    "6afd9fbd275947ef8d3cb93a6e4c6c8d":{
      "scriptId":"u57"},
    "ae98c65fab354f02a1d3b9cf663e73cf":{
      "scriptId":"u58"},
    "8e0c5a0d877a4560abdab4e8e4ca570d":{
      "scriptId":"u59"},
    "711c334c4b264774828bbe0f7635187f":{
      "scriptId":"u60"},
    "3ab4cfb4033740ad8c5e7b2210f6bbc6":{
      "scriptId":"u61"},
    "d6fe5f0774a4487685e5262a302f2f16":{
      "scriptId":"u62"},
    "af4c50ded28d42b2a9a9a56e089cffc0":{
      "scriptId":"u63"},
    "7ee89bb8faa24a6ebdf112cf86de0774":{
      "scriptId":"u64"},
    "219b5f31046547b3aac5a83a56c8b432":{
      "scriptId":"u65"},
    "280e199d1da24cebb6926679ce9819dc":{
      "scriptId":"u66"},
    "50acba23a5804a3b83f1829bc5124a7e":{
      "scriptId":"u67"},
    "da35f4f25c074fe88186ac784424402a":{
      "scriptId":"u68"},
    "81ea051733f04cf0872fd3e2f78a2222":{
      "scriptId":"u69"},
    "1eb2f701804048639ccf285c779e4976":{
      "scriptId":"u70"},
    "0b3a10c0a19b44028630cd0f43b68169":{
      "scriptId":"u71"},
    "a5c5c2429b204a2aad9c954bd3f03143":{
      "scriptId":"u72"},
    "e37bf754902e4a6db32524da8a723504":{
      "scriptId":"u73"},
    "aa8811adf94b4f45a212f26f92b05318":{
      "scriptId":"u74"},
    "dbb156e4553949ffbc03619897e99126":{
      "scriptId":"u75"},
    "16e9894dd5bb408ba7397421f94e8026":{
      "scriptId":"u76"},
    "edf77cc1682144e89a0970b595d5f6a8":{
      "scriptId":"u77"},
    "fb347665b0d54f479605387f68d9f5af":{
      "scriptId":"u78"},
    "31a7ccc62ec14d1dbc4f68f4fc866513":{
      "scriptId":"u79"},
    "6885c57fe1ae4fbf89dab6cd10fb2cdd":{
      "scriptId":"u80"},
    "7cf2971693274d018e194be602cf9cac":{
      "scriptId":"u81"},
    "c061ea780ac0436f8f3ba5a9404e9e45":{
      "scriptId":"u82"},
    "566787446ad2433193ca5634cda6d87c":{
      "scriptId":"u83"},
    "2dc33db03c3b4351abade4954c9e05b2":{
      "scriptId":"u84"},
    "58c99518245f4e268a5c089ea506f21b":{
      "scriptId":"u85"},
    "d62f28fc21614836a8b7d0fd8dbc304d":{
      "scriptId":"u86"},
    "0eff4477a1284474a8b5ef105e9ff861":{
      "scriptId":"u87"},
    "26d92e3c1f5641b3a7a79d4c00e837dc":{
      "scriptId":"u88"},
    "a953156fef3640e68f2fcb09490914f4":{
      "scriptId":"u89"},
    "2a9b1ba1ee3b4221af2d823c6c724e20":{
      "scriptId":"u90"},
    "e3534bfb20944d5eaed41703fa85de57":{
      "scriptId":"u91"},
    "ca01f33e60124fcb9505dc9736c7f6ff":{
      "scriptId":"u92"},
    "7d4c2dd0e1144e03ab055ccaec7ffdac":{
      "scriptId":"u93"},
    "414d8775db8342c2acde1706febddbe2":{
      "scriptId":"u94"},
    "a39c387ea9054c7e87a39e5d6ffc6960":{
      "scriptId":"u95"},
    "98b2b6696a494aff86adc753cb5c11cf":{
      "scriptId":"u96"},
    "608c0418504a4ddeb2bdf16e0b52f3bf":{
      "scriptId":"u97"},
    "4ed646bda0074a35aa2d0ab4c0e38e4a":{
      "scriptId":"u98"},
    "9ff8c6f1b30e46eeb7e13a3c18bd021f":{
      "scriptId":"u99"},
    "bb73d8a6055341398ec08aea8dbe40b7":{
      "scriptId":"u100"},
    "ff9b13ff2a1547448e80966b8e1ce689":{
      "scriptId":"u101"},
    "8b27e639b6764b2486798eef7df3610e":{
      "scriptId":"u102"},
    "58765b4c1a3c4e3a8eb50ca4fea23711":{
      "scriptId":"u103"},
    "0b13ef56505841ffaa2652c22a10201d":{
      "scriptId":"u104"},
    "f607c736dcf440528e98eb96c0ad3a9b":{
      "scriptId":"u105"}}});