$axure.loadCurrentPage({
  "url":"设备信息.html",
  "generationDate":new Date(1444726799283.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82f33c59e6b7403e95b2700716339241",
    "type":"Axure:Page",
    "name":"设备信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b5f93f851cc4dde810a533b8c996dd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":60},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d308979d21d14b3e839e07dfd018bcf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":60},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"612993ccbd0443a88412fa1649c29361",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":78,
              "y":106},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1c7aab86f2b49cb9b4ad406bef703d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":78,
                  "y":106},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"a314edbbcff943db99e2087ae099e9de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb869e5ff43840e49578587048e8e1bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"3a2c3a4196054a46a2da47e1d519b128",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":111},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e72aa78f8ba405a9d6fc0786a2a9249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":111},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"125b7b08d7be4dfcb3f560afaa720242",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":111},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e7204c433c4847bdd767a75b15121f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":111},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"f7d65eeb43ab445da5e302800e47a57a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":307,
              "y":114},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df5b3399abc3473d8097f8a7991cc409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":114},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121f8ee785ef47bc9754a01ec6e3cc3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":78,
              "y":128},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fecfca4444be40388f5037eefbc962d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":78,
                  "y":128},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"1cf1d3f563714a51bfa6f764ecdd613e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":132},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2f9d785f92c41a286fdde3054f42d8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":132},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u30.png"}},
{
          "id":"0e5efb8406bd4cee92d3feeafe1e8e50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":131},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4855db41a06a44eb87f4b501adc44301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":131},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改登录密码/u27.png"}},
{
          "id":"7d01673e01e8425ca435d1e62d152ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":200},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba567a911e44af49a35b747661f16b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":200},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a112e504ea24585a54294a4873b3497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":234},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd6247674c04d458eb279368f67332a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":234},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"938dc20c6adf403c909934014f5b8b88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":200},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b791bcedf3144f39e660e1ca81250d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":200},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc2c81858b2141ada17d3915586b0b9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":234},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5668319b3dea48909bd6e97ef6984c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":234},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"584401541b9b40b4843951cb552588ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":265},
            "size":{
              "width":31,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd3641d9cf94c50b96ecd86e2f057a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":265},
                "size":{
                  "width":31,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92261e5623194154985207e68e466e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":264},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d18da5fd1e43efa7bae1553e513000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":264},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d1c0d08f3c44f41b8e0fd50f3067f81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":300},
            "size":{
              "width":76,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59720dd00047480abb89bb991899423d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":300},
                "size":{
                  "width":76,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"470c6e09d3f741adb1fb2519bb67a306",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":300},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bb5deef3c4f431eaf3ebc1bff43e619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":300},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56ec4f11334f45529fc92ce4e2f7b377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":334},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16d15784e7bd4c5ab912fe7388f5308a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":334},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26601ae1d814a14a54ebe166aa9450c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":334},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f94c0f98c6244cc80dabd78d5d19397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":334},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3834b1d178eb4e2085b6042c4b09bbc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":364},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e89aefc09cc451abe34fc306251d50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":364},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"639e5d422f10408b9ce2f259595e10cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":364},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1058bf2784814ccbb9b91f1fae0b4daa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":364},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7b5f93f851cc4dde810a533b8c996dd8":{
      "scriptId":"u0"},
    "d308979d21d14b3e839e07dfd018bcf4":{
      "scriptId":"u1"},
    "612993ccbd0443a88412fa1649c29361":{
      "scriptId":"u2"},
    "b1c7aab86f2b49cb9b4ad406bef703d8":{
      "scriptId":"u3"},
    "a314edbbcff943db99e2087ae099e9de":{
      "scriptId":"u4"},
    "bb869e5ff43840e49578587048e8e1bd":{
      "scriptId":"u5"},
    "3a2c3a4196054a46a2da47e1d519b128":{
      "scriptId":"u6"},
    "2e72aa78f8ba405a9d6fc0786a2a9249":{
      "scriptId":"u7"},
    "125b7b08d7be4dfcb3f560afaa720242":{
      "scriptId":"u8"},
    "b5e7204c433c4847bdd767a75b15121f":{
      "scriptId":"u9"},
    "f7d65eeb43ab445da5e302800e47a57a":{
      "scriptId":"u10"},
    "df5b3399abc3473d8097f8a7991cc409":{
      "scriptId":"u11"},
    "121f8ee785ef47bc9754a01ec6e3cc3a":{
      "scriptId":"u12"},
    "fecfca4444be40388f5037eefbc962d1":{
      "scriptId":"u13"},
    "1cf1d3f563714a51bfa6f764ecdd613e":{
      "scriptId":"u14"},
    "f2f9d785f92c41a286fdde3054f42d8c":{
      "scriptId":"u15"},
    "0e5efb8406bd4cee92d3feeafe1e8e50":{
      "scriptId":"u16"},
    "4855db41a06a44eb87f4b501adc44301":{
      "scriptId":"u17"},
    "7d01673e01e8425ca435d1e62d152ce6":{
      "scriptId":"u18"},
    "8ba567a911e44af49a35b747661f16b8":{
      "scriptId":"u19"},
    "6a112e504ea24585a54294a4873b3497":{
      "scriptId":"u20"},
    "5cd6247674c04d458eb279368f67332a":{
      "scriptId":"u21"},
    "938dc20c6adf403c909934014f5b8b88":{
      "scriptId":"u22"},
    "4b791bcedf3144f39e660e1ca81250d3":{
      "scriptId":"u23"},
    "cc2c81858b2141ada17d3915586b0b9f":{
      "scriptId":"u24"},
    "5668319b3dea48909bd6e97ef6984c89":{
      "scriptId":"u25"},
    "584401541b9b40b4843951cb552588ad":{
      "scriptId":"u26"},
    "acd3641d9cf94c50b96ecd86e2f057a9":{
      "scriptId":"u27"},
    "92261e5623194154985207e68e466e82":{
      "scriptId":"u28"},
    "c4d18da5fd1e43efa7bae1553e513000":{
      "scriptId":"u29"},
    "8d1c0d08f3c44f41b8e0fd50f3067f81":{
      "scriptId":"u30"},
    "59720dd00047480abb89bb991899423d":{
      "scriptId":"u31"},
    "470c6e09d3f741adb1fb2519bb67a306":{
      "scriptId":"u32"},
    "1bb5deef3c4f431eaf3ebc1bff43e619":{
      "scriptId":"u33"},
    "56ec4f11334f45529fc92ce4e2f7b377":{
      "scriptId":"u34"},
    "16d15784e7bd4c5ab912fe7388f5308a":{
      "scriptId":"u35"},
    "d26601ae1d814a14a54ebe166aa9450c":{
      "scriptId":"u36"},
    "0f94c0f98c6244cc80dabd78d5d19397":{
      "scriptId":"u37"},
    "3834b1d178eb4e2085b6042c4b09bbc9":{
      "scriptId":"u38"},
    "0e89aefc09cc451abe34fc306251d50c":{
      "scriptId":"u39"},
    "639e5d422f10408b9ce2f259595e10cc":{
      "scriptId":"u40"},
    "1058bf2784814ccbb9b91f1fae0b4daa":{
      "scriptId":"u41"}}});