$axure.loadCurrentPage({
  "url":"账户余额查询.html",
  "generationDate":new Date(1443166056623.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"8b493374f1534727bf4df59b10d9e6e3",
    "type":"Axure:Page",
    "name":"账户余额查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9eccb7f7490c4f0c944a7cfff9c7da7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":520,
              "height":460}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6dd8bec4b447cbb3ef74d95bb82bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":460}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"7b4419616f42498b9b89372315f679d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "size":{
              "width":520,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb20eff743c40f08744d750328a6747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":520,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u2.png"}},
{
          "id":"0a26263203aa4c7984696286d315e59a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":177},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe3fef29a14d48b5ae565e3823014d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":177},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2de591a1a3b406b93b5bd42154e5c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":126},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471a72385a4c4c7a9105ffc923a9daae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":126},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4c6a749bfa142ccaac6326fc6e35bf5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":405},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"87da189014ff4a1cabef6d9f6b558027",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":174},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"376f7a2fe6ab46a5a1efd2d54cb4f56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":126},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"852db23d9277430fb02f422cd95170b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":126},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66129c67825f436e8d8819e34b8138c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":67},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"769df2e62f174d82924d3112ff254ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":67},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e8e8be65cbc46ef9a1d982063e6b2e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":64},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f448b0e29a9d41cbbf24dd5e01f94e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":222},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a21f72882c714cde91c67acedacf6c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":222},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e30f893264d4be585b5fc4e993ca2a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":264},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1b0b3b896504539b246b058d086011a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":264},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9eccb7f7490c4f0c944a7cfff9c7da7f":{
      "scriptId":"u0"},
    "de6dd8bec4b447cbb3ef74d95bb82bf4":{
      "scriptId":"u1"},
    "7b4419616f42498b9b89372315f679d0":{
      "scriptId":"u2"},
    "feb20eff743c40f08744d750328a6747":{
      "scriptId":"u3"},
    "0a26263203aa4c7984696286d315e59a":{
      "scriptId":"u4"},
    "fe3fef29a14d48b5ae565e3823014d52":{
      "scriptId":"u5"},
    "c2de591a1a3b406b93b5bd42154e5c3e":{
      "scriptId":"u6"},
    "471a72385a4c4c7a9105ffc923a9daae":{
      "scriptId":"u7"},
    "d4c6a749bfa142ccaac6326fc6e35bf5":{
      "scriptId":"u8"},
    "87da189014ff4a1cabef6d9f6b558027":{
      "scriptId":"u9"},
    "376f7a2fe6ab46a5a1efd2d54cb4f56a":{
      "scriptId":"u10"},
    "852db23d9277430fb02f422cd95170b7":{
      "scriptId":"u11"},
    "66129c67825f436e8d8819e34b8138c4":{
      "scriptId":"u12"},
    "769df2e62f174d82924d3112ff254ec0":{
      "scriptId":"u13"},
    "2e8e8be65cbc46ef9a1d982063e6b2e7":{
      "scriptId":"u14"},
    "f448b0e29a9d41cbbf24dd5e01f94e97":{
      "scriptId":"u15"},
    "a21f72882c714cde91c67acedacf6c16":{
      "scriptId":"u16"},
    "7e30f893264d4be585b5fc4e993ca2a9":{
      "scriptId":"u17"},
    "a1b0b3b896504539b246b058d086011a":{
      "scriptId":"u18"}}});