$axure.loadCurrentPage({
  "url":"订单管理_1.html",
  "generationDate":new Date(1442224859045.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"209b265d3e064477bbf516b504c93fc8",
    "type":"Axure:Page",
    "name":"订单管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2d3c2490277a4b35a9391af78703bbc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":10},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4400e905e8964fd49a909d76e1ee085b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":10},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 方案列表",
                      "objectsToFades":[{
                          "objectPath":["a0e5232e850e4853862d78f725dd1f9e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"cc9e8ad61c9a48d5a0d819d65d7c8922",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":453,
              "y":56},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e06292a643384517beaa81e2a3eccd7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":453,
                  "y":56},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"00930c2dd2b446ccb7c0e8d9795e3e8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":663,
              "y":61},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e1bec159c7c476cac9109cd4166c6bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":663,
                  "y":61},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"905e87f3f7034e87a7bf53d8329a6688",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":61},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d878b0d18b34bcb814f5be69627dc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":61},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"4ea8698602b741759fb30fb92fc65bda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":61},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411055d374e84ac9b76181f75ac1b551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":61},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"cc130178b3314edbb3ea9fa3ead3ab28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":682,
              "y":64},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97e8678e8b2343b389ff19713fdb7da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":682,
                  "y":64},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"424612ac303d4b14b2aa74cd4eb3d581",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":453,
              "y":78},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18ce06c9fb734be7b14cb6bda4c27caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":453,
                  "y":78},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"4bbaa3b4c49047d499b1ba9d44b5b437",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":83},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f5fcdb90a14cf6978a4878c37ef40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":83},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"f97a154b666644a2a998245f4fa3b002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":164},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5add42883ec14e8b81112fa44aab3aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":164},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9121df29c463465e951646feca5330a4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":186},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b982452c2814d7db2efbecf5b1c0cfb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":91,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9cbaf569bc7945279ce9fe60185e1969",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":91,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u21.png"}},
{
              "id":"d304bed4173945569caf77ab2b020128",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":91,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1317b2a8ac7f4af7af90dffb8c1ed2aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":91,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u27.png"}},
{
              "id":"0350563fc3a94c9bb12ab68282cb8503",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":91,
                  "y":0},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c3fd17ca1f74b958db132f426d13624",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":91,
                      "y":0},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u23.png"}},
{
              "id":"357e6b2db62343009c9f303b70a64c48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":91,
                  "y":30},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"903ec3b5bd5d475bbeecc6f8bdd5ded2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":91,
                      "y":30},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u29.png"}},
{
              "id":"64fb921d36fa4402bec936d7ad1a4c38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":0},
                "size":{
                  "width":83,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72f137114606499a9db60931b722b712",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":0},
                    "size":{
                      "width":83,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u25.png"}},
{
              "id":"5b4a35bd7e7d4559a70cad72beb236aa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":30},
                "size":{
                  "width":83,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ecadb0e9687458a9277e32ee60b955e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":167,
                      "y":30},
                    "size":{
                      "width":83,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/订单管理/u31.png"}}]},
{
          "id":"156d46cfee014b8a9c2e3fb6ce9eddc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":81},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"412b506611a141169ae3709c9fd7402f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":81},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"3de4da3c8a53474599aa5bf5f1d7d29a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":492,
              "y":454},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e1c2fbbc50d4f4dad59a41a458af636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":492,
                  "y":454},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"e7238df4871244b8920a44a42baccf9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":605,
              "y":454},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d659e1079b3d4f4db0df6d16abf48eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":605,
                  "y":454},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"be5ee65bd75149cebae2b108516dbe55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":270},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2534f96e0d48df8d19ec48610dc3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":270},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcf31fdffd2447b79b244e8100bddc90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":292},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5f34f38ae674489ab740fbc10e9d0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":292},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20137422c6ab41b3a8a0e7f3942c7903",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":315},
            "size":{
              "width":246,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ffb716840084d598273fe20934d599c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":315},
                "size":{
                  "width":246,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u47.png"}},
{
          "id":"3562a0d780b3475facbf98cac2541ad7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":10},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9556a660a094e70b27971e5ca917ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":10},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"00663e7a0da3461a8f9ef6bf5708aad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":56},
            "size":{
              "width":272,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b34b82bb4054734bf85f7b700eb003c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":56},
                "size":{
                  "width":272,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u51.png"}},
{
          "id":"4f5a093ecc734d23a958a729b51cb04d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":70,
              "y":81},
            "size":{
              "width":272,
              "height":39},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552d339a446e4d1e8a3995d53ded9ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":70,
                  "y":81},
                "size":{
                  "width":272,
                  "height":39},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u53.png"}},
{
          "id":"39eb29b23c3544f6b89bb55bccac3133",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":85},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd4af5ceec443e5a988d2f4b835f939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":85},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"cc5e5ad20ce84d409f4025c55657ac22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":84},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7279103de37b4f6f9b0f811ae2ffa741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":84},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"54d725e5aeaa4e4aa870bf98c9e4473f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":69,
              "y":56},
            "size":{
              "width":273,
              "height":25},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3525d5477b814801835299c0c9b291f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":69,
                  "y":56},
                "size":{
                  "width":273,
                  "height":25},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单管理/u59.png"}},
{
          "id":"10ba5069fed540e9ac8f44360f44d065",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":62},
            "size":{
              "width":15,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0463d9d3a4e4affbbe90bb2794abe03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":62},
                "size":{
                  "width":15,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"5df3bd19ff1a4b46acb4f03303f179be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":62},
            "size":{
              "width":10,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcaad0df1cbe482b911c5412cd7ae589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":62},
                "size":{
                  "width":10,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"b4812e6d67f443d691e4d610fc27c2a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":303,
              "y":65},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7800adea303e474da2511bcfdb575bb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":303,
                  "y":65},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c016abf482ab4300a967706ba7212cf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":62},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39bc684502b740f5801a0ca0ef9b489b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":62},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"beb7bf0a387e40beb22773324c910d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":259,
              "y":139},
            "size":{
              "width":73,
              "height":20},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe3176707184f46ba7b8dcc2a570faf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":259,
                  "y":139},
                "size":{
                  "width":73,
                  "height":20},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u39.png"}},
{
          "id":"a0e5232e850e4853862d78f725dd1f9e",
          "label":"方案列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":456,
              "y":194},
            "size":{
              "width":262,
              "height":111},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"48bf446d84b04cd588a29140606d9559",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6949521c4aa74b28b5ff064a01f84de5",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CC99},
                    "size":{
                      "width":260,
                      "height":110},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"833893e8b10d480a879624d368b2d8e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF00CC99},
                        "size":{
                          "width":260,
                          "height":110},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单管理_1/u66.png"}},
{
                  "id":"cd9aa0c368c24cdbb1036070fb9bef36",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":12},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f335895b67d54b81af3c4a0def09cfa0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":12},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b4f80286de6a40f287ed08db6fa2e3da",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":117,
                      "y":12},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b40f03524e44b89bee878b30061bd2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":117,
                          "y":12},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c7c9ce46600e46329fcff526f48e1d0d",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":181,
                      "y":12},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e33afa72f3f49aaa1352cd7621db28b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":181,
                          "y":12},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9fbedb79af434e1587502c2c1815fa53",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":38},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ada2daad0afd48869de3612cb2f157ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":38},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"db8f46ee14ba41ada139661f1b129281",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":48,
                      "y":64},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e1864f7f4ab449c96a30f203d733da5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":48,
                          "y":64},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5a4920c21b244f9583a584d2638d916d",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":38},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68617330a1e448f688597aa1b085a1ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":121,
                          "y":38},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f13c39cc7ba84843b3b7f680da5534b4",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":38},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b4fc769ec6b045dd9707c06d1d81492c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":38},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"52a1a466d1c8415e87a32b343f538d6e",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":121,
                      "y":64},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdf01fdf13ae4d2c85ff6d1cb19ba3d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":121,
                          "y":64},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"977c5229d57f47e0a55a3588f52e6b40",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":185,
                      "y":64},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"49a3fc33c451439484b15e05e9846c44",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":185,
                          "y":64},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08ebf68215834b0a830c1f60030574a8",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":11},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65acd35a63b945a8b0ae1f1509d54f5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":11},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"dd53f669b12541e6a7e3b4eb9c6d0edb",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":37},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be419e593d6842ebbdf57bbeb3628a53",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":37},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"929b658855e14f368bd2f09802bf0aa3",
                  "label":"",
                  "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":63},
                    "size":{
                      "width":96,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e40befa9274416b8674d92e4373c347",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a0e5232e850e4853862d78f725dd1f9e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":63},
                        "size":{
                          "width":96,
                          "height":16}},
                      "adaptiveStyles":{
}}]}]}]},
{
          "id":"052c63c6b5724491955d6f1f00988367",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":684,
              "y":159},
            "size":{
              "width":27,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a028436070a454a8591825f5198b36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":684,
                  "y":159},
                "size":{
                  "width":27,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 方案列表",
                      "objectsToFades":[{
                          "objectPath":["a0e5232e850e4853862d78f725dd1f9e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/订单管理/u138.png"}},
{
          "id":"ae1241d724a84472a44dfefa4d21bcbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":130},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"881f6589c5f9471f85cb1ef610e49c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":130},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54080aeec9845d0890dcf43daac49af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":124},
            "size":{
              "width":174,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fdd6e86219284cf5a31ee1d6ec50d71c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":100,
              "y":208},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f494c7305364ccba26e45e2d4463558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":208},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7adf7ce10a954e12ba30018c9fe6280b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":154,
              "y":208},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85a0a28cb0a7486cb8aa85134e593128",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":208},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e08717526d9d43e1b2715bd9bcf5562f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":227,
              "y":208},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e74b88f885e4a1e918c38ec024cb358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":227,
                  "y":208},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e87e954ed44945a1bcdfef7383abbdee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399CC,
              "opacity":1},
            "location":{
              "x":289,
              "y":208},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c775dbf559d64d9dab7761714fe22807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399CC,
                  "opacity":1},
                "location":{
                  "x":289,
                  "y":208},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3315d707b6447babebf6e5042b9285d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":224},
            "size":{
              "width":245,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/出货单管理/u78_line.png"}},
{
          "id":"3a3a619b0c244fd5803aa273d409da29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":237},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfef86b8561349948adc22408c3b0a25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":237},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e78b5c57084a44b0af418490d40b5752",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":237},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e06eeafe7b4f4434a3aff0e2b76c6e85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":237},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdd341cdb8f54572b132955841789f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":237},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d575ed393a74686875610869662e2b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":237},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c96dfab3625141e8afeba54e17edf44f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":237},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7be0ec7a9a4740ca98010f7a54d8e71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":237},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c74ad25d964f4fd496a774aca86739c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":253},
            "size":{
              "width":245,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/出货单管理/u78_line.png"}},
{
          "id":"fce2ededb291431588b6b4db420d7658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":266},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c7ac04da3d41e28cdd13229e561857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":266},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a1c8ca909a4620b3ecf38c9502d0a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":266},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb00fa15968b426e8cb2335ddd1c76f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":266},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91d5d86f4469427ab44d5d5dd59b292b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":266},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2dbee23f124496aa2295ee720c8b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":266},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8127158ba811474492aee2d610f98a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":266},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c392d247ee4962a7f3ce6d425cd27e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":266},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eefe34b179d40038c1b36153a6c1e54",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":281},
            "size":{
              "width":245,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/出货单管理/u78_line.png"}},
{
          "id":"5b10f9f3cb7d435486774d07222b1f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":294},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea61095896cc456ba31af1723fa15ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":294},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b20a844de04940b490de0121e33a442d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":294},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55072e3bfff54e40b9cbff2528fd03b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":294},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8387617d48d14afc938f81caf6c8d505",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":294},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef4cb0cae9ff45efba84f3cd0e91aa61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":294},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f57357fe36324ecb9987c4ad0523ae08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":294},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae6d9fe3130413f899a62635ed961ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":294},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2d3c2490277a4b35a9391af78703bbc1":{
      "scriptId":"u0"},
    "4400e905e8964fd49a909d76e1ee085b":{
      "scriptId":"u1"},
    "cc9e8ad61c9a48d5a0d819d65d7c8922":{
      "scriptId":"u2"},
    "e06292a643384517beaa81e2a3eccd7a":{
      "scriptId":"u3"},
    "00930c2dd2b446ccb7c0e8d9795e3e8c":{
      "scriptId":"u4"},
    "3e1bec159c7c476cac9109cd4166c6bb":{
      "scriptId":"u5"},
    "905e87f3f7034e87a7bf53d8329a6688":{
      "scriptId":"u6"},
    "9d878b0d18b34bcb814f5be69627dc87":{
      "scriptId":"u7"},
    "4ea8698602b741759fb30fb92fc65bda":{
      "scriptId":"u8"},
    "411055d374e84ac9b76181f75ac1b551":{
      "scriptId":"u9"},
    "cc130178b3314edbb3ea9fa3ead3ab28":{
      "scriptId":"u10"},
    "97e8678e8b2343b389ff19713fdb7da4":{
      "scriptId":"u11"},
    "424612ac303d4b14b2aa74cd4eb3d581":{
      "scriptId":"u12"},
    "18ce06c9fb734be7b14cb6bda4c27caa":{
      "scriptId":"u13"},
    "4bbaa3b4c49047d499b1ba9d44b5b437":{
      "scriptId":"u14"},
    "21f5fcdb90a14cf6978a4878c37ef40b":{
      "scriptId":"u15"},
    "f97a154b666644a2a998245f4fa3b002":{
      "scriptId":"u16"},
    "5add42883ec14e8b81112fa44aab3aa5":{
      "scriptId":"u17"},
    "9121df29c463465e951646feca5330a4":{
      "scriptId":"u18"},
    "1b982452c2814d7db2efbecf5b1c0cfb":{
      "scriptId":"u19"},
    "9cbaf569bc7945279ce9fe60185e1969":{
      "scriptId":"u20"},
    "0350563fc3a94c9bb12ab68282cb8503":{
      "scriptId":"u21"},
    "4c3fd17ca1f74b958db132f426d13624":{
      "scriptId":"u22"},
    "64fb921d36fa4402bec936d7ad1a4c38":{
      "scriptId":"u23"},
    "72f137114606499a9db60931b722b712":{
      "scriptId":"u24"},
    "d304bed4173945569caf77ab2b020128":{
      "scriptId":"u25"},
    "1317b2a8ac7f4af7af90dffb8c1ed2aa":{
      "scriptId":"u26"},
    "357e6b2db62343009c9f303b70a64c48":{
      "scriptId":"u27"},
    "903ec3b5bd5d475bbeecc6f8bdd5ded2":{
      "scriptId":"u28"},
    "5b4a35bd7e7d4559a70cad72beb236aa":{
      "scriptId":"u29"},
    "4ecadb0e9687458a9277e32ee60b955e":{
      "scriptId":"u30"},
    "156d46cfee014b8a9c2e3fb6ce9eddc8":{
      "scriptId":"u31"},
    "412b506611a141169ae3709c9fd7402f":{
      "scriptId":"u32"},
    "3de4da3c8a53474599aa5bf5f1d7d29a":{
      "scriptId":"u33"},
    "3e1c2fbbc50d4f4dad59a41a458af636":{
      "scriptId":"u34"},
    "e7238df4871244b8920a44a42baccf9d":{
      "scriptId":"u35"},
    "d659e1079b3d4f4db0df6d16abf48eed":{
      "scriptId":"u36"},
    "be5ee65bd75149cebae2b108516dbe55":{
      "scriptId":"u37"},
    "5c2534f96e0d48df8d19ec48610dc3b8":{
      "scriptId":"u38"},
    "dcf31fdffd2447b79b244e8100bddc90":{
      "scriptId":"u39"},
    "f5f34f38ae674489ab740fbc10e9d0ed":{
      "scriptId":"u40"},
    "20137422c6ab41b3a8a0e7f3942c7903":{
      "scriptId":"u41"},
    "0ffb716840084d598273fe20934d599c":{
      "scriptId":"u42"},
    "3562a0d780b3475facbf98cac2541ad7":{
      "scriptId":"u43"},
    "e9556a660a094e70b27971e5ca917ee3":{
      "scriptId":"u44"},
    "00663e7a0da3461a8f9ef6bf5708aad1":{
      "scriptId":"u45"},
    "7b34b82bb4054734bf85f7b700eb003c":{
      "scriptId":"u46"},
    "4f5a093ecc734d23a958a729b51cb04d":{
      "scriptId":"u47"},
    "552d339a446e4d1e8a3995d53ded9ee2":{
      "scriptId":"u48"},
    "39eb29b23c3544f6b89bb55bccac3133":{
      "scriptId":"u49"},
    "dcd4af5ceec443e5a988d2f4b835f939":{
      "scriptId":"u50"},
    "cc5e5ad20ce84d409f4025c55657ac22":{
      "scriptId":"u51"},
    "7279103de37b4f6f9b0f811ae2ffa741":{
      "scriptId":"u52"},
    "54d725e5aeaa4e4aa870bf98c9e4473f":{
      "scriptId":"u53"},
    "3525d5477b814801835299c0c9b291f9":{
      "scriptId":"u54"},
    "10ba5069fed540e9ac8f44360f44d065":{
      "scriptId":"u55"},
    "d0463d9d3a4e4affbbe90bb2794abe03":{
      "scriptId":"u56"},
    "5df3bd19ff1a4b46acb4f03303f179be":{
      "scriptId":"u57"},
    "fcaad0df1cbe482b911c5412cd7ae589":{
      "scriptId":"u58"},
    "b4812e6d67f443d691e4d610fc27c2a9":{
      "scriptId":"u59"},
    "7800adea303e474da2511bcfdb575bb9":{
      "scriptId":"u60"},
    "c016abf482ab4300a967706ba7212cf8":{
      "scriptId":"u61"},
    "39bc684502b740f5801a0ca0ef9b489b":{
      "scriptId":"u62"},
    "beb7bf0a387e40beb22773324c910d6a":{
      "scriptId":"u63"},
    "4fe3176707184f46ba7b8dcc2a570faf":{
      "scriptId":"u64"},
    "a0e5232e850e4853862d78f725dd1f9e":{
      "scriptId":"u65"},
    "6949521c4aa74b28b5ff064a01f84de5":{
      "scriptId":"u66"},
    "833893e8b10d480a879624d368b2d8e6":{
      "scriptId":"u67"},
    "cd9aa0c368c24cdbb1036070fb9bef36":{
      "scriptId":"u68"},
    "f335895b67d54b81af3c4a0def09cfa0":{
      "scriptId":"u69"},
    "b4f80286de6a40f287ed08db6fa2e3da":{
      "scriptId":"u70"},
    "4b40f03524e44b89bee878b30061bd2e":{
      "scriptId":"u71"},
    "c7c9ce46600e46329fcff526f48e1d0d":{
      "scriptId":"u72"},
    "4e33afa72f3f49aaa1352cd7621db28b":{
      "scriptId":"u73"},
    "9fbedb79af434e1587502c2c1815fa53":{
      "scriptId":"u74"},
    "ada2daad0afd48869de3612cb2f157ab":{
      "scriptId":"u75"},
    "db8f46ee14ba41ada139661f1b129281":{
      "scriptId":"u76"},
    "4e1864f7f4ab449c96a30f203d733da5":{
      "scriptId":"u77"},
    "5a4920c21b244f9583a584d2638d916d":{
      "scriptId":"u78"},
    "68617330a1e448f688597aa1b085a1ed":{
      "scriptId":"u79"},
    "f13c39cc7ba84843b3b7f680da5534b4":{
      "scriptId":"u80"},
    "b4fc769ec6b045dd9707c06d1d81492c":{
      "scriptId":"u81"},
    "52a1a466d1c8415e87a32b343f538d6e":{
      "scriptId":"u82"},
    "fdf01fdf13ae4d2c85ff6d1cb19ba3d8":{
      "scriptId":"u83"},
    "977c5229d57f47e0a55a3588f52e6b40":{
      "scriptId":"u84"},
    "49a3fc33c451439484b15e05e9846c44":{
      "scriptId":"u85"},
    "08ebf68215834b0a830c1f60030574a8":{
      "scriptId":"u86"},
    "65acd35a63b945a8b0ae1f1509d54f5d":{
      "scriptId":"u87"},
    "dd53f669b12541e6a7e3b4eb9c6d0edb":{
      "scriptId":"u88"},
    "be419e593d6842ebbdf57bbeb3628a53":{
      "scriptId":"u89"},
    "929b658855e14f368bd2f09802bf0aa3":{
      "scriptId":"u90"},
    "4e40befa9274416b8674d92e4373c347":{
      "scriptId":"u91"},
    "052c63c6b5724491955d6f1f00988367":{
      "scriptId":"u92"},
    "1a028436070a454a8591825f5198b36a":{
      "scriptId":"u93"},
    "ae1241d724a84472a44dfefa4d21bcbf":{
      "scriptId":"u94"},
    "881f6589c5f9471f85cb1ef610e49c4a":{
      "scriptId":"u95"},
    "e54080aeec9845d0890dcf43daac49af":{
      "scriptId":"u96"},
    "fdd6e86219284cf5a31ee1d6ec50d71c":{
      "scriptId":"u97"},
    "9f494c7305364ccba26e45e2d4463558":{
      "scriptId":"u98"},
    "7adf7ce10a954e12ba30018c9fe6280b":{
      "scriptId":"u99"},
    "85a0a28cb0a7486cb8aa85134e593128":{
      "scriptId":"u100"},
    "e08717526d9d43e1b2715bd9bcf5562f":{
      "scriptId":"u101"},
    "9e74b88f885e4a1e918c38ec024cb358":{
      "scriptId":"u102"},
    "e87e954ed44945a1bcdfef7383abbdee":{
      "scriptId":"u103"},
    "c775dbf559d64d9dab7761714fe22807":{
      "scriptId":"u104"},
    "c3315d707b6447babebf6e5042b9285d":{
      "scriptId":"u105"},
    "3a3a619b0c244fd5803aa273d409da29":{
      "scriptId":"u106"},
    "dfef86b8561349948adc22408c3b0a25":{
      "scriptId":"u107"},
    "e78b5c57084a44b0af418490d40b5752":{
      "scriptId":"u108"},
    "e06eeafe7b4f4434a3aff0e2b76c6e85":{
      "scriptId":"u109"},
    "fdd341cdb8f54572b132955841789f50":{
      "scriptId":"u110"},
    "2d575ed393a74686875610869662e2b5":{
      "scriptId":"u111"},
    "c96dfab3625141e8afeba54e17edf44f":{
      "scriptId":"u112"},
    "7be0ec7a9a4740ca98010f7a54d8e71c":{
      "scriptId":"u113"},
    "c74ad25d964f4fd496a774aca86739c2":{
      "scriptId":"u114"},
    "fce2ededb291431588b6b4db420d7658":{
      "scriptId":"u115"},
    "11c7ac04da3d41e28cdd13229e561857":{
      "scriptId":"u116"},
    "31a1c8ca909a4620b3ecf38c9502d0a9":{
      "scriptId":"u117"},
    "eb00fa15968b426e8cb2335ddd1c76f5":{
      "scriptId":"u118"},
    "91d5d86f4469427ab44d5d5dd59b292b":{
      "scriptId":"u119"},
    "2f2dbee23f124496aa2295ee720c8b2d":{
      "scriptId":"u120"},
    "8127158ba811474492aee2d610f98a55":{
      "scriptId":"u121"},
    "58c392d247ee4962a7f3ce6d425cd27e":{
      "scriptId":"u122"},
    "6eefe34b179d40038c1b36153a6c1e54":{
      "scriptId":"u123"},
    "5b10f9f3cb7d435486774d07222b1f23":{
      "scriptId":"u124"},
    "ea61095896cc456ba31af1723fa15ef3":{
      "scriptId":"u125"},
    "b20a844de04940b490de0121e33a442d":{
      "scriptId":"u126"},
    "55072e3bfff54e40b9cbff2528fd03b6":{
      "scriptId":"u127"},
    "8387617d48d14afc938f81caf6c8d505":{
      "scriptId":"u128"},
    "ef4cb0cae9ff45efba84f3cd0e91aa61":{
      "scriptId":"u129"},
    "f57357fe36324ecb9987c4ad0523ae08":{
      "scriptId":"u130"},
    "eae6d9fe3130413f899a62635ed961ba":{
      "scriptId":"u131"}}});