$axure.loadCurrentPage({
  "url":"扫描测试_1.html",
  "generationDate":new Date(1442224859244.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7a00b2d8fa3d4e1aa2a5d92f5a70bdb1",
    "type":"Axure:Page",
    "name":"扫描测试",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3ff648b72e6a4d2a9886ca8fb13db863",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":30},
            "size":{
              "width":295,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e39d56a4e4f74af48232e67ca2ac64bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":30},
                "size":{
                  "width":295,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"3d63fde459bd4a368ecb77347e10309b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":78,
              "y":76},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c763a457e0334b4dadebbe5f9a244a33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":78,
                  "y":76},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"09e27e2750744842b041fa7d2ef42132",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":81},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b540a6c67e4056a7f1be8b4aa9fd1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":81},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"3f75aa3534e44be89996a78a24c68cb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":81},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f79f290225fb43659e038e4e53d7895e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":81},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"e741654d96bd467bb0010e4c3cade82d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":81},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947e6ca4913c43069cfaff0f399d8211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":81},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"841aef3049bd44cb9746c02e5a0cb8be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":307,
              "y":84},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952eb9df5a8845af8b6164a06bffd540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":307,
                  "y":84},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631bfd2d9e8f41c5815312a84e39d417",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":78,
              "y":98},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8648e496a7e42a5ad6948b51f159a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":78,
                  "y":98},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"f2fc95c7a2d14469a6e2ef7eb1e7ed24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":102},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d0d2345bf304e4bbb070b90aca4cd10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":102},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u14.png"}},
{
          "id":"588cbdb25eb1406e91a37f44187b1289",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":101},
            "size":{
              "width":16,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db5966af1de24b59b2dbd8dfb70a26eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":101},
                "size":{
                  "width":16,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/出货单管理/u37.png"}},
{
          "id":"901b3ca04fe64a12b21c8b0ec1bf663b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":173},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"889bfd0b4d14446e842c707998a16ed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":173},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5a235403fdb460b82a8822d70cfaf50",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":196},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"27efd1174d7446258031b9495f4cf75a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":231},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa78d42a7a845798fa5cf0e01823121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":231},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3ff648b72e6a4d2a9886ca8fb13db863":{
      "scriptId":"u0"},
    "e39d56a4e4f74af48232e67ca2ac64bd":{
      "scriptId":"u1"},
    "3d63fde459bd4a368ecb77347e10309b":{
      "scriptId":"u2"},
    "c763a457e0334b4dadebbe5f9a244a33":{
      "scriptId":"u3"},
    "09e27e2750744842b041fa7d2ef42132":{
      "scriptId":"u4"},
    "c9b540a6c67e4056a7f1be8b4aa9fd1c":{
      "scriptId":"u5"},
    "3f75aa3534e44be89996a78a24c68cb6":{
      "scriptId":"u6"},
    "f79f290225fb43659e038e4e53d7895e":{
      "scriptId":"u7"},
    "e741654d96bd467bb0010e4c3cade82d":{
      "scriptId":"u8"},
    "947e6ca4913c43069cfaff0f399d8211":{
      "scriptId":"u9"},
    "841aef3049bd44cb9746c02e5a0cb8be":{
      "scriptId":"u10"},
    "952eb9df5a8845af8b6164a06bffd540":{
      "scriptId":"u11"},
    "631bfd2d9e8f41c5815312a84e39d417":{
      "scriptId":"u12"},
    "b8648e496a7e42a5ad6948b51f159a90":{
      "scriptId":"u13"},
    "f2fc95c7a2d14469a6e2ef7eb1e7ed24":{
      "scriptId":"u14"},
    "3d0d2345bf304e4bbb070b90aca4cd10":{
      "scriptId":"u15"},
    "588cbdb25eb1406e91a37f44187b1289":{
      "scriptId":"u16"},
    "db5966af1de24b59b2dbd8dfb70a26eb":{
      "scriptId":"u17"},
    "901b3ca04fe64a12b21c8b0ec1bf663b":{
      "scriptId":"u18"},
    "889bfd0b4d14446e842c707998a16ed0":{
      "scriptId":"u19"},
    "d5a235403fdb460b82a8822d70cfaf50":{
      "scriptId":"u20"},
    "27efd1174d7446258031b9495f4cf75a":{
      "scriptId":"u21"},
    "dfa78d42a7a845798fa5cf0e01823121":{
      "scriptId":"u22"}}});