$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1444726797918),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c653299f27994d9a9f6c48bfc6fb05bb",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d533d8ef177d4732924ae4b28085172a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":295,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae12ba3d11e145be910655e39989d48e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":295,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"2a81c41735674db88aa97fcc5ffc725d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":73,
              "y":126},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be3096e81e948bc8e18e6ead4e16488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":73,
                  "y":126},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"f58fa1ffe2294b8eb9058ca82315c500",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b75dd4415eb41f0a2119da4509e27c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"53a0b953201d460ebce92cd624ffbd1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":131},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"462c3b9b500d4753b213cf28c30623bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":131},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"e875399205a94381bd6fcafbab11af05",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5031879eb184e838f2c56aceaeeb376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"e195059838474a16b0e86911952d5f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":302,
              "y":134},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1633a21180964f78b3059bc07b06333a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":134},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3c0e386b96646c8be0f6c962c57f657",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":73,
              "y":148},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f66c5e9a36f49b8ac531ae92e8cc01a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":73,
                  "y":148},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"2c70a1fb04ed4ad7845ef15e2ea2b5e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":223},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6986389f614457cbdad9b520c25af0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":223},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6b1b64a5c81468ba04effd9ac28c6aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":272},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4938d41ee21a43aeb3b01bb5c3c5d026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":272},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0e2be75a3b64676b44d2ac2561bfb08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":244},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"0e3de9d82d8946a987b81e661ab57c8c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":294},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"0d1feb6787d24513a56c7cf9d67a3f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":158,
              "y":223},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f6801094184a44bab2a8193db79c34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":223},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93fa2cb9128c42979f18799dfe8d7286",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":157,
              "y":272},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f883acee0ac473ea00d69c327b432dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":272},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a160d500a7b4048b543e58c5840d020",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":90,
              "y":360},
            "size":{
              "width":235,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20dca46276dd4a5f87def2f22d27d875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":90,
                  "y":360},
                "size":{
                  "width":235,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u24.png"}},
{
          "id":"6782ce90abc84a159f8ac227bf528113",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8b430ba8b844c2abeaf67100d7d770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"86126e4a5bc840e19d37cc5669ede981",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a514225689f446a2bc1d95a3d9fa891d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8b49a0e539784ab9b723eb1393fbd3da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9be77029a5244c484127dfb7605835d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"656d8a9ae093413382244ff38eece9c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":425,
              "y":80},
            "size":{
              "width":295,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ebec4e67824469abd2f3f74d33f9c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":425,
                  "y":80},
                "size":{
                  "width":295,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"bfc5342014af4258bb8e907d0b6d18e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":438,
              "y":126},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52499844e4f4492598b84dcb2fe0d980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":438,
                  "y":126},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"ed42beffba554175bad4b55399c8203a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae75daeb70c4ed390cd77677f182b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"8f15f4f49b9a417499439453943ac422",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":131},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58cdcba09c1d456db6dc05d80431dbd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":685,
                  "y":131},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"4ced19202344451bb7e34bd1b5a756d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"744e8509c065496ca5d11d9c615c46ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"2a058ce370fc476d82b667aa840b8659",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":667,
              "y":134},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5e8ea409e9425aa45a81db708a9031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":667,
                  "y":134},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc090a5a22504d06b5cab9f42cd36241",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":438,
              "y":148},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d67b1648df7047c49d4f6dae23e9ff33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":438,
                  "y":148},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"091284071cd949878e685c3931049d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":223},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"048edc49a2b34865b25682dd536935d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":223},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e6b9a5555148b7ae867258e54114bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":272},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e711ea8e91d4498a6feb39c26dd9968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":272},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd60599158984b5a9b0c7c0dfe404474",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":244},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"679dc440c6cd452cbb1cffa879fe3808",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":451,
              "y":294},
            "size":{
              "width":250,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/菜单列表/u275_line.png"}},
{
          "id":"729df597b3ab4ec58feb74c8933617f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":523,
              "y":223},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393250b8d1cf4454a6dd7bce576ad611",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":523,
                  "y":223},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"319d88a9e28741b68cf9c532cb27a544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":522,
              "y":272},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b5c05d0600143228c24f2d10c6e5481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":522,
                  "y":272},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"775d3b602412414685e71bdd61b70da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":455,
              "y":360},
            "size":{
              "width":235,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfcab8ae6c7d4098a1d92b7ab04500b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":455,
                  "y":360},
                "size":{
                  "width":235,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u24.png"}},
{
          "id":"5704e30ecbdc41ea84dac6f62475357b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb1279706f304cb4b9f6c897b18d4f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"76ba32c18eaa4a489c2918ce34b62adf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":529,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4720e61a6d0244c2954c85c4ad6d8b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":529,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7dfc7685cb004d0a970c5a2070975c97",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":605,
              "y":324},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b4480d9a6e54b268b559aa7101097e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":605,
                  "y":324},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"7ec859c9dc3b4816982a72ef97660f01",
          "label":"设置密码",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":298},
            "size":{
              "width":257,
              "height":115}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"932608dc8ab6479097ca7f643b07446d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a20114a9deac41159f349048274616dc",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":250,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8478738c9b943f2af82a7d0b64a5ac8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":250,
                          "height":110}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录/u65.png"}},
{
                  "id":"f070be8f62fe4d3ea0b7dbc09b575bb3",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":18,
                      "y":14},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d80535ef847c469da8ffb4aa82346ce5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":18,
                          "y":14},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f0bf38a84ee1496586e5a5a127a0ff13",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":50},
                    "size":{
                      "width":26,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u69_line.png"}},
{
                  "id":"b56e3490fb5b4c7da228860e958f060a",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":50},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u70_line.png"}},
{
                  "id":"7b7be1649817442098103f1a77201cb6",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":95,
                      "y":50},
                    "size":{
                      "width":25,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u71_line.png"}},
{
                  "id":"e51b40c5294a4c1c99623a0dd98dfcc3",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":50},
                    "size":{
                      "width":26,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u69_line.png"}},
{
                  "id":"72cb029e41fc4407a0f947da42b1ea3a",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":154,
                      "y":50},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u70_line.png"}},
{
                  "id":"8e6e3fbfcd624b6184d7fc65464c7b05",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":189,
                      "y":50},
                    "size":{
                      "width":25,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/登录/u71_line.png"}},
{
                  "id":"2f0916132322445bbca221685dc69ee3",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecef13dcba344bad8c78d11195ebc038",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":130,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录/u75.png"}},
{
                  "id":"75d086de27744c0781d6fb831bba72d4",
                  "label":"",
                  "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":80},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15967cd897414796aedb373648271c66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7ec859c9dc3b4816982a72ef97660f01",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":124,
                          "y":80},
                        "size":{
                          "width":126,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录/u77.png"}}]}]},
{
          "id":"286e9b7287bc44d3a3d87f3ee99aeb8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":154},
            "size":{
              "width":25,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d076734909c942e09c0ca5dc9917b188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":154},
                "size":{
                  "width":25,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u79.png"}},
{
          "id":"966f74a4557543d0895bfec847e33de8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":80},
            "size":{
              "width":295,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c631af3b09cb4b6e9080b4fd1925a4be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":80},
                "size":{
                  "width":295,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u0.png"}},
{
          "id":"99fbb6a9929c41b2beeb0e2d93b624bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":788,
              "y":126},
            "size":{
              "width":267,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b628a7cfb3432080e7ef05f5369ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":788,
                  "y":126},
                "size":{
                  "width":267,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u2.png"}},
{
          "id":"d1227dc139d44b1594ee4daa7755e918",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":998,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae11ab16eaa14a1cbc10799c4959f4ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":998,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u4.png"}},
{
          "id":"6e781674470c4e30ab89f957734bcc19",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":131},
            "size":{
              "width":10,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be460cca43c6475aaf47f5f9fa55eab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035,
                  "y":131},
                "size":{
                  "width":10,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u6.png"}},
{
          "id":"57b7f67f7bee40d088a89dc043e100db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":131},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8d4abca13445e8a107940a7a7f851c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":131},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u8.png"}},
{
          "id":"bf2276d61ddc43b59dc246aaf2fce8ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBFBFBF,
              "opacity":1},
            "location":{
              "x":1017,
              "y":134},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d022044b843047a987428283638ac756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBFBFBF,
                  "opacity":1},
                "location":{
                  "x":1017,
                  "y":134},
                "size":{
                  "width":16,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfaec7e69fbf4fc1b184582da93f95fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Elephant Normal', 'Elephant'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":788,
              "y":148},
            "size":{
              "width":267,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbd173080554003b667500cd063efc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Elephant Normal', 'Elephant'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":788,
                  "y":148},
                "size":{
                  "width":267,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/菜单列表/u12.png"}},
{
          "id":"41ac721f2cfe49659a9402258274a993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":814,
              "y":205},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16c40d39334d4ab291ab125f0635af06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":814,
                  "y":205},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d42f238581849b38c448973593a0c56",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":200},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3c96d9f0e3734c62babeea5654188c77",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":236},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7a01b90f46704e6587e384c7b57ab209",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":821,
              "y":240},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb9a3158b614f2aaf4fe6a0fb362a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":821,
                  "y":240},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebafee1ffdc34812a5427666050107be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":811,
              "y":360},
            "size":{
              "width":223,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5edcd3f364554c0f8c0f86e8eb037b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":811,
                  "y":360},
                "size":{
                  "width":223,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u101.png"}},
{
          "id":"dd980fd4531d4b47940eb6a58ed0e660",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":276},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15a90667de04ad28ac1bf0e12814bbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":276},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca1020c4e704afe8e3a9ee7a39abac0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":271},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7d20f96362d94674b8cb5a425556d4a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":874,
              "y":305},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bd59c73c2fb448229c31cfca79f61e70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":822,
              "y":309},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7ad42f333aa4137ba4211e0799fc8ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":822,
                  "y":309},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f471c956cc434b4782dec5c501c43d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":811,
              "y":420},
            "size":{
              "width":223,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace114ab3bbe4309a6fa7e1112ee7534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":811,
                  "y":420},
                "size":{
                  "width":223,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u101.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d533d8ef177d4732924ae4b28085172a":{
      "scriptId":"u0"},
    "ae12ba3d11e145be910655e39989d48e":{
      "scriptId":"u1"},
    "2a81c41735674db88aa97fcc5ffc725d":{
      "scriptId":"u2"},
    "3be3096e81e948bc8e18e6ead4e16488":{
      "scriptId":"u3"},
    "f58fa1ffe2294b8eb9058ca82315c500":{
      "scriptId":"u4"},
    "2b75dd4415eb41f0a2119da4509e27c0":{
      "scriptId":"u5"},
    "53a0b953201d460ebce92cd624ffbd1c":{
      "scriptId":"u6"},
    "462c3b9b500d4753b213cf28c30623bb":{
      "scriptId":"u7"},
    "e875399205a94381bd6fcafbab11af05":{
      "scriptId":"u8"},
    "b5031879eb184e838f2c56aceaeeb376":{
      "scriptId":"u9"},
    "e195059838474a16b0e86911952d5f99":{
      "scriptId":"u10"},
    "1633a21180964f78b3059bc07b06333a":{
      "scriptId":"u11"},
    "c3c0e386b96646c8be0f6c962c57f657":{
      "scriptId":"u12"},
    "7f66c5e9a36f49b8ac531ae92e8cc01a":{
      "scriptId":"u13"},
    "2c70a1fb04ed4ad7845ef15e2ea2b5e8":{
      "scriptId":"u14"},
    "c6986389f614457cbdad9b520c25af0c":{
      "scriptId":"u15"},
    "b6b1b64a5c81468ba04effd9ac28c6aa":{
      "scriptId":"u16"},
    "4938d41ee21a43aeb3b01bb5c3c5d026":{
      "scriptId":"u17"},
    "f0e2be75a3b64676b44d2ac2561bfb08":{
      "scriptId":"u18"},
    "0e3de9d82d8946a987b81e661ab57c8c":{
      "scriptId":"u19"},
    "0d1feb6787d24513a56c7cf9d67a3f50":{
      "scriptId":"u20"},
    "b8f6801094184a44bab2a8193db79c34":{
      "scriptId":"u21"},
    "93fa2cb9128c42979f18799dfe8d7286":{
      "scriptId":"u22"},
    "6f883acee0ac473ea00d69c327b432dd":{
      "scriptId":"u23"},
    "9a160d500a7b4048b543e58c5840d020":{
      "scriptId":"u24"},
    "20dca46276dd4a5f87def2f22d27d875":{
      "scriptId":"u25"},
    "6782ce90abc84a159f8ac227bf528113":{
      "scriptId":"u26"},
    "5f8b430ba8b844c2abeaf67100d7d770":{
      "scriptId":"u27"},
    "86126e4a5bc840e19d37cc5669ede981":{
      "scriptId":"u28"},
    "a514225689f446a2bc1d95a3d9fa891d":{
      "scriptId":"u29"},
    "8b49a0e539784ab9b723eb1393fbd3da":{
      "scriptId":"u30"},
    "b9be77029a5244c484127dfb7605835d":{
      "scriptId":"u31"},
    "656d8a9ae093413382244ff38eece9c0":{
      "scriptId":"u32"},
    "77ebec4e67824469abd2f3f74d33f9c0":{
      "scriptId":"u33"},
    "bfc5342014af4258bb8e907d0b6d18e6":{
      "scriptId":"u34"},
    "52499844e4f4492598b84dcb2fe0d980":{
      "scriptId":"u35"},
    "ed42beffba554175bad4b55399c8203a":{
      "scriptId":"u36"},
    "8ae75daeb70c4ed390cd77677f182b4b":{
      "scriptId":"u37"},
    "8f15f4f49b9a417499439453943ac422":{
      "scriptId":"u38"},
    "58cdcba09c1d456db6dc05d80431dbd7":{
      "scriptId":"u39"},
    "4ced19202344451bb7e34bd1b5a756d8":{
      "scriptId":"u40"},
    "744e8509c065496ca5d11d9c615c46ee":{
      "scriptId":"u41"},
    "2a058ce370fc476d82b667aa840b8659":{
      "scriptId":"u42"},
    "9f5e8ea409e9425aa45a81db708a9031":{
      "scriptId":"u43"},
    "fc090a5a22504d06b5cab9f42cd36241":{
      "scriptId":"u44"},
    "d67b1648df7047c49d4f6dae23e9ff33":{
      "scriptId":"u45"},
    "091284071cd949878e685c3931049d6e":{
      "scriptId":"u46"},
    "048edc49a2b34865b25682dd536935d0":{
      "scriptId":"u47"},
    "06e6b9a5555148b7ae867258e54114bc":{
      "scriptId":"u48"},
    "2e711ea8e91d4498a6feb39c26dd9968":{
      "scriptId":"u49"},
    "dd60599158984b5a9b0c7c0dfe404474":{
      "scriptId":"u50"},
    "679dc440c6cd452cbb1cffa879fe3808":{
      "scriptId":"u51"},
    "729df597b3ab4ec58feb74c8933617f3":{
      "scriptId":"u52"},
    "393250b8d1cf4454a6dd7bce576ad611":{
      "scriptId":"u53"},
    "319d88a9e28741b68cf9c532cb27a544":{
      "scriptId":"u54"},
    "8b5c05d0600143228c24f2d10c6e5481":{
      "scriptId":"u55"},
    "775d3b602412414685e71bdd61b70da1":{
      "scriptId":"u56"},
    "dfcab8ae6c7d4098a1d92b7ab04500b2":{
      "scriptId":"u57"},
    "5704e30ecbdc41ea84dac6f62475357b":{
      "scriptId":"u58"},
    "eb1279706f304cb4b9f6c897b18d4f24":{
      "scriptId":"u59"},
    "76ba32c18eaa4a489c2918ce34b62adf":{
      "scriptId":"u60"},
    "4720e61a6d0244c2954c85c4ad6d8b08":{
      "scriptId":"u61"},
    "7dfc7685cb004d0a970c5a2070975c97":{
      "scriptId":"u62"},
    "5b4480d9a6e54b268b559aa7101097e9":{
      "scriptId":"u63"},
    "7ec859c9dc3b4816982a72ef97660f01":{
      "scriptId":"u64"},
    "a20114a9deac41159f349048274616dc":{
      "scriptId":"u65"},
    "a8478738c9b943f2af82a7d0b64a5ac8":{
      "scriptId":"u66"},
    "f070be8f62fe4d3ea0b7dbc09b575bb3":{
      "scriptId":"u67"},
    "d80535ef847c469da8ffb4aa82346ce5":{
      "scriptId":"u68"},
    "f0bf38a84ee1496586e5a5a127a0ff13":{
      "scriptId":"u69"},
    "b56e3490fb5b4c7da228860e958f060a":{
      "scriptId":"u70"},
    "7b7be1649817442098103f1a77201cb6":{
      "scriptId":"u71"},
    "e51b40c5294a4c1c99623a0dd98dfcc3":{
      "scriptId":"u72"},
    "72cb029e41fc4407a0f947da42b1ea3a":{
      "scriptId":"u73"},
    "8e6e3fbfcd624b6184d7fc65464c7b05":{
      "scriptId":"u74"},
    "2f0916132322445bbca221685dc69ee3":{
      "scriptId":"u75"},
    "ecef13dcba344bad8c78d11195ebc038":{
      "scriptId":"u76"},
    "75d086de27744c0781d6fb831bba72d4":{
      "scriptId":"u77"},
    "15967cd897414796aedb373648271c66":{
      "scriptId":"u78"},
    "286e9b7287bc44d3a3d87f3ee99aeb8b":{
      "scriptId":"u79"},
    "d076734909c942e09c0ca5dc9917b188":{
      "scriptId":"u80"},
    "966f74a4557543d0895bfec847e33de8":{
      "scriptId":"u81"},
    "c631af3b09cb4b6e9080b4fd1925a4be":{
      "scriptId":"u82"},
    "99fbb6a9929c41b2beeb0e2d93b624bb":{
      "scriptId":"u83"},
    "d7b628a7cfb3432080e7ef05f5369ce3":{
      "scriptId":"u84"},
    "d1227dc139d44b1594ee4daa7755e918":{
      "scriptId":"u85"},
    "ae11ab16eaa14a1cbc10799c4959f4ea":{
      "scriptId":"u86"},
    "6e781674470c4e30ab89f957734bcc19":{
      "scriptId":"u87"},
    "be460cca43c6475aaf47f5f9fa55eab1":{
      "scriptId":"u88"},
    "57b7f67f7bee40d088a89dc043e100db":{
      "scriptId":"u89"},
    "ac8d4abca13445e8a107940a7a7f851c":{
      "scriptId":"u90"},
    "bf2276d61ddc43b59dc246aaf2fce8ab":{
      "scriptId":"u91"},
    "d022044b843047a987428283638ac756":{
      "scriptId":"u92"},
    "dfaec7e69fbf4fc1b184582da93f95fa":{
      "scriptId":"u93"},
    "1cbd173080554003b667500cd063efc6":{
      "scriptId":"u94"},
    "41ac721f2cfe49659a9402258274a993":{
      "scriptId":"u95"},
    "16c40d39334d4ab291ab125f0635af06":{
      "scriptId":"u96"},
    "0d42f238581849b38c448973593a0c56":{
      "scriptId":"u97"},
    "3c96d9f0e3734c62babeea5654188c77":{
      "scriptId":"u98"},
    "7a01b90f46704e6587e384c7b57ab209":{
      "scriptId":"u99"},
    "aeb9a3158b614f2aaf4fe6a0fb362a7c":{
      "scriptId":"u100"},
    "ebafee1ffdc34812a5427666050107be":{
      "scriptId":"u101"},
    "5edcd3f364554c0f8c0f86e8eb037b26":{
      "scriptId":"u102"},
    "dd980fd4531d4b47940eb6a58ed0e660":{
      "scriptId":"u103"},
    "d15a90667de04ad28ac1bf0e12814bbd":{
      "scriptId":"u104"},
    "0ca1020c4e704afe8e3a9ee7a39abac0":{
      "scriptId":"u105"},
    "7d20f96362d94674b8cb5a425556d4a9":{
      "scriptId":"u106"},
    "bd59c73c2fb448229c31cfca79f61e70":{
      "scriptId":"u107"},
    "f7ad42f333aa4137ba4211e0799fc8ad":{
      "scriptId":"u108"},
    "f471c956cc434b4782dec5c501c43d3d":{
      "scriptId":"u109"},
    "ace114ab3bbe4309a6fa7e1112ee7534":{
      "scriptId":"u110"}}});