insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0000', 'Kingdom of Cambodia', '0000', 1, 0);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0100', 'Phnom Penh', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0200', 'Banteay Meanchey', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0300', 'Battambang', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0400', 'Kampong Cham', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0500', 'Kampong Chhnang', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0600', 'Kampong Speu', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0700', 'Kampong Thom', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0800', 'Kampot', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0900', 'Kandal', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1000', 'Koh Kong', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1100', 'Kep', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1200', 'Krati¨¦', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1300', 'Mondulkiri', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1400', 'Oddar Meanchey', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1500', 'Pailin', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1600', 'Sihanoukville', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1700', 'Preah Vihear', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1800', 'Pursat', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1900', 'Prey Veng', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2000', 'Ratanakiri', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2100', 'Siem Reap', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2200', 'Stung Treng', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2300', 'Svay Rieng', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2400', 'Takeo', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2500', 'Tbong Khmum', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2600', 'Poipet', '0000', 1, 1);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0101', 'Chamkarmon', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0102', 'Chbar Ampov', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0103', 'Chroy Changva', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0104', 'Dangkao', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0105', 'Daun Penh', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0106', 'Meanchey', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0107', 'Prampi Makara', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0108', 'Russey Keo', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0109', 'Sen Sok', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0110', 'Tuol Kork', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0111', 'Porsenchey', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0112', 'Prek Pnov', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0113', 'Takmao', '0100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0201', 'Mongkol Borey', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0202', 'Phnom Srok', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0203', 'Preah Net Preah', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0204', 'Ou Chrov', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0205', 'Serei Saophoan', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0206', 'Thmar Puok', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0207', 'Svay Chek', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0208', 'Malai', '0200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0301', 'Banan', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0302', 'Thmar Koul', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0303', 'Battambang', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0304', 'Bavel', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0305', 'Aek Phnom', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0306', 'Moung Russei', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0307', 'Rotanak Mondul', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0308', 'Sangkhae', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0309', 'Samlout', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0310', 'Sampov Loun', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0311', 'Phnom Proek', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0312', 'Kamrieng', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0313', 'Koas Krala', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0314', 'Ruhakiri', '0300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0401', 'Batheay', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0402', 'Chamkar Leu', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0403', 'Cheung Prey', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0404', 'Kampong Cham', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0405', 'Kampong Siem', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0406', 'Kang Meas', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0407', 'Koh Sotin', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0408', 'Prey Chhor', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0409', 'Srey Santhor', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0410', 'Stueng Trang', '0400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0501', 'Baribour', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0502', 'Chol Kiri', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0503', 'Kampong Chhnang', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0504', 'Kampong Leng', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0505', 'Kampong Tralach', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0506', 'Rolea Bier', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0507', 'Samaki Meanchey', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0508', 'Tuek Phos', '0500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0601', 'Baset', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0602', 'Chbar Mon', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0603', 'Kong Pisei', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0604', 'Aural', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0605', 'Udong', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0606', 'Phnom Sruoch', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0607', 'Samraong Tong', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0608', 'Thpong', '0600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0701', 'Baray', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0702', 'Kampong Svay', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0703', 'Stung Sen', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0704', 'Prasat Balang', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0705', 'Prasat Sambour', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0706', 'Sandan', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0707', 'Santuk', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0708', 'Stoung', '0700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0801', 'Angkor Chey', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0802', 'Banteay Meas', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0803', 'Chhuk', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0804', 'Chum Kiri', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0805', 'Dang Tong', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0806', 'Kampong Trach', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0807', 'Teouk Chhou', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0808', 'Kampot Town', '0800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0901', 'Kandal Steung', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0902', 'Kien Svay', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0903', 'Khsach Kandal', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0904', 'Koh Thom', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0905', 'Leuk Daek', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0906', 'Lavear Em', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0907', 'Mukh Kamphol', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0908', 'Ang Snuol', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0909', 'Ponhea Leu', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0910', 'S`ang', '0900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1001', 'Botum Sakor', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1002', 'Kiri Sakor', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1003', 'Koh Kong', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1004', 'Krong Kamarakpumin', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1005', 'Mondol Seima', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1006', 'Srae Ambel', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1007', 'Thmar Bang', '1000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1101', 'Koh Tonsay', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1102', 'Koh Kok', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1103', 'Koh Matay', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1104', 'Koh Svay', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1105', 'Koh Kbal', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1106', 'Koh Hal Trey', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1107', 'Koh Svay Prey', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1108', 'Koh Sarang', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1109', 'Koh Pou', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1110', 'Koh Makprang', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1111', 'Koh Angrong', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1112', 'Koh Seh', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1113', 'Koh Sngout', '1100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1201', 'Chhloung', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1202', 'Krati¨¦', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1203', 'Praek Prasab', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1204', 'Sambour', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1205', 'Snuol', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1206', 'Chet Borei', '1200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1301', 'Keo Seima', '1300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1302', 'Kaoh Neak', '1300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1303', 'O Reang', '1300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1304', 'Pech Chenda', '1300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1305', 'Senmonorom', '1300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1401', 'Anlong Veng', '1400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1402', 'Banteay Ampil', '1400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1403', 'Chong Kal', '1400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1404', 'Samraong', '1400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1405', 'Trapeang Prasat', '1400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1501', 'Pailin', '1500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1502', 'Sala Krau', '1500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1601', 'Mittakpheap', '1600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1602', 'Prey Nob', '1600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1603', 'Stueng Hav', '1600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1604', 'Kampong Seila', '1600', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1701', 'Chey Saen', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1702', 'Chhaeb', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1703', 'Chaom Khsant', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1704', 'Kulen', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1705', 'Rovieng', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1706', 'Sangkom Thmei', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1707', 'Tbeng Meanchey', '1700', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1801', 'Bakan', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1802', 'Kandieng', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1803', 'Krakor', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1804', 'Phnom Kravanh', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1805', 'Sampov Meas', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1806', 'Veal Veng', '1800', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1901', 'Ba Phnum', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1902', 'Kamchay Mear', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1903', 'Kampong Trabaek', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1904', 'Kanhchriech', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1905', 'Me Sang', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1906', 'Peam Chor', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1907', 'Peam Ro', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1908', 'Pea Reang', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1909', 'Preah Sdach', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1910', 'Prey Veng', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1911', 'Kampong Leav', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1912', 'Sithor Kandal', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('1913', 'Svay Antor', '1900', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2001', 'Andoung Meas', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2002', 'Banlung', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2003', 'Bar Kaev', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2004', 'Koun Mom', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2005', 'Lumphat', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2006', 'Ou Chum', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2007', 'Ou Ya Dav', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2008', 'Ta Veaeng', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2009', 'Veun Sai', '2000', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2101', 'Angkor Chum', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2102', 'Angkor Thom', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2103', 'Banteay Srei', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2104', 'Chi Kraeng', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2105', 'Kralanh', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2106', 'Puok', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2107', 'Prasat Bakong', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2108', 'Siem Reap', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2109', 'Sout Nikom', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2110', 'Srei Snam', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2111', 'Svay Leu', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2112', 'Varin', '2100', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2201', 'Sesan', '2200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2202', 'Siem Bouk', '2200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2203', 'Siem Pang', '2200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2204', 'Stung Treng', '2200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2205', 'Thala Barivat', '2200', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2301', 'Chanthrea', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2302', 'Kampong Rou', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2303', 'Romdoul', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2304', 'Romeas Haek', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2305', 'Svay Chrom', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2306', 'Svay Rieng', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2307', 'Svay Theab', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2308', 'Krong Bavet', '2300', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2401', 'Angkor Borei', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2402', 'Bathi', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2403', 'Borey Cholsar', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2404', 'Kirivong', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2405', 'Koh Andaet', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2406', 'Prey Kabbas', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2407', 'Samraong', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2408', 'Daun Kaev', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2409', 'Tram Kak', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2410', 'Treang', '2400', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2501', 'Dambae', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2502', 'Krouch Chhma', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2503', 'Memot', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2504', 'Ou Reang Ov', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2505', 'Ponhea Kraek', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2506', 'Tboung Khmum District', '2500', 1, 2);
insert into INF_AREAS (AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('2507', 'Suong City', '2500', 1, 2);
insert into INF_AREAS(AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0114','KOH PICH','0100',1,2);
insert into INF_AREAS(AREA_CODE, AREA_NAME, SUPER_AREA, STATUS, AREA_TYPE) values ('0115','KOH PICH TEMP','0100',1,2);

commit;
